import type {AppContext,Feature} from '../../app/contracts';
import {element,button,downloadText,csvDocument,format} from '../../ui/components/dom';
import {rowObject} from '../../domain/benchmark/types';
import {DEFAULT_HYBRID_POLICY,hybridIsCurrent,type HybridOptions} from '../../analysis/contingency-hybrid';
import {scenarioSignature} from '../../domain/scenario/overlay';
import {downloadComparisonWorkbook} from '../analysis/comparison-export';

/** Policy controls are separate from operational limits. All downloads remain user initiated. */
export function createCalculationActions(ctx:AppContext,analysis:()=>string,selected:()=>import('../../analysis/contingency-ac').AcOutage|null=()=>null):Feature{
  const root=element('div'),hybridPanel=element('div','ga-notice'),scPanel=element('div','ga-notice');root.append(hybridPanel,scPanel);
  const number=(label:string,value:number,min:number,max:number)=>{const w=element('label','ga-field',label),input=element('input');input.type='number';input.value=String(value);input.min=String(min);input.max=String(max);input.step='any';input.setAttribute('aria-label',label);w.append(input);return {w,input};};
  const threshold=number('DC promosyon eşiği % (kullanıcı politikası)',90,0,1000),budget=number('AC vaka bütçesi',10,0,100),perCase=number('Vaka zaman sınırı s',120,1,300),global=number('Toplam zaman sınırı s',300,1,1800),loading=number('İşletme yük limiti %',100,1,1000),vmin=number('AC min Vpu',.9,.1,2),vmax=number('AC max Vpu',1.1,.1,2);
  const fields=element('div','ga-toolbar'),scope=element('select'),season=element('select');scope.setAttribute('aria-label','Hibrit YTM kapsamı');season.setAttribute('aria-label','Hibrit kapasite mevsimi');for(const v of ['nominal','summer','winter']){const o=element('option','',v);o.value=v;season.append(o);}fields.append(threshold.w,budget.w,perCase.w,global.w,loading.w,vmin.w,vmax.w,scope,season);
  const risks=element('div','ga-toolbar'),riskInputs=new Map<string,HTMLInputElement>();
  for(const [key,label]of [['includeDCViolation','DC aşımı'],['includeCapacityUnavailable','Eksik rating'],['includeUnscreenable','Taranamayan'],['classifyIslanding','Ada ayıran'],['includeExplicitUserSelection','Açık seçim']] as const){const w=element('label','ga-field',label),i=element('input');i.type='checkbox';i.checked=true;i.setAttribute('aria-label',label);riskInputs.set(key,i);w.append(i);risks.append(w);}
  const hybridOptions=():HybridOptions=>{
    const t=ctx.benchmark?.groups.N1.tables.N1_RecordedExtrema_Raw;
    const observations=t?t.rows.flatMap(r=>{const row=rowObject(t,r);return ['postLoadingPercent','postPmw','postQmvar','postMva','postVoltagePu'].map(metric=>({sourceClass:String(row.affectedClass??''),fid:String(row.affectedFid??''),metric,side:String(row.postPowerEndpoint??''),caseId:String(row.caseId??'')}));}):[];
    const chosen=selected(),equipment=chosen?(chosen.sourceClass==='ElmLne'?ctx.network?.lines:ctx.network?.transformers)?.find(e=>e.sourceId===chosen.fid):null;
    return {selectedCandidateIds:equipment?[`${equipment.sourceClass}:${equipment.id}`]:undefined,filter:scope.value?{ytmId:scope.value}:{},season:season.value as HybridOptions['season'],observations,policy:{...DEFAULT_HYBRID_POLICY,...Object.fromEntries([...riskInputs].map(([k,i])=>[k,i.checked])),dcPromotionLoadingPercent:Number(threshold.input.value),acBudgetCases:Number(budget.input.value),perCaseTimeLimitMs:Number(perCase.input.value)*1000,globalTimeLimitMs:Number(global.input.value)*1000,operationalLoadingLimitPercent:Number(loading.input.value),voltageMinPu:Number(vmin.input.value),voltageMaxPu:Number(vmax.input.value),limitsProvenance:limitsFromManifest?'PF_N1_RunManifest_Raw + current visible user overrides':'USER_OPERATIONAL_PROFILE',promotionProvenance:'USER_POLICY; NOT_INFERRED_FROM_PF'}};
  };
  const run=button('Otomatik hibrit (DC → Full AC)',()=>void ctx.runHybrid(hybridOptions())),resume=button('Hibrit devam et',()=>void ctx.runHybrid(hybridOptions(),true)),stop=button('Hibrit durdur',()=>ctx.cancel()),summary=element('p'),cases=element('details'),casesTitle=element('summary','','Hibrit vaka özeti'),caseBody=element('div');cases.append(casesTitle,caseBody);cases.ontoggle=()=>render();
  const hybridRows=()=>[['caseId','sourceClass','FID','status','reason','promotionReasons','DC','iterations','mismatchMW','minVpu','maxVpu','maxLoadingPercent','unknownRatings','modelHash','scenarioHash','settingsHash','optionsHash','method','scope','season'],...(ctx.hybridResult?.cases??[]).map(c=>[c.outage.caseId,c.outage.sourceClass,c.outage.fid,c.status,c.reason,c.promotionReasons.join(';'),c.dcStatus,c.iterations,c.maxMismatchMw,c.minVpu,c.maxVpu,c.maxLoadingPercent,c.unknownRatings,ctx.hybridResult!.identity.modelHash,ctx.hybridResult!.identity.scenarioHash,ctx.hybridResult!.identity.settingsHash,ctx.hybridResult!.identity.optionsHash,ctx.hybridResult!.method,JSON.stringify(ctx.hybridResult!.filter),ctx.hybridResult!.season])];
  hybridPanel.append(element('h3','','N-1 HİBRİT (DC → Full AC)'),fields,risks,element('p','ga-muted','DC ≥66 kV P-only. 90% promosyon bir kullanıcı politikasıdır; 100% ve 0.90–1.10 işletme limitleri yalnız AC sonrasında uygulanır. Eksik rating UNKNOWN; sınırlı kapsam güvenli şebeke anlamına gelmez. Eşzamanlı AC: 1.'),run,resume,stop,button('Hibrit JSON',()=>downloadText(JSON.stringify(ctx.hybridResult,null,2),'GA_Hybrid.local.json','application/json')),button('Hibrit CSV',()=>downloadText(csvDocument(hybridRows()),'GA_Hybrid.local.csv','text/csv;charset=utf-8')),button('Hibrit XLSX',()=>downloadComparisonWorkbook([{name:'Hybrid',rows:hybridRows()}])),summary,cases);
  const factor=number('SC c faktörü (açık yaklaşım profili)',1.1,.1,2),faultBudget=number('SC fault bütçesi',10,1,10000),scTime=number('SC zaman sınırı s',120,1,300),terminals=element('textarea'),scSummary=element('p'),scDetails=element('details'),scBody=element('div');terminals.rows=3;terminals.setAttribute('aria-label','SC fiziksel terminal FID seçimi');terminals.style.width='100%';
  const scRun=button('GA 3PH MAX hesap',()=>void ctx.runSc(terminals.value.split(/[\s,;]+/).filter(Boolean),{faultType:'3PH',calculateMode:'MAX',voltageFactor:Number(factor.input.value),factorProvenance:'EXPLICIT_USER_NETWORK_APPROXIMATION_PROFILE; NOT_VERIFIED_IEC_CMAX',edition:null,rfOhm:0,xfOhm:0,maxFaults:Number(faultBudget.input.value),timeBudgetMs:Number(scTime.input.value)*1000}));
  const scRows=()=>[['physicalTerminalFID','electricalBusId','nominalKv','status','reason','ZkkRohm','ZkkXohm','Ikss_kA','Skss_MVA','Ip_kA','Ib_kA','Ith_kA','residual','modelHash','scenarioHash','profileHash','method','edition','faultType','scope','factorProvenance'],...(ctx.scResult?.faults??[]).map(f=>[f.physicalTerminalFid,f.electricalBusId,f.nominalKv,f.status,f.reasons.join(';'),f.zkkOhm?.re??null,f.zkkOhm?.im??null,f.ikssKa,f.skssMva,f.ipKa,f.ibKa,f.ithKa,f.residual,ctx.scResult!.identity.modelHash,ctx.scResult!.identity.scenarioHash,ctx.scResult!.identity.profileHash,ctx.scResult!.method,ctx.scResult!.profile.edition,ctx.scResult!.profile.faultType,'EXPLICIT_SELECTED_PHYSICAL_TERMINALS',ctx.scResult!.profile.factorProvenance])];
  scDetails.append(element('summary','','GA SC kapsam & engeller'),scBody);scDetails.ontoggle=()=>render();
  scPanel.append(element('h3','','GA bağımsız 3PH MAX'),element('p','ga-muted','CALCULATED_NETWORK_APPROXIMATION: fiziksel kaynak R/X gerekir; IEC edisyonu ve düzeltmeleri doğrulanmış değildir. Ip/Ib/Ith null. 1LG/LL/2LG kapalıdır. Kaynak veya converter katkısı eksikse ilgili fault BLOCKED.'),factor.w,faultBudget.w,scTime.w,terminals,scRun,button('SC durdur',()=>ctx.cancel()),button('SC JSON',()=>downloadText(JSON.stringify(ctx.scResult,null,2),'GA_SC.local.json','application/json')),button('SC CSV',()=>downloadText(csvDocument(scRows()),'GA_SC.local.csv','text/csv;charset=utf-8')),button('SC XLSX',()=>downloadComparisonWorkbook([{name:'SC',rows:scRows()}])),button('SC alan audit JSON',()=>downloadText(JSON.stringify(ctx.scContext?.audit??[],null,2),'GA_SC_Field_Audit.local.json','application/json')),scSummary,scDetails);
  let network=ctx.network,loaded=false,limitsFromManifest=false;
  const invalidateHybrid=()=>{if(ctx.busy)ctx.cancel();ctx.hybridResult=null;ctx.notify();};
  for(const i of [threshold.input,budget.input,perCase.input,global.input,loading.input,vmin.input,vmax.input,scope,season,...riskInputs.values()])i.onchange=invalidateHybrid;
  const invalidateSc=()=>{if(ctx.busy)ctx.cancel();ctx.scResult=null;ctx.notify();};
  for(const i of [factor.input,faultBudget.input,scTime.input,terminals])i.onchange=invalidateSc;
  function render(){
    if(network!==ctx.network||!loaded&&ctx.network){network=ctx.network;loaded=true;scope.replaceChildren();const all=element('option','','Tüm YTM’ler (ALL)');all.value='';scope.append(all);const areas=new Map(ctx.network?.sites.map(s=>[s.areaId,s.areaName]));for(const[id,name]of areas){if(!id)continue;const o=element('option','',name);o.value=id;scope.append(o);if(name==='Orta Anadolu YTM')scope.value=id;}
      const t=ctx.benchmark?.groups.N1.tables.N1_RunManifest_Raw,r=t?.rows[0]?rowObject(t,t.rows[0]):null;limitsFromManifest=!!r&&r.loadingLimitPercent===100&&r.minVoltagePu===.9&&r.maxVoltagePu===1.1;
      if(limitsFromManifest){loading.input.value='100';vmin.input.value='.9';vmax.input.value='1.1';}
      const sc=ctx.benchmark?.groups.SC.tables.SC_BusResults_Raw;terminals.value=sc?sc.rows.slice(0,10).map(r=>String(rowObject(sc,r).physicalTerminalFid??'')).filter(Boolean).join('\n'):ctx.network?.buses.filter(b=>b.inService).slice(0,10).map(b=>b.sourceId).join('\n')??'';
    }
    hybridPanel.hidden=analysis()!=='N1';scPanel.hidden=analysis()!=='SC';run.disabled=ctx.busy||!ctx.network;resume.disabled=ctx.busy||!ctx.hybridResult||!ctx.network||!hybridIsCurrent(ctx.hybridResult,ctx.network,ctx.scenario.current,ctx.analysisSettings.value);stop.disabled=!ctx.busy;
    summary.textContent=ctx.hybridResult?`${ctx.hybridResult.phase} · ${ctx.hybridResult.status} · ${JSON.stringify(ctx.hybridResult.counts)} · ${ctx.hybridResult.reason}`:'Hibrit hesap bekleniyor';
    caseBody.replaceChildren();if(cases.open)for(const c of ctx.hybridResult?.cases.slice(0,30)??[]){const p=element('p','',`${c.outage.caseId} · ${c.status} · ${c.promotionReasons.join(', ')} · V ${format(c.minVpu)}–${format(c.maxVpu)} · ${c.reason}`);p.append(button('Vaka AC detayını hesapla',()=>void ctx.runN1AcValidation([c.outage])));caseBody.append(p);}
    scRun.disabled=ctx.busy||!ctx.scContext;scRun.title=ctx.scContext?'Kaynak modeli olmayan faultlar nedenleriyle reddedilir':'MODEL_SOURCE_CONTEXT_MISSING';
    const current=ctx.scResult&&ctx.network&&ctx.scResult.identity.modelHash===ctx.network.modelHash&&ctx.scResult.identity.scenarioHash===scenarioSignature(ctx.scenario.current);
    scSummary.textContent=current?`${JSON.stringify(ctx.scResult!.counts)} · ${ctx.scResult!.factorizations} sparse faktorizasyon · ${ctx.scResult!.rhsCount} RHS · IEC parity: BLOCKED`:'GA SC hesap bekleniyor';
    scBody.replaceChildren();if(scDetails.open)for(const f of current?ctx.scResult!.faults.slice(0,30):[])scBody.append(element('p','',`${f.physicalTerminalFid} → ${f.electricalBusId??'—'} · ${f.status} · Ikss ${format(f.ikssKa)} kA · Skss ${format(f.skssMva)} MVA · ${f.reasons.slice(0,3).join('; ')}${f.reasons.length>3?' … '+f.reasons.length+' kaynak engeli':''}`));
  }
  render();return {element:root,render};
}
