import type {AppContext,Feature} from '../../app/contracts';
import {element,button,downloadText,csvDocument,format} from '../../ui/components/dom';
import {rowObject} from '../../domain/benchmark/types';
import {DEFAULT_HYBRID_POLICY,hybridIsCurrent,type HybridOptions} from '../../analysis/contingency-hybrid';
import {hybridStudySettings,type HybridStudyProfile} from '../../analysis/contingency-hybrid/profile';
import {approximationModeProfiles} from '../../analysis/short-circuit/mode-profiles';
import {scenarioSignature} from '../../domain/scenario/overlay';
import {createStudyScope} from './study-scope-controls';
import {filterN1CatalogCandidates} from '../../domain/n1/catalog';
import {selectFaultTerminals} from '../../domain/benchmark/study-scope';
import {downloadComparisonWorkbook} from '../analysis/comparison-export';

/** Policy controls are separate from operational limits. All downloads remain user initiated. */
export function createCalculationActions(ctx:AppContext,analysis:()=>string,selected:()=>import('../../analysis/contingency-ac').AcOutage|null=()=>null):Feature{
  const root=element('div'),hybridPanel=element('div','ga-notice'),scPanel=element('div','ga-notice');root.append(hybridPanel,scPanel);
  const number=(label:string,value:number,min:number,max:number)=>{const w=element('label','ga-field',label),input=element('input');input.type='number';input.value=String(value);input.min=String(min);input.max=String(max);input.step='any';input.setAttribute('aria-label',label);w.append(input);return {w,input};};
  const threshold=number('DC promosyon eşiği % (kullanıcı politikası)',90,0,1000),budget=number('AC vaka bütçesi',10,0,100),perCase=number('Vaka zaman sınırı s',120,1,300),global=number('Toplam zaman sınırı s',300,1,1800),loading=number('İşletme yük limiti %',100,1,1000),vmin=number('AC min Vpu',.9,.1,2),vmax=number('AC max Vpu',1.1,.1,2);
  const fields=element('div','ga-toolbar'),scopeControls=createStudyScope('Hibrit'),scope=scopeControls.areas,season=element('select');season.setAttribute('aria-label','Hibrit kapasite mevsimi');for(const v of ['nominal','summer','winter']){const o=element('option','',v);o.value=v;season.append(o);}fields.append(threshold.w,budget.w,perCase.w,global.w,loading.w,vmin.w,vmax.w,scopeControls.element,season);
  const studyProfile=element('select');studyProfile.setAttribute('aria-label','Hibrit kontrol profili');for(const [value,label] of [['CURRENT_SETTINGS','Güncel Full AC ayarları (kontrol desteği doğrulanmalı)'],['GA_APPROX_STATION_OFF','GA_APPROX_STATION_OFF — açık onay: CONTROL_FIDELITY_PARTIAL / NOT_PF_PARITY']]){const o=element('option','',label);o.value=value;studyProfile.append(o);}fields.append(studyProfile);
  const controlInfo=element('p');fields.append(controlInfo);
  const risks=element('div','ga-toolbar'),riskInputs=new Map<string,HTMLInputElement>();
  for(const [key,label]of [['includeDCViolation','DC aşımı'],['includeCapacityUnavailable','Eksik rating'],['includeUnscreenable','Taranamayan'],['classifyIslanding','Ada ayıran'],['includeExplicitUserSelection','Açık seçim']] as const){const w=element('label','ga-field',label),i=element('input');i.type='checkbox';i.checked=true;i.setAttribute('aria-label',label);riskInputs.set(key,i);w.append(i);risks.append(w);}
  const allAc=element('input'),allAcLabel=element('label','ga-field','Seçili kapsamdaki tüm vakaları Full AC çöz');allAc.type='checkbox';allAc.setAttribute('aria-label','Seçili kapsamın tüm vakalarını Full AC');allAcLabel.append(allAc);risks.append(allAcLabel);
  const clearSample=number('DC temiz vaka AC doğrulama örneği',1,0,100);fields.append(clearSample.w);
  const selectedIds=new Set<string>(),catalog=element('details'),catalogTitle=element('summary','','YTM N-1 kataloğu'),catalogBody=element('div'),catalogInfo=element('p');let catalogPage=0,casePage=0,detailCase='';
  const candidates=()=>filterN1CatalogCandidates(ctx.n1CatalogResult?.candidates??[],scopeControls.filter());
  catalog.append(catalogTitle,button('Tam N-1 kataloğunu hazırla',()=>void ctx.loadN1Catalog('scenario',season.value as HybridOptions['season']&string,true)),catalogInfo,button('Kapsamdaki vakaları seç',()=>{for(const c of candidates())selectedIds.add(c.candidateId);invalidateHybrid();render();}),button('Vaka seçimini temizle',()=>{selectedIds.clear();invalidateHybrid();render();}),catalogBody,button('Katalog önceki',()=>{catalogPage=Math.max(0,catalogPage-1);render();}),button('Katalog sonraki',()=>{catalogPage++;render();}));catalog.ontoggle=()=>render();
  const hybridOptions=():HybridOptions=>{
    const t=ctx.benchmark?.groups.N1.tables.N1_RecordedExtrema_Raw;
    const observations=t?t.rows.flatMap(r=>{const row=rowObject(t,r);return ['postLoadingPercent','postPmw','postQmvar','postMva','postVoltagePu'].map(metric=>({sourceClass:String(row.affectedClass??''),fid:String(row.affectedFid??''),metric,side:String(row.postPowerEndpoint??''),caseId:String(row.caseId??'')}));}):[];
    const chosen=selected(),equipment=chosen?(chosen.sourceClass==='ElmLne'?ctx.network?.lines:ctx.network?.transformers)?.find(e=>e.sourceId===chosen.fid):null;
    const ids=[...new Set([...selectedIds,...(equipment?[`${equipment.sourceClass}:${equipment.id}`]:[])])];
    return {studyProfile:studyProfile.value as HybridStudyProfile,catalogCandidateIds:ids.length?ids:undefined,solveAllSelected:allAc.checked,dcClearValidationCases:Number(clearSample.input.value),selectedCandidateIds:[...new Set([...selectedIds,...(equipment?[`${equipment.sourceClass}:${equipment.id}`]:[])])],filter:scopeControls.filter(),season:season.value as HybridOptions['season'],observations,policy:{...DEFAULT_HYBRID_POLICY,...Object.fromEntries([...riskInputs].map(([k,i])=>[k,i.checked])),dcPromotionLoadingPercent:Number(threshold.input.value),acBudgetCases:Number(budget.input.value),perCaseTimeLimitMs:Number(perCase.input.value)*1000,globalTimeLimitMs:Number(global.input.value)*1000,operationalLoadingLimitPercent:Number(loading.input.value),voltageMinPu:Number(vmin.input.value),voltageMaxPu:Number(vmax.input.value),limitsProvenance:limitsFromManifest?'PF_N1_RunManifest_Raw + current visible user overrides':'USER_OPERATIONAL_PROFILE',promotionProvenance:'USER_POLICY; NOT_INFERRED_FROM_PF'}};
  };
  const run=button('Otomatik hibrit (DC → Full AC)',()=>void ctx.runHybrid(hybridOptions())),resume=button('Hibrit devam et',()=>void ctx.runHybrid(hybridOptions(),true)),stop=button('Hibrit durdur',()=>ctx.cancel()),summary=element('p'),cases=element('details'),casesTitle=element('summary','','Hibrit vaka özeti'),caseBody=element('div');cases.append(casesTitle,caseBody);cases.ontoggle=()=>render();
  const hybridRows=()=>[['caseId','sourceClass','FID','YTM_from','YTM_to','voltageKv','topology','unsuppliedLoadMW','voltageViolations','thermalViolations','status','reason','promotionReasons','DC','iterations','mismatchMW','minVpu','maxVpu','maxLoadingPercent','unknownRatings','constraintCounts','modelHash','scenarioHash','settingsHash','optionsHash','method','scope','season'],...(ctx.hybridResult?.cases??[]).map(c=>[c.outage.caseId,c.outage.sourceClass,c.outage.fid,c.metadata?.fromYtmIds.join(';')??'',c.metadata?.toYtmIds.join(';')??'',c.metadata?.voltageKv??null,c.metadata?.topology??'',c.unsuppliedLoadMw??null,c.voltageViolations,c.thermalViolations,c.status,c.reason,c.promotionReasons.join(';'),c.dcStatus,c.iterations,c.maxMismatchMw,c.minVpu,c.maxVpu,c.maxLoadingPercent,c.unknownRatings,JSON.stringify(c.constraintCounts??{}),ctx.hybridResult!.identity.modelHash,ctx.hybridResult!.identity.scenarioHash,ctx.hybridResult!.identity.settingsHash,ctx.hybridResult!.identity.optionsHash,ctx.hybridResult!.method,JSON.stringify(ctx.hybridResult!.filter),ctx.hybridResult!.season])];
  hybridPanel.append(element('h3','','N-1 HİBRİT (DC → Full AC)'),fields,risks,element('p','ga-muted','DC ≥66 kV P-only. 90% promosyon bir kullanıcı politikasıdır; 100% ve 0.90–1.10 işletme limitleri yalnız AC sonrasında uygulanır. Eksik rating UNKNOWN; sınırlı kapsam güvenli şebeke anlamına gelmez. Eşzamanlı AC: 1.'),run,resume,stop,button('Hibrit JSON',()=>downloadText(JSON.stringify(ctx.hybridResult,null,2),'GA_Hybrid.local.json','application/json')),button('Hibrit CSV',()=>downloadText(csvDocument(hybridRows()),'GA_Hybrid.local.csv','text/csv;charset=utf-8')),button('Hibrit XLSX',()=>downloadComparisonWorkbook([{name:'Hybrid',rows:hybridRows()}])),summary,catalog,cases,button('Vakalar önceki',()=>{casePage=Math.max(0,casePage-1);render();}),button('Vakalar sonraki',()=>{casePage++;render();}));
  const scScope=createStudyScope('SC');scScope.endpoints.hidden=true;
  const scMode=element('select');scMode.setAttribute('aria-label','SC hesap modu');for(const value of ['MAX','MIN']){const o=element('option','',value);o.value=value;scMode.append(o);}
  const approximation=element('input'),approxLabel=element('label','ga-field','Native + açık kaynak varsayımları (NETWORK_APPROXIMATION)');approximation.type='checkbox';approximation.setAttribute('aria-label','SC açık NETWORK_APPROXIMATION');approxLabel.append(approximation);
  const missingMachine=element('input'),missingLabel=element('label','ga-field','Yalnız eksik makine R/X için aşağıdaki pu varsayımını kullan');missingMachine.type='checkbox';missingMachine.setAttribute('aria-label','Eksik makine pu varsayımını onayla');missingLabel.append(missingMachine);
  const mixed=element('input'),mixedLabel=element('label','ga-field','Kapalı anahtarda farklı nominal kV: canonical baz normalizasyonunu onayla');mixed.type='checkbox';mixed.setAttribute('aria-label','SC nominal baz normalizasyonunu onayla');mixedLabel.append(mixed);
  const sourceC=number('Dış kaynak c_source varsayımı',1.1,.1,2),machineX=number('Eksik makine x double prime pu varsayımı',.2,.001,10),machineR=number('Eksik makine r pu varsayımı',.01,0,10),currentAngle=number('Konverter akım açısı derece varsayımı',-90,-180,180),provenance=element('textarea'),overrides=element('textarea'),faultSearch=element('input'),faultInfo=element('p');provenance.setAttribute('aria-label','SC varsayım kaynağı');provenance.value='Kullanıcı NETWORK_APPROXIMATION: konverter akımı bağlı terminal bazında; KG/KT/KKW doğrulanmadı';overrides.setAttribute('aria-label','SC kaynak R X ohm JSON override');overrides.placeholder='[{"sourceClass":"ElmSym","fid":"...","rOhm":1,"xOhm":10,"provenance":"kaynak/varsayım"}]';faultSearch.setAttribute('aria-label','SC TM bara terminal ara');faultSearch.placeholder='TM / bara / fiziksel terminal';
  const factor=number('SC c faktörü (açık yaklaşım profili)',1.1,.1,2),faultBudget=number('SC fault bütçesi',10,1,10000),scTime=number('SC zaman sınırı s',120,1,300),terminals=element('textarea'),scSummary=element('p'),scDetails=element('details'),scBody=element('div');terminals.rows=3;terminals.setAttribute('aria-label','SC fiziksel terminal FID seçimi');terminals.style.width='100%';
  let faultCache:{network:typeof ctx.network;key:string;ids:string[]}|undefined;
  const faultList=()=>{const scope={...scScope.filter(),search:faultSearch.value},key=JSON.stringify(scope);if(faultCache?.network===ctx.network&&faultCache.key===key)return faultCache.ids;const ids=selectFaultTerminals(ctx.network!,scope);faultCache={network:ctx.network,key,ids};return ids;};
  const fillFaults=()=>{if(!ctx.network)return;const eligible=new Set(faultList()),pf=ctx.benchmark?.groups.SC.tables.SC_BusResults_Raw;const refs=pf?pf.rows.map(r=>String(rowObject(pf,r).physicalTerminalFid??'')).filter(fid=>eligible.has(fid)):[];terminals.value=(refs.length?refs:[...eligible]).slice(0,Number(faultBudget.input.value)).join('\n');invalidateSc();render();};
  const scRun=button('GA 3PH MAX hesap',()=>{try{
    const eligible=new Set(faultList()),ids=terminals.value.split(/[\s,;]+/).filter(Boolean);if(ids.some(id=>!eligible.has(id)))throw Error('SC seçimi YTM/gerilim/arama kapsamı dışında');
    const opts:import('../../analysis/short-circuit/source-adapter').ScAdapterOptions=approximation.checked?{externalGridFactor:{value:Number(sourceC.input.value),provenance:provenance.value},converterAngleDeg:Number(currentAngle.input.value),converterTerminalBasis:true,allowMixedNominalKv:mixed.checked,provenance:provenance.value,missingMachineXdssPu:missingMachine.checked?Number(machineX.input.value):undefined,missingMachineRPu:missingMachine.checked?Number(machineR.input.value):undefined,overrides:overrides.value.trim()?JSON.parse(overrides.value):undefined}:{};
    if(approximation.checked&&!provenance.value.trim())throw Error('SC varsayım kaynağı zorunlu');
    void ctx.runSc(ids.length?ids:[...eligible].slice(0,Number(faultBudget.input.value)),{faultType:'3PH',calculateMode:scMode.value as 'MAX'|'MIN',voltageFactor:Number(factor.input.value),factorProvenance:'EXPLICIT_USER_NETWORK_APPROXIMATION_PROFILE; NOT_VERIFIED_IEC',edition:null,rfOhm:0,xfOhm:0,maxFaults:Number(faultBudget.input.value),timeBudgetMs:Number(scTime.input.value)*1000},opts);
  }catch(e){ctx.setMessage(String(e));}});

  const faultYtm=(fid:string)=>{const bus=ctx.network?.buses.find(b=>b.sourceId===fid);return [...new Set(bus?.siteIds.map(id=>ctx.network?.sites.find(s=>s.id===id)?.areaId).filter(Boolean)??[])].join(';');};
  const scRows=()=>[['physicalTerminalFID','electricalBusId','YTM_native_IDs','nominalKv','status','reason','ZkkRohm','ZkkXohm','Ikss_kA','Skss_MVA','Ip_kA','Ib_kA','Ith_kA','residual','modelHash','scenarioHash','profileHash','method','edition','faultType','scope','factorProvenance'],...(ctx.scResult?.faults??[]).map(f=>[f.physicalTerminalFid,f.electricalBusId,faultYtm(f.physicalTerminalFid),f.nominalKv,f.status,f.reasons.join(';'),f.zkkOhm?.re??null,f.zkkOhm?.im??null,f.ikssKa,f.skssMva,f.ipKa,f.ibKa,f.ithKa,f.residual,ctx.scResult!.identity.modelHash,ctx.scResult!.identity.scenarioHash,ctx.scResult!.identity.profileHash,ctx.scResult!.method,ctx.scResult!.profile.edition,ctx.scResult!.profile.faultType,'EXPLICIT_SELECTED_PHYSICAL_TERMINALS',ctx.scResult!.profile.factorProvenance])];
  scDetails.append(element('summary','','GA SC kapsam & engeller'),scBody);scDetails.ontoggle=()=>render();
  scPanel.append(element('h3','','GA bağımsız 3PH MAX / MIN'),element('p','ga-muted','CALCULATED_NETWORK_APPROXIMATION: fiziksel kaynak R/X gerekir; IEC edisyonu ve düzeltmeleri doğrulanmış değildir. Ip/Ib/Ith null. 1LG/LL/2LG kapalıdır. Kaynak veya converter katkısı eksikse ilgili fault BLOCKED.'),scScope.element,scMode,faultSearch,faultInfo,button('Fault seçimini kapsamdan doldur',fillFaults),factor.w,faultBudget.w,scTime.w,approxLabel,sourceC.w,currentAngle.w,missingLabel,machineX.w,machineR.w,mixedLabel,provenance,overrides,terminals,scRun,button('SC durdur',()=>ctx.cancel()),button('SC JSON',()=>downloadText(JSON.stringify(ctx.scResult,null,2),'GA_SC.local.json','application/json')),button('SC CSV',()=>downloadText(csvDocument(scRows()),'GA_SC.local.csv','text/csv;charset=utf-8')),button('SC XLSX',()=>downloadComparisonWorkbook([{name:'SC',rows:scRows()}])),button('SC alan audit JSON',()=>downloadText(JSON.stringify(ctx.scContext?.audit??[],null,2),'GA_SC_Field_Audit.local.json','application/json')),scSummary,scDetails);
  let network=ctx.network,loaded=false,limitsFromManifest=false;
  const invalidateHybrid=()=>{if(ctx.busy)ctx.cancel();ctx.hybridResult=null;ctx.notify();};
  for(const i of [threshold.input,loading.input,vmin.input,vmax.input,scope,scopeControls.voltage,scopeControls.endpoints,season,studyProfile,allAc,clearSample.input,...riskInputs.values()])i.onchange=()=>{catalogPage=0;selectedIds.clear();invalidateHybrid();};
  for(const i of [budget.input,perCase.input,global.input])i.onchange=()=>{if(ctx.busy)ctx.cancel();ctx.notify();};
  const invalidateSc=()=>{if(ctx.busy)ctx.cancel();ctx.scResult=null;if(ctx.benchmarkMap?.analysis==='SC')ctx.benchmarkMap=null;ctx.notify();};
  for(const i of [factor.input,faultBudget.input,scTime.input,terminals,scMode,approximation,missingMachine,mixed,sourceC.input,machineX.input,machineR.input,currentAngle.input,provenance,overrides])i.onchange=invalidateSc;
  const modeProfiles=approximationModeProfiles();let lastMode:'MAX'|'MIN'='MAX';
  scMode.onchange=()=>{modeProfiles[lastMode]={faultFactor:Number(factor.input.value),sourceFactor:Number(sourceC.input.value)};lastMode=scMode.value as 'MAX'|'MIN';factor.input.value=String(modeProfiles[lastMode].faultFactor);sourceC.input.value=String(modeProfiles[lastMode].sourceFactor);invalidateSc();};
  for(const i of [scScope.areas,scScope.voltage,faultSearch])i.onchange=fillFaults;
  function render(){
    if(network!==ctx.network||!loaded&&ctx.network){network=ctx.network;loaded=true;scopeControls.populate(network);scScope.populate(network);selectedIds.clear();catalogPage=casePage=0;
      const t=ctx.benchmark?.groups.N1.tables.N1_RunManifest_Raw,r=t?.rows[0]?rowObject(t,t.rows[0]):null;limitsFromManifest=!!r&&r.loadingLimitPercent===100&&r.minVoltagePu===.9&&r.maxVoltagePu===1.1;
      if(limitsFromManifest){loading.input.value='100';vmin.input.value='.9';vmax.input.value='1.1';}
      const sc=ctx.benchmark?.groups.SC.tables.SC_BusResults_Raw;terminals.value=sc?sc.rows.slice(0,10).map(r=>String(rowObject(sc,r).physicalTerminalFid??'')).filter(Boolean).join('\n'):ctx.network?.buses.filter(b=>b.inService).slice(0,10).map(b=>b.sourceId).join('\n')??'';
    }
    hybridPanel.hidden=analysis()!=='N1';scPanel.hidden=analysis()!=='SC';run.disabled=ctx.busy||!ctx.network;resume.disabled=ctx.busy||!ctx.hybridResult||!ctx.network||!hybridIsCurrent(ctx.hybridResult,ctx.network,ctx.scenario.current,ctx.analysisSettings.value);stop.disabled=!ctx.busy;
    const settings=hybridStudySettings(ctx.analysisSettings.value,studyProfile.value as HybridStudyProfile);controlInfo.textContent=`stationControlMode=${settings.powerFlow.stationControlMode} · activeBalancing=${settings.powerFlow.activeBalancingMode} · ${ctx.hybridResult?.base?.fidelity??'CONTROL_SUPPORT_REQUIRES_VERIFICATION'} · support=${JSON.stringify(ctx.hybridResult?.base?.controlSupport??{})}`;
    summary.textContent=ctx.hybridResult?`${ctx.hybridResult.phase} · ${ctx.hybridResult.status} · ${JSON.stringify(ctx.hybridResult.counts)} · ${ctx.hybridResult.reason}`:'Hibrit hesap bekleniyor';
    const filtered=candidates();catalogInfo.textContent=`Tam katalog ${ctx.n1CatalogIdentity?.includeAllVoltages?ctx.n1CatalogResult?.counts.total??0:'hazırlanmadı'} · kapsam ${filtered.length} · açık seçim ${selectedIds.size} · sayfa ${catalogPage+1}`;
    catalogBody.replaceChildren();if(catalog.open){catalogPage=Math.min(catalogPage,Math.max(0,Math.ceil(filtered.length/50)-1));for(const c of filtered.slice(catalogPage*50,(catalogPage+1)*50)){const row=element('label','ga-field',`${c.candidateId} · ${c.name} · ${c.vnKv} kV · ${c.fromYtmIds.join('/')} → ${c.toYtmIds.join('/')} · ${c.topology} · ${c.screenable?'DC':'doğrudan AC'}`),check=element('input');check.type='checkbox';check.checked=selectedIds.has(c.candidateId);check.onchange=()=>{if(check.checked)selectedIds.add(c.candidateId);else selectedIds.delete(c.candidateId);invalidateHybrid();};row.append(check);catalogBody.append(row);}}
    caseBody.replaceChildren();if(cases.open){const rows=ctx.hybridResult?.cases??[];casePage=Math.min(casePage,Math.max(0,Math.ceil(rows.length/50)-1));for(const c of rows.slice(casePage*50,(casePage+1)*50)){const p=element('p','',`${c.outage.caseId} · ${c.metadata?.voltageKv??'—'} kV · ${c.status} · DC ${c.dcStatus} · iter ${c.iterations??'—'} / residual ${format(c.maxMismatchMw)} MW · beslenemeyen yük ${format(c.unsuppliedLoadMw)} MW · V ${format(c.minVpu)}–${format(c.maxVpu)} · ${JSON.stringify(c.constraintCounts??{})} · ${c.reason}`);p.append(button('Vaka haritası',()=>void ctx.loadHybridCaseDetail(c.outage.caseId).then(ok=>{if(ok){ctx.benchmarkMap={analysis:'N1',source:'GA',metric:'postVoltagePu',table:'N1_RecordedExtrema_Raw',caseId:c.outage.caseId,n1Layer:'POST'};ctx.setView('map');}})),button('Vaka sonuçlarını göster',()=>void ctx.loadHybridCaseDetail(c.outage.caseId).then(ok=>{if(ok){detailCase=c.outage.caseId;render();}})));caseBody.append(p);}
      const chosen=rows.find(c=>c.outage.caseId===detailCase);if(chosen){caseBody.append(element('h4','',detailCase+' · en fazla 50 kritik kısıt'));for(const k of (chosen.constraintChanges??[]).slice(0,50))caseBody.append(element('p','',`${k.sourceClass}:${k.fid} · ${k.state} / ${k.metric} BASE ${format(k.base)} / POST ${format(k.post)} / CHANGE ${format(k.delta)} / limit ${k.limit} / ${k.loading?.basis??'BUS'}`));caseBody.append(button('Vaka tam JSON',()=>downloadText(JSON.stringify(chosen,null,2),'GA_N1_Case.local.json','application/json')),button('Vaka bara CSV',()=>downloadText(csvDocument([['physicalTerminals','vnKv','voltagePu','angleDeg'],...(chosen.mapResults?.buses??[]).map(b=>[b.terms.join(';'),b.vnKv,b.vmPu,b.angleDeg])]),'GA_N1_Buses.local.csv','text/csv;charset=utf-8')),button('Vaka uç P Q S I CSV',()=>downloadText(csvDocument([['class','FID','Pfrom_MW','Qfrom_Mvar','Sfrom_MVA','Pto_MW','Qto_Mvar','Sto_MVA','Ifrom_A','Ito_A','currentLoadingPercent','apparentLoadingPercent','operationalLoadingPercent','season','basis'],...(chosen.mapResults?.branches??[]).map(b=>[b.sourceClass,b.fid,b.pf,b.qf,Math.hypot(b.pf,b.qf),b.pt,b.qt,Math.hypot(b.pt,b.qt),b.ifA,b.itA,b.loading.currentPercent,b.loading.apparentPercent,b.loading.operationalPercent,b.loading.season,b.loading.basis])]),'GA_N1_Branches.local.csv','text/csv;charset=utf-8')),button('Vaka P Q S I V XLSX',()=>{const post=chosen.mapResults;downloadComparisonWorkbook([{name:'Buses',rows:[['physicalTerminals','vnKv','voltagePu','angleDeg'],...(post?.buses??[]).map(b=>[b.terms.join(';'),b.vnKv,b.vmPu,b.angleDeg])]},{name:'Branches',rows:[['class','FID','Pfrom_MW','Qfrom_Mvar','Sfrom_MVA','Pto_MW','Qto_Mvar','Sto_MVA','Ifrom_A','Ito_A','currentLoadingPercent','apparentLoadingPercent','operationalLoadingPercent','season','basis'],...(post?.branches??[]).map(b=>[b.sourceClass,b.fid,b.pf,b.qf,Math.hypot(b.pf,b.qf),b.pt,b.qt,Math.hypot(b.pt,b.qt),b.ifA,b.itA,b.loading.currentPercent,b.loading.apparentPercent,b.loading.operationalPercent,b.loading.season,b.loading.basis])]}]);}));}}
    faultInfo.textContent=ctx.network?`YTM/gerilim/arama kapsamı: ${faultList().length} fiziksel terminal · elektriksel kaynaklar ve bağlı ağ korunur`:'Model bekleniyor';scRun.textContent=`GA 3PH ${scMode.value} hesap`;scRun.setAttribute('aria-label',scRun.textContent);
    scRun.disabled=ctx.busy||!ctx.scContext;scRun.title=ctx.scContext?'Kaynak modeli olmayan faultlar nedenleriyle reddedilir':'MODEL_SOURCE_CONTEXT_MISSING';
    const current=ctx.scResult&&ctx.network&&ctx.scResult.identity.modelHash===ctx.network.modelHash&&ctx.scResult.identity.scenarioHash===scenarioSignature(ctx.scenario.current);
    scSummary.textContent=current?`${scMode.value}: c_fault=${factor.input.value}, c_source=${sourceC.input.value} EXPLICIT_APPROXIMATION / ${JSON.stringify(ctx.scResult!.sourceCounts??{})} / ${JSON.stringify(ctx.scResult!.counts)} · ${ctx.scResult!.factorizations} sparse faktorizasyon · ${ctx.scResult!.rhsCount} RHS · IEC parity: BLOCKED`:'GA SC hesap bekleniyor';
    scBody.replaceChildren();if(scDetails.open)for(const f of current?ctx.scResult!.faults.slice(0,30):[])scBody.append(element('p','',`${f.physicalTerminalFid} → ${f.electricalBusId??'—'} · ${f.status} · Ikss ${format(f.ikssKa)} kA · Skss ${format(f.skssMva)} MVA · ${f.reasons.slice(0,3).join('; ')}${f.reasons.length>3?' … '+f.reasons.length+' kaynak engeli':''}`));
  }
  render();return {element:root,render};
}
