import type { AppContext,Feature } from '../../app/contracts';
import { element,button,format,downloadText,csvDocument } from '../../ui/components/dom';
import { preflightBenchmark,metricRows,metricStatistics,METRICS,type BenchmarkMetricRow,type BenchmarkPreflight } from '../../domain/benchmark/comparison';
import { rowObject,type BenchmarkAnalysis,type RawTable } from '../../domain/benchmark/types';
import { metricExportRows,rawExportRows,rawExportJson } from './export';
import { downloadComparisonWorkbook } from '../analysis/comparison-export';
import type { AcOutage } from '../../analysis/contingency-ac';
import { scenarioSignature } from '../../domain/scenario/overlay';
import { stableJson } from '../../domain/calculation/identity';

export function createBenchmarkComparisonView(ctx:AppContext):Feature{
  const root=element('section','ga-panel ga-benchmark'),title=element('h2','','KARŞILAŞTIRMA'),inputs=element('div','ga-toolbar'),model=element('input'),benchmark=element('input'),notice=element('p','ga-notice'),tabs=element('nav','ga-toolbar'),controls=element('div','ga-toolbar'),tableSelect=element('select'),metric=element('select'),search=element('input'),ytm=element('input'),tm=element('input'),kv=element('input'),status=element('select'),order=element('select'),summary=element('p','ga-muted'),coverage=element('div','ga-benchmark-coverage'),container=element('div','ga-table-wrap'),paging=element('div','ga-toolbar'),selection=element('div','ga-notice'),readiness=element('details');
  model.type=benchmark.type='file';model.accept=benchmark.accept='.zip';model.setAttribute('aria-label','Model ZIP');benchmark.setAttribute('aria-label','Benchmark ZIP');
  for(const [label,input] of [['Model ZIP',model],['Benchmark ZIP',benchmark]] as const){const wrapper=element('label','ga-field',label);wrapper.append(input);inputs.append(wrapper);}
  const load=button('İki ZIP’i aç',()=>{if(model.files?.[0]&&benchmark.files?.[0])void ctx.loadBenchmarkPair(model.files[0],benchmark.files[0]);}),cancel=button('İptal',()=>ctx.cancel()),solve=button('GA Tam AC baz hesabı',()=>void ctx.run('powerFlow','base'));inputs.append(load,cancel,solve);
  let analysis:BenchmarkAnalysis='LF',page=0,selected:AcOutage|null=null;const metricChoices=new Map<string,string>();
  const tabButtons=new Map<BenchmarkAnalysis,HTMLButtonElement>();
  for(const [a,label] of [['LF','Yük Akışı'],['N1','N-1'],['SC','Kısa Devre']] as const){const b=button(label,()=>{analysis=a;tableSelect.value='';metric.value='';page=0;selected=null;render();});tabButtons.set(a,b);tabs.append(b);}
  tableSelect.setAttribute('aria-label','PF Raw tablo');metric.setAttribute('aria-label','Karşılaştırma metriği');search.type=ytm.type=tm.type='search';search.placeholder='FID / ad / vaka';ytm.placeholder='YTM';tm.placeholder='TM';kv.type='number';kv.placeholder='Nominal kV';
  search.setAttribute('aria-label','FID ad vaka ara');ytm.setAttribute('aria-label','YTM filtrele');tm.setAttribute('aria-label','TM filtrele');kv.setAttribute('aria-label','Nominal gerilim filtrele');
  status.setAttribute('aria-label','Veri durumu');for(const s of ['','COMPARABLE_PARTIAL','NOT_COMPARABLE','NOT_RECORDED','PF_REFERENCE_ONLY','RECORDED_NUMERIC_ZERO','CAPABILITY_UNVERIFIED']){const option=element('option','',s||'Tüm durumlar');option.value=s;status.append(option);}
  order.setAttribute('aria-label','Sıralama');for(const [value,label] of [['source','Kaynak sırası'],['fid','FID'],['name','Ad'],['pf','PF büyükten küçüğe'],['delta','|Fark| büyükten küçüğe']]){const o=element('option','',label);o.value=value;order.append(o);}
  controls.append(tableSelect,metric,search,ytm,tm,kv,status,order);
  const exportRows=()=>activeRows(),exportButtons=[button('CSV',()=>downloadText(csvDocument(metric.value?metricExportRows(exportRows()):rawExportRows(filteredRawTable())),'PF_Benchmark.csv','text/csv;charset=utf-8')),button('XLSX',()=>downloadComparisonWorkbook([{name:'Benchmark',rows:metric.value?metricExportRows(exportRows()):rawExportRows(filteredRawTable())}])),button('JSON',()=>downloadText(metric.value?JSON.stringify({identity:ctx.benchmark?.groups[analysis].identity,gate,rows:exportRows()},null,2):rawExportJson(filteredRawTable()),'PF_Benchmark.json','application/json'))];controls.append(...exportButtons);
  const pageLabel=element('span'),previous=button('Önceki',()=>{page--;draw();}),next=button('Sonraki',()=>{page++;draw();});paging.append(previous,pageLabel,next);
  const readinessTitle=element('summary','','GA IEC 60909 kaynak hazırlığı'),readinessText=element('p'),readinessTable=element('div');readiness.append(readinessTitle,readinessText,readinessTable,button('Readiness JSON',()=>downloadText(JSON.stringify(ctx.benchmarkReadiness,null,2),'GA_SC_Readiness.local.json','application/json')),button('Readiness CSV',()=>{const rows=ctx.benchmarkReadiness?.rows||[];downloadText(csvDocument([['sourceClass','FID','status','reason','missingFields','subset','inService'],...rows.map(r=>[r.sourceClass,r.fid,r.status,r.reasons.join(';'),r.missingFields.join(';'),r.subset,r.inService])]),'GA_SC_Readiness.local.csv','text/csv;charset=utf-8');}));
  root.append(title,element('p','ga-muted','Model ZIP ve dokuz PF çıktısını içeren benchmark ZIP seçin. Referanslar bu oturumda bellekte tutulur.'),inputs,notice,tabs,controls,summary,coverage,selection,container,paging,readiness);
  let cachedPackage=ctx.benchmark,cachedNetwork=ctx.network,cachedResult=ctx.resultStore.get('base','powerFlow'),gate:BenchmarkPreflight={status:'NOT_COMPARABLE',reasons:['BENCHMARK_NOT_LOADED'],lf:null,comparison:null},currentTable:RawTable|null=null,rows:BenchmarkMetricRow[]=[],rowsKey='';
  function refreshGate(){const b=ctx.benchmark,n=ctx.network,r=ctx.resultStore.get('base','powerFlow');if(b!==cachedPackage||n!==cachedNetwork||r!==cachedResult||b&&!gate.lf){cachedPackage=b;cachedNetwork=n;cachedResult=r;gate=b?preflightBenchmark(b,n,r,ctx.powerFactoryControlContextNumericFile):{status:'NOT_COMPARABLE',reasons:['BENCHMARK_NOT_LOADED'],lf:null,comparison:null};rowsKey='';}}
  function activeRows(){const q=search.value.toLocaleLowerCase('tr-TR'),y=ytm.value.toLocaleLowerCase('tr-TR'),t=tm.value.toLocaleLowerCase('tr-TR');const out=rows.filter(r=>(!q||`${r.fid} ${r.name} ${r.caseId}`.toLocaleLowerCase('tr-TR').includes(q))&&(!y||r.ytm.toLocaleLowerCase('tr-TR').includes(y))&&(!t||r.tm.toLocaleLowerCase('tr-TR').includes(t))&&(!kv.value||r.nominalKv===Number(kv.value))&&(!status.value||r.status===status.value||r.pf.availability===status.value));
    if(order.value==='fid'||order.value==='name')out.sort((a,b)=>a[order.value as 'fid'|'name'].localeCompare(b[order.value as 'fid'|'name'],'tr'));else if(order.value==='pf'||order.value==='delta')out.sort((a,b)=>order.value==='pf'?(b.pf.value??-Infinity)-(a.pf.value??-Infinity):(b.absoluteDelta??-Infinity)-(a.absoluteDelta??-Infinity));return out;}
  function choose(row:Record<string,string|number|null>){
    const sourceClass=String(row.outageClass??''),fid=String(row.outageFid??'');selected=sourceClass==='ElmLne'||sourceClass==='ElmTr2'?{sourceClass,fid,caseId:String(row.caseId??'')}:null;renderSelection();
  }
  function filteredRawRows(){
    if(!currentTable)return [];
    const q=search.value.toLocaleLowerCase('tr-TR'),y=ytm.value.toLocaleLowerCase('tr-TR'),t=tm.value.toLocaleLowerCase('tr-TR');
    const out=currentTable.rows.map((row,index)=>({row,index,object:rowObject(currentTable!,row)})).filter(({row,object:r})=>(!q||row.some(v=>String(v??'').toLocaleLowerCase('tr-TR').includes(q)))&&(!y||String(r.ytmName??r.outageYtm??'').toLocaleLowerCase('tr-TR').includes(y))&&(!t||String(r.substationName??r.siteName??r.outageSubstation??'').toLocaleLowerCase('tr-TR').includes(t))&&(!kv.value||Number(r.nominalKv??r.voltageLevelKv??r.outageVoltageKv)===Number(kv.value))&&(!status.value||row.some(v=>v===status.value)));
    if(order.value==='fid'||order.value==='name'){const field=order.value;out.sort((a,b)=>String(a.object[field]??a.object[field==='fid'?'outageFid':'outageName']??'').localeCompare(String(b.object[field]??b.object[field==='fid'?'outageFid':'outageName']??''),'tr'));}return out;
  }
  function filteredRawTable():RawTable{const selected=filteredRawRows();return {...currentTable!,rows:selected.map(r=>r.row),rowNumbers:selected.map(r=>currentTable!.rowNumbers[r.index])};}
  function renderSelection(){selection.replaceChildren();selection.hidden=analysis!=='N1';if(analysis!=='N1')return;
    selection.append(element('p','','PF vaka sonuçları ve ada durumu doğrulanmamıştır. PF kayıtlı ekstremum, GA DC screening ve GA AC doğrulama ayrı yöntemlerdir. PF post-P/Q/S/V eksik olduğunda fark hesaplanmaz.'));
    if(!selected){selection.append(element('p','','Kesinti seçmek için N1_Cases_Raw satırına tıklayın.'));return;}
    const s=selected;selection.append(element('strong','',`${s.caseId} · ${s.sourceClass}:${s.fid}`));
    const dc=button('Seçili vaka: GA DC screening',()=>void ctx.runN1Screen({candidateTypes:[s.sourceClass],selectedCandidateIds:[`${s.sourceClass}:${s.fid}`],analysisScope:'scenario'})),ac=button('Seçili vaka: GA Full AC doğrula',()=>void ctx.runN1AcValidation([s]));dc.disabled=ac.disabled=ctx.busy;selection.append(dc,ac);
    const screen=ctx.n1Result?.candidates.find(c=>c.equipmentId===s.fid&&c.sourceClass===s.sourceClass);if(screen)selection.append(element('p','',`GA_DC_SCREEN · ${screen.status} · ${screen.topImpacts.length} etkilenen dal`));
    function detailTable(label:string,headers:string[],data:(string|number|null)[][]){const details=element('details'),heading=element('summary','',label),wrap=element('div','ga-table-wrap'),table=element('table','ga-table'),head=element('tr');for(const h of headers)head.append(element('th','',h));table.append(head);for(const row of data.slice(0,50)){const tr=element('tr');for(const v of row)tr.append(element('td','',typeof v==='number'?format(v):v??'—'));table.append(tr);}wrap.append(table);details.append(heading,element('p','ga-muted',`${data.length} kayıt · ilk 50 kayıt; tamamı export içinde`),wrap,button(`${label} CSV`,()=>downloadText(csvDocument([headers,...data]),'GA_N1.local.csv','text/csv;charset=utf-8')),button(`${label} XLSX`,()=>downloadComparisonWorkbook([{name:'GA_N1',rows:[headers,...data]}])));selection.append(details);}
    if(screen)detailTable('GA DC screening dalları',['Sınıf','FID','Baz P MW','Post P MW','ΔP MW','Post tahmini yük %','Metot'],screen.topImpacts.map(r=>[r.sourceClass,r.equipmentId,r.baseFlowMw,r.postFlowMw,r.deltaPMw,r.postEstimatedLoadingPct,'GA_DC_SCREEN']));
    const validated=ctx.n1AcResults.find(r=>r.outage.caseId===s.caseId&&r.identity.baseScenarioHash===scenarioSignature(ctx.scenario.current)&&r.identity.settingsHash===stableJson(ctx.analysisSettings.value));if(validated){selection.append(element('p','',`GA_AC_POST_CONTINGENCY · ${validated.status} · ${validated.reason} · ${validated.result?.buses.length??0} bara`));if(validated.result){selection.append(button('GA AC sonuç JSON',()=>downloadText(JSON.stringify(validated,null,2),'GA_N1_AC.local.json','application/json')));detailTable('GA AC baralar',['FID','Ad','Vpu','kV','θ deg','Ada'],validated.result.buses.map(b=>[b.id,b.name,b.vmPu,b.vmPu*b.vnKv,b.angleRad*180/Math.PI,b.islandId??null]));detailTable('GA AC dallar',['Sınıf','FID','P from MW','Q from Mvar','S from MVA','P to MW','Q to Mvar','S to MVA','Yük %'],validated.result.branches.map(b=>[b.sourceClass,b.id,b.pf,b.qf,Math.hypot(b.pf,b.qf),b.pt,b.qt,Math.hypot(b.pt,b.qt),b.loading]));}}
  }
  function draw(){
    for(const option of order.options)option.disabled=!metric.value&&['pf','delta'].includes(option.value);if(!metric.value&&['pf','delta'].includes(order.value))order.value='source';
    const filtered=metric.value?activeRows():filteredRawRows(),total=filtered.length;page=Math.max(0,Math.min(page,Math.max(0,Math.ceil(total/50)-1)));const visible=filtered.slice(page*50,page*50+50),table=element('table','ga-table'),head=element('thead'),headRow=element('tr'),body=element('tbody');
    const headers=metric.value?['Sınıf / FID','Ad / vaka','Metrik','PF','GA','Δ GA−PF','|Δ|','Δ%','Birim','Durum / yöntem','Kaynak']:currentTable?.headers||[];
    for(const h of headers)headRow.append(element('th','',h));head.append(headRow);table.append(head,body);
    for(const item of visible){const tr=element('tr');
      if(metric.value){const r=item as BenchmarkMetricRow,values=[`${r.sourceClass}:${r.fid}`,`${r.name} ${r.caseId}`,r.metric,format(r.pf.value),format(r.ga),format(r.delta),format(r.absoluteDelta),format(r.deltaPercent),r.pf.unit,`${r.status} · ${r.pf.availability} · ${r.method}`,`${r.pf.source.sheet}!${r.pf.source.column}${r.pf.source.row}`];for(const text of values)tr.append(element('td','',text));tr.title=r.reason+'\n'+r.pf.qualityFlags.join(';');}
      else{const {row,index}=item as {row:(string|number|null)[];index:number};for(const v of row)tr.append(element('td','',v==null?'—':typeof v==='number'?format(v):v));tr.title=`${currentTable!.name} · satır ${currentTable!.rowNumbers[index]}`;if(analysis==='N1'&&currentTable!.headers.includes('outageFid')){tr.tabIndex=0;tr.onclick=()=>choose(rowObject(currentTable!,row));tr.onkeydown=e=>{if(e.key==='Enter'||e.key===' ')choose(rowObject(currentTable!,row));};}}
      for(const cell of tr.cells)cell.title=cell.textContent||'';body.append(tr);
    }
    container.replaceChildren(table);pageLabel.textContent=`${total.toLocaleString('tr-TR')} kayıt · ${page+1}/${Math.max(1,Math.ceil(total/50))} sayfa`;previous.disabled=page===0;next.disabled=(page+1)*50>=total;
    const stats=metric.value?metricStatistics(filtered as BenchmarkMetricRow[]):[];coverage.replaceChildren();for(const s of stats){const block=element('div','',`${s.metric}: ${s.matched}/${s.sourceCount} karşılaştırılabilir · PF eksik ${s.missingPF} · GA eksik ${s.missingGA} · metot dışı ${s.excludedMethod} · rating dışı ${s.excludedRating} · MAE ${format(s.mae)} · P95 ${format(s.p95)} · maks |Δ| ${format(s.maxAbsDelta)} ${s.unit}`);const meter=element('meter');meter.min=0;meter.max=Math.max(1,s.sourceCount);meter.value=s.matched;meter.setAttribute('aria-label',`${s.metric} karşılaştırılabilir kapsam`);block.append(meter);coverage.append(block);}
    const critical=metric.value?(filtered as BenchmarkMetricRow[]).filter(r=>r.absoluteDelta!==null).sort((a,b)=>b.absoluteDelta!-a.absoluteDelta!).slice(0,10):[];
    if(critical.length){const chart=element('details'),heading=element('summary','','En büyük 10 mutlak fark');chart.append(heading);const max=critical[0].absoluteDelta!;for(const r of critical){const line=element('div','',`${r.sourceClass}:${r.fid} · ${format(r.absoluteDelta)} ${r.pf.unit}`),bar=element('meter');bar.min=0;bar.max=max||1;bar.value=r.absoluteDelta!;line.append(bar);chart.append(line);}coverage.append(chart);}
  }
  function render(){
    load.disabled=ctx.busy||!model.files?.length||!benchmark.files?.length;cancel.disabled=!ctx.busy;solve.disabled=ctx.busy||!ctx.network;for(const[a,b]of tabButtons)b.setAttribute('aria-pressed',String(a===analysis));refreshGate();
    const group=ctx.benchmark?.groups[analysis],visibleStatus=analysis==='LF'?gate.status:analysis==='SC'?'PF_REFERENCE_ONLY':'NOT_COMPARABLE_PF_MISSING',visibleReasons=analysis==='LF'?gate.reasons:[];notice.textContent=group?`${group.identity.studyCase} · ${group.identity.studyTime} Europe/Istanbul · PF ${group.identity.pfVersion} · exporter ${group.identity.addonVersion??'kaydedilmedi'} · ${group.identity.effectiveMethod} · ${group.identity.methodVerificationStatus} · ${visibleStatus}${visibleReasons.length?' · '+visibleReasons.join('; '):''}`:'İki ZIP seçilmesini bekliyor.';
    const names=group?Object.keys(group.tables):[],oldTable=tableSelect.value;tableSelect.replaceChildren();for(const name of names){const o=element('option','',`${name} (${group!.tables[name].rows.length.toLocaleString('tr-TR')})`);o.value=name;tableSelect.append(o);}tableSelect.value=names.includes(oldTable)?oldTable:({LF:'GA_Reference_Raw',N1:'N1_Cases_Raw',SC:'SC_BusResults_Raw'})[analysis];
    currentTable=group?.tables[tableSelect.value]||null;const fields=Object.keys(METRICS[tableSelect.value]||{}),oldMetric=metric.value;metric.replaceChildren();const rawOption=element('option','','Ham tablo / tüm kolonlar');rawOption.value='';metric.append(rawOption);for(const field of fields){const o=element('option','',`${field} (${METRICS[tableSelect.value][field]})`);o.value=field;metric.append(o);}metric.value=fields.includes(oldMetric)?oldMetric:analysis==='N1'?'':fields[0]||'';
    const choiceKey=`${analysis}|${tableSelect.value}`;metric.value=metricChoices.has(choiceKey)?metricChoices.get(choiceKey)!:analysis==='N1'?'':fields[0]||'';
    const key=`${analysis}|${tableSelect.value}|${metric.value}`;if(key!==rowsKey){rows=currentTable&&metric.value?metricRows(currentTable,gate,metric.value):[];rowsKey=key;}
    summary.textContent=analysis==='SC'?'PF_REFERENCE_ONLY · Fiziksel bara, elektriksel bara ve cihaz kayıtları ayrıdır. Fault×device katkı tablolarının eksikliği sıfır katkı anlamına gelmez.':analysis==='N1'?'PF_RECORDED_EXTREMA · CaseStatus CAPABILITY_UNVERIFIED; ayrıntılı PF post-case verisi olmadan sayısal AC paritesi yok.':'Kaynak FID/topoloji, metot ve rating doğrulanmadan fark üretilmez. Açı, doğrulanmış ada referansıyla hizalanır.';
    renderSelection();readiness.hidden=analysis!=='SC';readinessText.textContent=ctx.benchmarkReadiness?`NOT_COMPUTABLE · IEC edisyonu ${ctx.benchmarkReadiness.edition??'doğrulanmadı'} · ${JSON.stringify(ctx.benchmarkReadiness.counts)} · ${ctx.benchmarkReadiness.reasons.join('; ')}`:'Kaynak audit bekleniyor';readinessTable.replaceChildren();if(readiness.open){for(const r of ctx.benchmarkReadiness?.rows.slice(0,50)||[])readinessTable.append(element('p','',`${r.sourceClass}:${r.fid} · ${r.status} · ${r.reasons.join('; ')}`));}
    for(const b of exportButtons)b.disabled=!currentTable;draw();
  }
  model.onchange=benchmark.onchange=()=>render();tableSelect.onchange=()=>{metric.value='';rowsKey='';page=0;render();};metric.onchange=()=>{rowsKey='';page=0;const chosen=metric.value;metricChoices.set(`${analysis}|${tableSelect.value}`,chosen);rows=currentTable&&chosen?metricRows(currentTable,gate,chosen):[];rowsKey=`${analysis}|${tableSelect.value}|${chosen}`;draw();};for(const input of [search,ytm,tm,kv,status,order])input.oninput=()=>{page=0;draw();};readiness.ontoggle=()=>render();
  render();return {element:root,render};
}
