import type {AppContext} from '../../app/contracts';
import {element,button,format,downloadText,csvDocument} from '../../ui/components/dom';
import {buildScorecard,compareScorecardVersions,TOLERANCE_VERSION,type ScorecardEvidence} from '../../domain/benchmark/scorecard';
import {metricRows,preflightBenchmark} from '../../domain/benchmark/comparison';
import {hasReference} from '../../domain/benchmark/reference-slots';
import {stableJson} from '../../domain/calculation/identity';
import {emptyScenario} from '../../domain/scenario/overlay';
const cache=new WeakMap<AppContext,{key:string;benchmark:unknown;result:unknown;evidence:ScorecardEvidence}>();
export function scorecardEvidence(ctx:AppContext):ScorecardEvidence{const result=ctx.resultStore.get('base','powerFlow'),baseScenario=emptyScenario(),key=stableJson([ctx.network?.modelHash,ctx.analysisSettings.value,baseScenario,ctx.powerFactoryControlContextHash]),old=cache.get(ctx);if(old?.key===key&&old.benchmark===ctx.benchmark&&old.result===result)return old.evidence;
  const b=ctx.benchmark,gate=b?preflightBenchmark(b,ctx.network,result,ctx.powerFactoryControlContextNumericFile):null,rows=[];
  if(b&&gate)for(const a of ['LF','N1','SC'] as const){if(!hasReference(b,a))continue;const table=b.groups[a].tables[a==='LF'?'GA_Reference_Raw':a==='N1'?'N1_RecordedExtrema_Raw':'SC_BusResults_Raw'];if(table)for(const row of metricRows(table,gate,undefined,{lfResult:result,diagnostic:true,network:ctx.network,scenario:baseScenario,settings:ctx.analysisSettings.value,benchmark:b}))rows.push(row);}
  const evidence={gitSha:'',modelHash:ctx.network?.modelHash??'',studyCase:ctx.network?.studyCase??'',referenceHash:stableJson(b?.sourceArchives??b?.archiveSha256),settingsHash:stableJson(ctx.analysisSettings.value),controlContextHash:ctx.powerFactoryControlContextHash,toleranceVersion:TOLERANCE_VERSION,rows:buildScorecard(rows,true),createdAt:new Date().toISOString()};cache.set(ctx,{key,benchmark:b,result,evidence});return evidence;
}
export function createScorecardView(ctx:AppContext){const root=element('details','ga-scorecard'),summary=element('summary','','≥66 kV PF–GA doğruluk karnesi'),body=element('div'),sha=element('input'),history=element('input'),trend=element('p');sha.placeholder='Çalışan sürüm Git SHA';sha.setAttribute('aria-label','Karne sürüm Git SHA');history.type='file';history.accept='.json';history.setAttribute('aria-label','Önceki gerçek karne JSON');let previous:ScorecardEvidence|null=null;
  history.onchange=()=>{const file=history.files?.[0];if(file)void file.text().then(text=>{const parsed=JSON.parse(text);if(typeof parsed?.gitSha!=='string'||!Array.isArray(parsed?.rows))throw Error('INVALID_SCORECARD');previous=parsed;render();}).catch(()=>{previous=null;trend.textContent='Geçersiz önceki kayıt';});};
  const current=()=>({...scorecardEvidence(ctx),gitSha:/^[0-9a-f]{40}$/i.test(sha.value.trim())?sha.value.trim():''});
  root.append(summary,element('p','ga-muted','Bu karne B0 sonucu ve B0 PF referansını kullanır; aktif S1/S2 ile GA−PF kıyası değildir. Toleranslar GA-ENGINEERING-1.0 mühendislik değerlendirme profilidir. LF tanısaldır; N-1 PF post-case ve SC IEC/partition kanıtı olmadan oran hesaplanamaz. Boş değerler sıfır sayılmaz.'),body,sha,history,trend,button('Karne JSON',()=>downloadText(JSON.stringify(current(),null,2),'GA_PF_Scorecard.local.json','application/json')),button('Karne CSV',()=>{const rows=scorecardEvidence(ctx).rows;downloadText(csvDocument([['Analiz','kV','Tür','Metrik','Eşleşen','Sayısal PF uygun','PF sayısal dışı','Kapsam %','Tolerans içi %','MAE','P95','Maks','Birim','Tolerans','Metot','Eşleşmeyen nedenleri'],...rows.map(r=>[r.analysis,r.kv,r.kind,r.metric,r.matched,r.eligible,r.excludedPF,r.coverage,r.agreement,r.mae,r.p95,r.maximum,r.unit,r.tolerance,r.method,JSON.stringify(r.reasons)])]),'GA_PF_Scorecard.local.csv','text/csv;charset=utf-8');}),button('Karne yöntemi / yardım',()=>{ctx.helpId='compare.scorecard';ctx.setView('help');}));root.ontoggle=()=>{if(root.open)render();};sha.oninput=()=>render();
  function render(){if(!root.open)return;const evidence=current(),table=element('table','ga-table'),head=element('tr');for(const label of ['Analiz / kV / tür','Metrik','Eşleşen / uygun','Kapsam %','Tolerans içi %','MAE / P95 / maks','Tolerans / metot'])head.append(element('th','',label));table.append(head);for(const r of evidence.rows){const tr=element('tr');tr.title=JSON.stringify(r.reasons);for(const value of [`${r.analysis} / ${r.kv} / ${r.kind}`,r.metric,`${r.matched} / ${r.eligible} (PF dışı ${r.excludedPF})`,format(r.coverage),r.agreement===null?'HESAPLANAMAZ':format(r.agreement),`${format(r.mae)} / ${format(r.p95)} / ${format(r.maximum)} ${r.unit}`,`${r.tolerance} · ${r.method}`])tr.append(element('td','',value));table.append(tr);}const wrap=element('div','ga-table-wrap');wrap.append(table);body.replaceChildren(wrap);trend.textContent=previous?JSON.stringify(compareScorecardVersions(previous,evidence)):'Önceki gerçek sürüm kaydı yok · gelişme yüzdesi HESAPLANAMAZ';}
  return{element:root,render};
}
