import {requestedRole,calculationLabel,baseResultNotice} from '../../ui/components/calculation-controls';
import {createVoltageFilter} from '../../ui/components/voltage-filter';
import {voltageMatches} from '../../domain/model/voltage-band';
import {displayBranches} from '../../domain/results/presentation';
import type {AppContext,Feature} from '../../app/contracts';
import {element,button,format as f,escapeHtml as h,downloadText,csvCell} from '../../ui/components/dom';
import {ResultTable} from './result-table';
import {createCapacityView} from './capacity-view';
import {comparePowerFactoryReference,importPowerFactoryReference,type PowerFactoryReferenceRecord} from '../../analysis/validation/powerfactory-reference';
export function createAnalysisView(ctx:AppContext):Feature{
  const root=element('section','ga-analysis-view'),heading=element('h2','','Analizler'),controls=element('div','ga-analysis-controls'),status=element('p','ga-notice'),tabs=element('div','ga-tabs-small'),content=element('div','ga-panel'),tableHost=element('div'),table=new ResultTable(ctx,tableHost,false),capacityView=createCapacityView(ctx),search=element('input');let active='summary',genPage=0;
  search.type='search';search.placeholder='Ad veya FID ara';search.setAttribute('aria-label','Analiz sonuçlarında ara');search.oninput=()=>{table.search=search.value;table.page=0;genPage=0;render();};
  const actions=[button('Tam AC · Full Newton–Raphson',()=>void ctx.run('powerFlow',requestedRole(ctx))),button('Hızlı Yaklaşık AC',()=>void ctx.run('fastAc',requestedRole(ctx))),button('DC Tarama',()=>void ctx.run('dc',requestedRole(ctx)))],cancel=button('İptal',()=>ctx.cancel()),role=element('select'),engine=element('select'),referenceInput=element('input');let referenceRecords:PowerFactoryReferenceRecord[]=[],referenceFileName='',referenceError='';
  referenceInput.type='file';referenceInput.accept='.json,.csv,application/json,text/csv';referenceInput.className='ga-visually-hidden';referenceInput.setAttribute('aria-label','PowerFactory referans JSON veya CSV');referenceInput.onchange=()=>{const file=referenceInput.files?.[0];if(!file)return;void file.text().then(text=>{referenceRecords=importPowerFactoryReference(text);referenceFileName=file.name;referenceError='';active='diagnostics';render();}).catch(error=>{referenceError=error instanceof Error?error.message:String(error);active='diagnostics';render();}).finally(()=>{referenceInput.value='';});};
  role.setAttribute('aria-label','Analiz sonuç kaynağı');role.innerHTML='<option value="base">Baz</option><option value="scenario">Senaryo</option><option value="delta">Senaryo Δ</option>';role.onchange=()=>{ctx.resultStore.role=role.value as 'base'|'scenario'|'delta';ctx.notify();};
  engine.setAttribute('aria-label','Gösterilen hesap türü');engine.innerHTML='<option value="powerFlow">Tam AC</option><option value="fastAc">Hızlı AC</option><option value="dc">DC</option>';engine.onchange=()=>{ctx.resultStore.analysisType=engine.value as 'powerFlow'|'fastAc'|'dc';ctx.notify();};
  controls.append(...actions,cancel,role,engine,button('PowerFactory referansı (JSON/CSV)',()=>referenceInput.click()),referenceInput,button('CSV indir',()=>{const r=ctx.resultStore.active;if(!r)return;const rows=active==='voltage'?r.buses:active==='generators'?r.generators:[...displayBranches(ctx.network!,r).values()].filter(b=>active==='trafos'?b.sourceClass==='ElmTr2':active==='lines'?b.sourceClass==='ElmLne':true),keys=rows.length?['name','id',...Object.keys(rows[0]).filter(k=>!['name','id'].includes(k))]:[];downloadText('\uFEFFsep=;\r\n'+[keys.map(csvCell).join(';'),...rows.map(row=>keys.map(k=>csvCell((row as unknown as Record<string,unknown>)[k])).join(';'))].join('\r\n'),'GridAnalyzer-sonuclar.csv','text/csv;charset=utf-8');}));
  for(const[key,label]of[['summary','Özet'],['voltage','Gerilim'],['lines','Hatlar'],['trafos','Trafolar'],['generators','Üreticiler'],['topology','Topoloji'],['diagnostics','Tanı'],['capacity','Hat kapasiteleri']]){const b=button(label,()=>{active=key;table.page=0;render();});b.dataset.analysis=key;tabs.append(b);}
  const baseNotice=baseResultNotice(ctx);root.append(baseNotice.element);
  const voltageFilter=createVoltageFilter(ctx,'Analiz gerilim grupları');root.append(heading,controls,voltageFilter.element,status,tabs,search,content);
  function render(){baseNotice.render();['Tam AC','Hızlı AC','DC'].forEach((label,i)=>{actions[i].textContent=calculationLabel(ctx)+' · '+label;actions[i].setAttribute('aria-label',actions[i].textContent);});voltageFilter.render();actions.forEach(b=>b.disabled=ctx.busy||!ctx.network);cancel.disabled=!ctx.busy;role.value=ctx.resultStore.role;engine.value=ctx.resultStore.analysisType;status.textContent=ctx.status;tabs.querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.analysis===active)));
    const n=ctx.network,r=ctx.resultStore.active;if(!n){content.textContent='Önce DGS JSON modeli yükleyin.';return;}content.replaceChildren();
    if(['voltage','lines','trafos'].includes(active)){table.kind=active==='voltage'?'bus':active==='trafos'?'trafo':'line';table.tab=ctx.resultStore.role==='delta'?'delta':'results';content.append(tableHost);table.render();return;}
    if(active==='capacity'){capacityView.render(search.value);content.append(capacityView.element);return;}
    if(active==='summary'){const labels=[['Model',n.name],['Hesap',r?.status||'Hesap bekleniyor'],['Bara',f(r?.buses.length,0)],['Dal',f(r?.branches.length,0)],['Adım',f(r?.iterations,0)],['Max Δ MW',f(r?.maxMismatchMw,8)],['Süre s',f(r?r.elapsedMs/1000:null,2)],['Referans','PowerFactory referansı mevcut değil']];content.innerHTML=`<div class="ga-card-grid">${labels.map(([a,b])=>`<div class="ga-card"><small>${a}</small><strong>${h(b)}</strong></div>`).join('')}</div><p class="ga-muted">${ctx.resultStore.analysisType==='powerFlow'?'Full Newton–Raphson · Tüm gerilim seviyeleri · PV/PQ, Q limitleri, snapshot trafo tapları':'66 kV+ indirgenmiş ağ · Yaklaşık sonuç'}. Kontrol eşlemesi kısmi; station/secondary dış kontrol döngüleri uygulanmaz.</p>`;return;}
    if(active==='topology'||active==='diagnostics'){const referenceComparison=active==='diagnostics'&&referenceRecords.length?{file:referenceFileName,records:referenceRecords.length,available:r?.converged?comparePowerFactoryReference(referenceRecords,r):null,note:r?.converged?undefined:'Karşılaştırma için yakınsamış sonuç gerekir.'}:null;const summary=active==='topology'?r?.diagnostics:{capabilities:n.capabilities,result:r?.diagnostics,referenceError:referenceError||undefined,referenceComparison,warnings:[...n.warnings,...(r?.warnings||[])].slice(0,100)};const pre=element('pre','ga-diagnostics',JSON.stringify(summary||{status:'Elektriksel topoloji hesapla hazırlanır.',terminals:n.buses.length,switches:n.switches.length},null,2));content.append(pre);return;}
    const q=search.value.toLocaleLowerCase('tr-TR');
    if(active==='generators'){const all=(r?.generators||[]).filter(g=>voltageMatches(r?.buses.find(b=>b.id===g.bus)?.vnKv,ctx.filters.voltages)).filter(g=>`${g.name} ${g.id}`.toLocaleLowerCase('tr-TR').includes(q));genPage=Math.max(0,Math.min(genPage,Math.ceil(all.length/20)-1));const rows=all.slice(genPage*20,genPage*20+20);content.innerHTML=`<div class="ga-table-wrap"><table class="ga-table"><thead><tr><th>Üretici</th><th>P MW</th><th>Q MVAr</th><th>Q durumu</th></tr></thead><tbody>${rows.map(g=>`<tr><td><strong>${h(g.name)}</strong><small>${h(g.id)}</small></td><td>${f(g.pMw)}</td><td>${f(g.qMvar)}</td><td>${h(g.qState)}</td></tr>`).join('')}</tbody></table></div>`;const pager=element('div','ga-pager');pager.append(button('Önceki',()=>{genPage--;render();}),element('span','',`${all.length} kayıt · ${genPage+1}`),button('Sonraki',()=>{genPage++;render();}));content.append(pager);return;}
  }
  return{element:root,render};
}
