import {requestedRole,calculationLabel,baseResultNotice,calculationSessionStatus} from '../../ui/components/calculation-controls';
import {createVoltageFilter} from '../../ui/components/voltage-filter';
import {voltageMatches} from '../../domain/model/voltage-band';
import {displayBranches} from '../../domain/results/presentation';
import type {AppContext,Feature} from '../../app/contracts';
import {element,button,format as f,escapeHtml as h,downloadText,csvCell} from '../../ui/components/dom';
import {ResultTable} from './result-table';
import {createCapacityView} from './capacity-view';
import {comparePowerFactoryReference,importPowerFactoryReferenceDocument,powerFactoryLoadFlowSettings,type PowerFactoryComparison,type PowerFactoryReference} from '../../analysis/validation/powerfactory-reference';
import {preflightPowerFactoryReference,type ReferencePreflight} from '../../analysis/validation/powerfactory-preflight';
import {createComparisonView} from './comparison-view';
import {createTopologyView} from './topology-view';
import {comparisonSheets,downloadComparisonWorkbook,downloadComparisonCsv} from './comparison-export';
import {downloadResultWorkbook} from './xlsx-export';
import {createAnalysisSettingsDialog} from './analysis-settings-dialog';
export function createAnalysisView(ctx:AppContext):Feature{
  const root=element('section','ga-analysis-view'),heading=element('h2','','Analizler'),controls=element('div','ga-analysis-controls'),status=element('p','ga-notice'),tabs=element('div','ga-tabs-small'),content=element('div','ga-panel'),tableHost=element('div'),table=new ResultTable(ctx,tableHost,false),capacityView=createCapacityView(ctx),search=element('input');let active='summary',genPage=0;
  search.type='search';search.placeholder='Ad veya FID ara';search.setAttribute('aria-label','Analiz sonuçlarında ara');search.oninput=()=>{table.search=search.value;table.page=0;genPage=0;render();};
  const actions=[button('Tam AC · Full Newton–Raphson',()=>void ctx.run('powerFlow',requestedRole(ctx))),button('Hızlı Yaklaşık AC',()=>void ctx.run('fastAc',requestedRole(ctx))),button('DC Tarama',()=>void ctx.run('dc',requestedRole(ctx)))],cancel=button('İptal',()=>ctx.cancel()),role=element('select'),engine=element('select'),referenceInput=element('input'),controlContextInput=element('input');
  const settingsDialog=createAnalysisSettingsDialog(ctx.analysisSettings,()=>ctx.notify()),settingsButton=button('Hesap Ayarları',settingsDialog.open);
  let reference:PowerFactoryReference|null=null,referenceError='',diagnosticTab:'system'|'comparison'|'settings'='system';
  let cachedNetwork:typeof ctx.network=null,cachedResult:typeof ctx.resultStore.active=null,cachedReference:PowerFactoryReference|null=null,cachedPreflight:ReferencePreflight|null=null,cachedComparison:PowerFactoryComparison|null=null;
  const comparisonHost=element('div'),comparisonView=createComparisonView(comparisonHost),topologyHost=element('div'),topologyView=createTopologyView(ctx,topologyHost);
  function comparisonState(){const n=ctx.network,r=ctx.resultStore.active;if(!n||!reference||!r)return{preflight:null,report:null};if(cachedNetwork!==n||cachedResult!==r||cachedReference!==reference){cachedPreflight=preflightPowerFactoryReference(reference,n,r,ctx.powerFactoryControlContextNumericFile);cachedComparison=comparePowerFactoryReference(cachedPreflight.reference,r,cachedPreflight.context);cachedNetwork=n;cachedResult=r;cachedReference=reference;}return{preflight:cachedPreflight,report:cachedComparison};}
  function exportComparison(kind:'xlsx'|'csv'){const n=ctx.network,r=ctx.resultStore.active,{preflight,report}=comparisonState();if(!n||!r||!reference||!preflight||!report)return;const sheets=comparisonSheets(report,preflight,n,r,reference);if(kind==='xlsx')downloadComparisonWorkbook(sheets);else downloadComparisonCsv(sheets);}
  function settingsComparison(){
    const host=element('div'),preflight=comparisonState().preflight,report=comparisonState().report;
    if(!reference){host.append(element('p','ga-notice','Önce PowerFactory referans CSV veya JSON dosyasını yükleyin.'));return host;}
    const result=ctx.resultStore.active,detected=powerFactoryLoadFlowSettings(reference),ga=ctx.analysisSettings.value.powerFlow,sem=detected.semantic,balance=result?.diagnostics.activeBalancing&&typeof result.diagnostics.activeBalancing==='object'?result.diagnostics.activeBalancing as Record<string,unknown>:{},effectiveBalance=String(balance.effectiveActiveBalancingMode??balance.effectiveMode??'SINGLE_REFERENCE');
    const rows:Array<[string,string,string,string,string]>=[
      ['Analysis profile','profile','POWERFACTORY_TEIAS_PARITY',ga.profile,'Selected calculation profile'],
      ['Network representation','networkRepresentation','Balanced Positive Sequence','Balanced Positive Sequence','Model temsili'],
      ['Equation formulation','equationFormulation','Classical Newton-Raphson — Power Equations','Classical Newton-Raphson — Power Equations','Newton denklemi'],
      ['P control','activeControlMode','As Dispatched','As Dispatched','Aktif güç talimatı'],
      ['P balancing','activeBalancingMode','Distributed Slack by Loads',effectiveBalance==='DISTRIBUTED_ADJUSTABLE_LOADS'?'Distributed Slack by Loads':'Single Reference','Dengeleme kaynakları ve yük verisi'],
      ['Station control','stationControlMode','Zero Droop',ga.stationControlMode==='zeroDroop'?'Zero Droop':ga.stationControlMode==='droop'?'Droop':'Off','İstasyon controller fidelity'],
      ['Q limits','reactiveLimitsEnabled','ON',ga.reactiveLimitsEnabled?'ON':'OFF','Üretici ve referans Q sınırları'],
      ['P limits','activePowerLimitsEnabled','OFF',ga.activePowerLimitsEnabled?'ON':'OFF','Aktif üretim sınırları'],
      ['Auto tap','automaticTransformerTap','OFF',ga.automaticTransformerTap?'ON':'OFF','Tap aktif-set kontrolü'],['Auto shunt','automaticShunt','OFF',ga.automaticShunt?'ON':'OFF','Şönt adım kontrolü'],
      ['Load voltage dependency','loadVoltageDependency','OFF',ga.loadVoltageDependency?'ON':'OFF','Yük modeli'],['Feeder load scaling','feederLoadScaling','OFF',ga.feederLoadScaling?'ON':'OFF','Fider yük çarpanı'],['Interchange schedule','interchangeSchedule','OFF',ga.interchangeSchedule?'ON':'OFF','Sınır alışveriş programı'],
      ['Load scale','loadScalePercent','100%',ctx.analysisSettings.value.shared.loadScalePercent===100?'100%':'100% (setting not applied)','Sabit yük ölçeği'],['Generation scale','generationScalePercent','100%',ctx.analysisSettings.value.shared.generationScalePercent===100?'100%':'100% (setting not applied)','Üretim ölçeği'],
      ['NR max','maxInnerIterations','100',String(ga.maxInnerIterations),'İç çözüm bütçesi'],
      ['Outer max','maxOuterIterations','50',String(ga.maxOuterIterations),'Kontrol çözüm bütçesi'],['Node tolerance','nodalToleranceKva','5 kVA',`${ga.nodalToleranceKva} kVA`,'Düğüm P/Q artığı'],
      ['Model tolerance','modelEquationTolerancePercent','0.2 %',`${ga.modelEquationTolerancePercent} %`,'Kontrol denklem artığı'],['Stagnation limit','maxNoImprovementIterations','20',String(ga.maxNoImprovementIterations),'İyileşme izleme'],
      ['Reactive limit repeat','repeatedReactiveLimitDetection','3',String(ga.repeatedReactiveLimitDetection),'Tekrarlı Q sınırı algılama'],['Q limit tolerance','qLimitToleranceMvar','0.02 MVAr',`${ga.qLimitToleranceMvar} MVAr`,'PV/PQ limit geçişi']
    ];
    const table=element('table','ga-settings-diff'),head=element('thead'),hr=element('tr');for(const title of ['Ayar','PowerFactory','Grid Analyzer','Durum','Etki'])hr.append(element('th','',title));head.append(hr);table.append(head);
    const body=element('tbody');for(const [label,key,pfFallback,gaValue,impact] of rows){const pf=sem[key],known=typeof pf==='string',pfValue=known?pf:'Bilinmiyor',matches=known&&pf.trim().toLocaleLowerCase('en-US')===pfFallback.toLocaleLowerCase('en-US')&&gaValue.toLocaleLowerCase('en-US')===pfFallback.toLocaleLowerCase('en-US');const tr=element('tr');for(const value of [label,pfValue,gaValue,known?(matches?'✓ Eşleşiyor':'Uyuşmuyor'):'Bilinmiyor',impact])tr.append(element('td','',value));tr.dataset.status=known?(matches?'match':'mismatch'):'unknown';body.append(tr);}table.append(body);host.append(table);
    const eligibility=preflight?.context.activeBalanceEligibilityAvailable??false,settingsAvailable=preflight?.context.calculationSettingsSemanticsAvailable??false;
    const gate=report?.compatibility.status??(preflight?.status??'BLOCKED');
    host.append(element('p','ga-notice',`Karşılaştırma durumu: ${gate}${!settingsAvailable?' · PowerFactory ayar semantiği mevcut değil':''}${!eligibility?' · ACTIVE_BALANCE_ELIGIBILITY_MISSING':''}`));
    if(!eligibility)host.append(element('p','ga-muted','Ayarlanabilir yük katılımı tüm etkin yüklerde doğrulanmadı. Karşılaştırma COMPARABLE_PARTIAL olarak kalır; distributed-load parity onaylanmaz.'));
    if(detected.profile==='UNKNOWN'&&Object.keys(detected.raw).length)host.append(element('p','ga-muted',`ComLdf alanları bulundu; enum değerleri çevrilmeden saklanıyor (${Object.keys(detected.raw).join(', ')}).`));
    return host;
  }
  referenceInput.type='file';referenceInput.accept='.json,.csv,application/json,text/csv';referenceInput.className='ga-visually-hidden';referenceInput.setAttribute('aria-label','PowerFactory referans JSON veya CSV');referenceInput.onchange=()=>{const file=referenceInput.files?.[0];if(!file)return;void file.text().then(text=>{reference=importPowerFactoryReferenceDocument(text,file.name);settingsDialog.setReference(reference);referenceError='';active='diagnostics';diagnosticTab='comparison';ctx.resultStore.role='base';ctx.resultStore.analysisType='powerFlow';render();}).catch(error=>{referenceError=error instanceof Error?error.message:String(error);settingsDialog.setReference(null);active='diagnostics';diagnosticTab='comparison';render();}).finally(()=>{referenceInput.value='';});};
  controlContextInput.type='file';controlContextInput.accept='.csv,text/csv';controlContextInput.className='ga-visually-hidden';controlContextInput.setAttribute('aria-label','PowerFactory ControlContext CSV');controlContextInput.onchange=()=>{const file=controlContextInput.files?.[0];if(!file)return;void ctx.loadPowerFactoryControlContext(file).then(()=>{referenceError='';cachedNetwork=null;active='diagnostics';diagnosticTab='settings';render();}).catch(error=>{referenceError=error instanceof Error?error.message:String(error);ctx.setMessage(`ControlContext yüklenemedi: ${referenceError}`);}).finally(()=>{controlContextInput.value='';});};
  role.setAttribute('aria-label','Analiz sonuç kaynağı');role.innerHTML='<option value="base">Baz</option><option value="scenario">Senaryo</option><option value="delta">Senaryo Δ</option>';role.onchange=()=>{ctx.resultStore.role=role.value as 'base'|'scenario'|'delta';ctx.notify();};
  engine.setAttribute('aria-label','Gösterilen hesap türü');engine.innerHTML='<option value="powerFlow">Tam AC</option><option value="fastAc">Hızlı AC</option><option value="dc">DC</option>';engine.onchange=()=>{ctx.resultStore.analysisType=engine.value as 'powerFlow'|'fastAc'|'dc';ctx.notify();};
  controls.append(...actions,settingsButton,cancel,role,engine,button('PowerFactory referansı (JSON/CSV)',()=>referenceInput.click()),referenceInput,button('PowerFactory ControlContext (CSV)',()=>controlContextInput.click()),controlContextInput,button('XLSX sonuç indir',()=>{const result=ctx.resultStore.active;if(result&&ctx.network)downloadResultWorkbook(result,ctx.network,comparisonState().report||undefined);}),button('CSV indir',()=>{const r=ctx.resultStore.active,n=ctx.network;if(!r||!n)return;const rows=active==='voltage'?r.buses:active==='generators'?r.generators:[...displayBranches(n,r).values()].filter(b=>active==='trafos'?b.sourceClass==='ElmTr2':active==='lines'?b.sourceClass==='ElmLne':true),keys=rows.length?['name','id',...Object.keys(rows[0]).filter(k=>!['name','id'].includes(k))]:[];let options:Record<string,unknown>={};try{options=JSON.parse(r.identity.optionsHash) as Record<string,unknown>;}catch{/* provenance may come from older results */}const meta:[string,string][]=[['engine',r.identity.analysisType],['analysisSettingsHash',String(options.analysisSettingsHash??'unavailable')],['modelHash',r.identity.modelHash],['scenarioHash',r.identity.scenarioHash],['studyCase',n.studyCase||''],['controlContextHash',String(options.controlContextHash??'unavailable')]];const flatten=(v:unknown,p:string)=>{if(v&&typeof v==='object'&&!Array.isArray(v)){for(const[k,x]of Object.entries(v))flatten(x,p?`${p}.${k}`:k);}else if(v!==undefined)meta.push([`analysisSettings.${p}`,String(v)]);};flatten(options.analysisSettings,'');const provenance=['Provenance;Value',...meta.map(([k,v])=>`${csvCell(k)};${csvCell(v)}`)].join('\r\n'),table=[keys.map(csvCell).join(';'),...rows.map(row=>keys.map(k=>csvCell((row as unknown as Record<string,unknown>)[k])).join(';'))].join('\r\n');downloadText('\uFEFFsep=;\r\n'+provenance+'\r\n\r\n'+table,'GridAnalyzer-sonuclar.csv','text/csv;charset=utf-8');}));
  root.append(settingsDialog.element);
  for(const[key,label]of[['summary','Özet'],['voltage','Gerilim'],['lines','Hatlar'],['trafos','Trafolar'],['generators','Üreticiler'],['topology','Topoloji'],['diagnostics','Tanı'],['capacity','Hat kapasiteleri']]){const b=button(label,()=>{active=key;table.page=0;render();});b.dataset.analysis=key;tabs.append(b);}
  const baseNotice=baseResultNotice(ctx),sessionStatus=calculationSessionStatus(ctx);root.append(baseNotice.element,sessionStatus.element);
  const voltageFilter=createVoltageFilter(ctx,'Analiz gerilim grupları');root.append(heading,controls,voltageFilter.element,status,tabs,search,content);
  function render(){baseNotice.render();sessionStatus.render();['Tam AC','Hızlı AC','DC'].forEach((label,i)=>{actions[i].textContent=calculationLabel(ctx)+' · '+label;actions[i].setAttribute('aria-label',actions[i].textContent);});voltageFilter.render();actions.forEach(b=>b.disabled=ctx.busy||!ctx.network);cancel.disabled=!ctx.busy;role.value=ctx.resultStore.role;engine.value=ctx.resultStore.analysisType;status.textContent=ctx.status;tabs.querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.analysis===active)));
    const n=ctx.network,r=ctx.resultStore.active;if(!n){content.textContent='Önce DGS JSON modeli yükleyin.';return;}content.replaceChildren();
    if(['voltage','lines','trafos'].includes(active)){table.kind=active==='voltage'?'bus':active==='trafos'?'trafo':'line';table.tab=ctx.resultStore.role==='delta'?'delta':'results';content.append(tableHost);table.render();return;}
    if(active==='capacity'){capacityView.render(search.value);content.append(capacityView.element);return;}
    if(active==='summary'){const labels=[['Model',n.name],['Hesap',r?.status||'Hesap bekleniyor'],['Bara',f(r?.buses.length,0)],['Dal',f(r?.branches.length,0)],['Adım',f(r?.iterations,0)],['Max Δ MW',f(r?.maxMismatchMw,8)],['Süre s',f(r?r.elapsedMs/1000:null,2)],['Referans',reference?'PowerFactory karşılaştırması mevcut':'Referans yok']];content.innerHTML=`<div class="ga-card-grid">${labels.map(([a,b])=>`<div class="ga-card"><small>${a}</small><strong>${h(b)}</strong></div>`).join('')}</div><p class="ga-muted">${ctx.resultStore.analysisType==='powerFlow'?'Full Newton–Raphson · Tüm gerilim seviyeleri · PV/PQ, Q limitleri, ayrı referanslı adalar ve snapshot trafo tapları':'66 kV+ indirgenmiş ağ · Yaklaşık sonuç'}. Kontrolör kaynak alanları korunur; doğrulanmamış i_ctrl/imode semantiği nedeniyle dış kontrol uygulanmaz.</p>`;return;}
    if(active==='topology'){content.append(topologyHost);topologyView.render(comparisonState().preflight);return;}
    if(active==='diagnostics'){
      const diagnosticTabs=element('div','ga-tabs-small');for(const [key,label] of [['system','Sistem Tanısı'],['comparison','Karşılaştır'],['settings','Ayarlar']] as const){const tab=button(label,()=>{diagnosticTab=key;render();});tab.setAttribute('aria-pressed',String(diagnosticTab===key));diagnosticTabs.append(tab);}content.append(diagnosticTabs);
      if(diagnosticTab==='settings'){content.append(settingsComparison());return;}
      if(diagnosticTab==='comparison'){const {preflight,report}=comparisonState();if(referenceError)content.append(element('p','ga-notice',referenceError));if(!r)content.append(element('p','ga-notice','Karşılaştırma için yakınsamış Tam AC baz sonucunu hesaplayın.'));content.append(comparisonHost);comparisonView.render(report,preflight);if(report&&preflight){const downloads=element('div','ga-analysis-controls');downloads.append(button('Karşılaştırma XLSX',()=>exportComparison('xlsx')),button('Karşılaştırma CSV',()=>exportComparison('csv')));content.append(downloads);}return;}
      const warnings=[...n.warnings,...(r?.warnings||[])].slice(0,100),cards=[['Model',n.name],['Topoloji terminali',n.buses.length],['Anahtar',n.switches.length],['Hesap',r?.status||'Bekleniyor'],['Yakınsama',r?.converged?'Evet':'Hayır'],['Uyarı',warnings.length]],summary=element('div');summary.innerHTML=`<div class="ga-card-grid">${cards.map(([label,value])=>`<div class="ga-card"><small>${h(label)}</small><strong>${h(value)}</strong></div>`).join('')}</div>`;if(warnings.length)summary.innerHTML+=`<h3>Uyarılar</h3><ul>${warnings.map(item=>`<li>${h(item)}</li>`).join('')}</ul>`;content.append(summary);return;
    }
    const q=search.value.toLocaleLowerCase('tr-TR');
    if(active==='generators'){const all=(r?.generators||[]).filter(g=>voltageMatches(r?.buses.find(b=>b.id===g.bus)?.vnKv,ctx.filters.voltages)).filter(g=>`${g.name} ${g.id}`.toLocaleLowerCase('tr-TR').includes(q));genPage=Math.max(0,Math.min(genPage,Math.ceil(all.length/20)-1));const rows=all.slice(genPage*20,genPage*20+20);content.innerHTML=`<div class="ga-table-wrap"><table class="ga-table"><thead><tr><th>Üretici</th><th>P MW</th><th>Q MVAr</th><th>Q durumu</th></tr></thead><tbody>${rows.map(g=>`<tr><td><strong>${h(g.name)}</strong><small>${h(g.id)}</small></td><td>${f(g.pMw)}</td><td>${f(g.qMvar)}</td><td>${h(g.qState)}</td></tr>`).join('')}</tbody></table></div>`;const pager=element('div','ga-pager');pager.append(button('Önceki',()=>{genPage--;render();}),element('span','',`${all.length} kayıt · ${genPage+1}`),button('Sonraki',()=>{genPage++;render();}));content.append(pager);return;}
  }
  return{element:root,render};
}
