import type {PowerFactoryComparison,ComparisonRow,MetricPair} from '../../analysis/validation/powerfactory-reference';
import type {ReferencePreflight} from '../../analysis/validation/powerfactory-preflight';
import {voltageBand} from '../../domain/model/voltage-band';
import {button,element,escapeHtml as h,format as f} from '../../ui/components/dom';

type Tab='summary'|'bus'|'line'|'transformer'|'generator'|'unmatched'|'topology';
type Flat={row:ComparisonRow;metric:string;pair:MetricPair};
const labels:Record<Tab,string>={summary:'Özet',bus:'Gerilim & Açı',line:'Hatlar',transformer:'Trafolar',generator:'Üreticiler',unmatched:'Eşleşmeyenler',topology:'Topoloji farkı'};
const metricLabels:Record<string,string>={voltagePu:'V pu',voltageKv:'V kV',angleDeg:'Ham açı',alignedAngleDeg:'Hizalı açı',nominalKv:'Nominal kV',pFromMw:'P uç A',qFromMvar:'Q uç A',pToMw:'P uç B',qToMvar:'Q uç B',pHvMw:'YG P',qHvMvar:'YG Q',pLvMw:'AG P',qLvMvar:'AG Q',pLossMw:'P kayıp',qLossMvar:'Q kayıp',currentFromA:'I uç A',currentToA:'I uç B',currentHvA:'YG I',currentLvA:'AG I',loadingPercent:'Yüklenme',tapPosition:'Kademe',tapRatio:'Tap oranı',phaseShiftDeg:'Faz',pMw:'P',qMvar:'Q'};

export function createComparisonView(host:HTMLElement){
  let report:PowerFactoryComparison|null=null,preflight:ReferencePreflight|null=null,flat:Flat[]=[],tab:Tab='summary',page=0,query='',band='all',ytm='all',tm='all',status='all',onlyDifferences=false,sort='hierarchy';
  const collapsed=new Set<string>(),hidden=new Set<string>();
  const tabs=element('div','ga-tabs-small'),filters=element('div','ga-comparison-filters'),body=element('div'),pager=element('div','ga-pager');
  const search=element('input'),voltage=element('select'),ytmSelect=element('select'),tmSelect=element('select'),matchSelect=element('select'),sortSelect=element('select'),only=element('input'),columns=element('div','ga-comparison-columns');
  search.type='search';search.placeholder='FID / ad ara';search.setAttribute('aria-label','Karşılaştırma ara');search.oninput=()=>{query=search.value.toLocaleLowerCase('tr-TR');page=0;draw();};
  voltage.setAttribute('aria-label','Gerilim filtresi');voltage.innerHTML='<option value="all">Tüm gerilimler</option><option value="400">400 kV</option><option value="220">220 kV</option><option value="154">154 kV</option><option value="66">66 kV</option><option value="low">Diğer</option>';voltage.onchange=()=>{band=voltage.value;page=0;draw();};
  ytmSelect.setAttribute('aria-label','YTM filtresi');ytmSelect.onchange=()=>{ytm=ytmSelect.value;page=0;draw();};tmSelect.setAttribute('aria-label','TM filtresi');tmSelect.onchange=()=>{tm=tmSelect.value;page=0;draw();};
  matchSelect.setAttribute('aria-label','Eşleşme durumu filtresi');matchSelect.innerHTML='<option value="all">Tüm eşleşmeler</option><option value="MATCHED">Eşleşen</option><option value="UNMATCHED_REFERENCE">PF eşleşmeyen</option><option value="UNMATCHED_ACTUAL">GA eşleşmeyen</option><option value="AMBIGUOUS">Belirsiz</option>';matchSelect.onchange=()=>{status=matchSelect.value;page=0;draw();};
  sortSelect.setAttribute('aria-label','Karşılaştırma sıralaması');sortSelect.innerHTML='<option value="hierarchy">YTM → TM → ekipman</option><option value="absolute">En büyük |Δ|</option><option value="delta">En büyük Δ</option><option value="name">Ekipman adı</option>';sortSelect.onchange=()=>{sort=sortSelect.value;page=0;draw();};
  only.type='checkbox';only.setAttribute('aria-label','Yalnız farklar');only.onchange=()=>{onlyDifferences=only.checked;page=0;draw();};const onlyLabel=element('label','ga-check');onlyLabel.append(only,document.createTextNode('Yalnız farklar'));
  for(const key of ['YTM','TM','Metric','Grid Analyzer','PowerFactory','Δ','|Δ|','Δ%']){const checkbox=element('input');checkbox.type='checkbox';checkbox.checked=true;checkbox.onchange=()=>{if(checkbox.checked)hidden.delete(key);else hidden.add(key);draw();};const label=element('label','ga-check');label.append(checkbox,document.createTextNode(key));columns.append(label);}
  for(const [key,label] of Object.entries(labels) as [Tab,string][]) {const control=button(label,()=>{tab=key;page=0;draw();});control.dataset.compareTab=key;tabs.append(control);}
  filters.append(search,voltage,ytmSelect,tmSelect,matchSelect,sortSelect,onlyLabel);host.append(tabs,filters,columns,body,pager);
  const card=(label:string,value:unknown)=>`<div class="ga-card"><small>${h(label)}</small><strong>${h(value)}</strong></div>`;
  const table=(headers:string[],rows:string[][])=>`<div class="ga-table-wrap"><table class="ga-table"><thead><tr>${headers.map(x=>`<th>${h(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(value=>`<td>${value}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
  const note=(text:string)=>`<p class="ga-muted">${h(text)}</p>`;
  function selectOptions(select:HTMLSelectElement,values:string[],title:string,current:string){select.innerHTML=`<option value="all">${h(title)}</option>`+values.sort((a,b)=>a.localeCompare(b,'tr')).map(value=>`<option value="${h(value)}">${h(value)}</option>`).join('');select.value=values.includes(current)?current:'all';}
  function setReport(next:PowerFactoryComparison|null,nextPreflight:ReferencePreflight|null){if(next!==report){report=next;flat=next?next.rows.flatMap(row=>Object.entries(row.metrics).map(([metric,pair])=>({row,metric,pair:pair!}))):[];const ytmValues=[...new Set(next?.rows.map(row=>row.hierarchy.ytm).filter((x):x is string=>!!x)||[])],tmValues=[...new Set(next?.rows.map(row=>row.hierarchy.tm).filter((x):x is string=>!!x)||[])];selectOptions(ytmSelect,ytmValues,'Tüm YTM',ytm);selectOptions(tmSelect,tmValues,'Tüm TM',tm);page=0;}preflight=nextPreflight;draw();}
  function visible(row:ComparisonRow){const name=`${row.gridAnalyzerId||''} ${row.powerFactoryFid||''} ${row.gridAnalyzerName||''} ${row.powerFactoryName||''}`.toLocaleLowerCase('tr-TR');return(!query||name.includes(query))&&(band==='all'||voltageBand(row.hierarchy.voltageKv||0)===band)&&(ytm==='all'||row.hierarchy.ytm===ytm)&&(tm==='all'||row.hierarchy.tm===tm)&&(status==='all'||row.status===status);}
  function paginate<T>(rows:T[]):T[]{const count=Math.max(1,Math.ceil(rows.length/60));page=Math.min(page,count-1);pager.append(button('Önceki',()=>{page=Math.max(0,page-1);draw();}),element('span','',`${rows.length} satır · ${page+1}/${count}`),button('Sonraki',()=>{page=Math.min(count-1,page+1);draw();}));(pager.firstChild as HTMLButtonElement).disabled=page===0;(pager.lastChild as HTMLButtonElement).disabled=page>=count-1;return rows.slice(page*60,page*60+60);}
  function draw(){tabs.querySelectorAll<HTMLButtonElement>('button').forEach(control=>control.setAttribute('aria-pressed',String(control.dataset.compareTab===tab)));body.replaceChildren();pager.replaceChildren();filters.hidden=tab==='summary'||tab==='topology';columns.hidden=filters.hidden||tab==='unmatched';if(!report){body.textContent='PowerFactory referansı yükleyin.';return;}
    const blocked=report.compatibility.status==='BLOCKED'||preflight?.status==='BLOCKED';
    if(tab==='summary'){const p=preflight;body.innerHTML=`<div class="ga-card-grid">${card('Uyumluluk',blocked?'Bloklandı':'Doğrulandı')}${card('Eşleşen ekipman',report.summary.matchedTotal)}${card('PF eşleşmeyen',report.summary.unmatchedReference)}${card('Belirsiz',report.summary.ambiguousReference)}${card('PF bara değer çelişkisi',report.referenceValueConflicts.length)}${card('Elektriksel bara',p?.topology.electricalBusesChecked??'—')}${card('Dal uçları',p?.topology.branchEndpointsChecked??'—')}</div>`;
      if(blocked)body.innerHTML+=`<p class="ga-notice">${h([...(p?.reasons||[]),...report.compatibility.reasons].join(' · '))}</p>`;else body.innerHTML+=`<p class="ga-muted">${h(p?.topology.physicalTerminalsChecked)} aktif terminal doğrulandı · ${h(p?.topology.inactiveStubTerminals)} enjeksiyonsuz uç hesap grafiğinde yok · study time ${h(p?.studyTimeProvenance==='STUDY_CASE_NAME'?'study case adından':'doğrulanamadı')}</p>`;
      body.innerHTML+=table(['Ekipman','Metrik','N','MAE','P95 |Δ|','Maks |Δ|','Birim'],report.metrics.map(row=>[h(labels[row.kind as Tab]||row.kind),h(metricLabels[row.metric]||row.metric),h(row.count),f(row.mae,4),f(row.p95AbsoluteError,4),f(row.maxAbsoluteError,4),h(row.unit)]));body.innerHTML+=note('PF c:loading yalnız eşdeğer akım/rating semantiği doğrulanınca sayısal metrik olur. Ham açı saklanır; hizalı açı ada referansı veya medyan ofsetle gösterilir.');return;}
    if(tab==='topology'){const p=preflight;body.innerHTML=p?table(['Kontrol','Değer'],[['Durum',h(p.status)],['Model',h(p.context.modelId)],['Study case',h(p.context.studyCase)],['Study time',h(p.context.studyTime)],['Elektriksel bara grubu',h(p.topology.electricalBusesChecked)],['Fiziksel terminal',h(p.topology.physicalTerminalsChecked)],['Aktif olmayan eksik terminal',h(p.topology.inactiveStubTerminals)],['Dal ucu',h(p.topology.branchEndpointsChecked)],['Dal uç farkı',h(p.topology.branchEndpointConflicts)]]):note('PF topoloji bilgisi yok.');return;}
    if(tab==='unmatched'){const rows=report.rows.filter(row=>row.status!=='MATCHED'&&visible(row));body.innerHTML=table(['Durum','Sınıf','PF FID','GA FID','Ad','YTM','TM'],paginate(rows).map(row=>[h(row.status),h(row.kind),h(row.powerFactoryFid),h(row.gridAnalyzerId),h(row.powerFactoryName||row.gridAnalyzerName),h(row.hierarchy.ytm),h(row.hierarchy.tm)]));return;}
    let rows=flat.filter(entry=>entry.row.kind===tab&&visible(entry.row)&&(!onlyDifferences||entry.pair.absoluteDelta!=null&&entry.pair.absoluteDelta>1e-6));
    if(sort==='absolute')rows=rows.sort((a,b)=>(b.pair.absoluteDelta??-1)-(a.pair.absoluteDelta??-1));else if(sort==='delta')rows=rows.sort((a,b)=>(b.pair.delta??-Infinity)-(a.pair.delta??-Infinity));else if(sort==='name')rows=rows.sort((a,b)=>(a.row.gridAnalyzerName||a.row.powerFactoryName||'').localeCompare(b.row.gridAnalyzerName||b.row.powerFactoryName||'','tr'));else rows=rows.sort((a,b)=>`${a.row.hierarchy.ytm||''}|${a.row.hierarchy.tm||''}|${a.row.gridAnalyzerName||a.row.powerFactoryName||''}|${a.metric}`.localeCompare(`${b.row.hierarchy.ytm||''}|${b.row.hierarchy.tm||''}|${b.row.gridAnalyzerName||b.row.powerFactoryName||''}|${b.metric}`,'tr'));
    const selected=paginate(rows),headers=['YTM','TM','Ekipman','FID','Metric','Grid Analyzer','PowerFactory','Δ','|Δ|','Δ%','Durum',...(tab==='generator'?['GA Q durumu','PF kontrol','Bara eşleşmesi']:[])],keys=headers,visibleColumns=headers.filter((_,index)=>!hidden.has(keys[index]));
    const groups=new Map<string,number>();let lastGroup='';const lineMarkup=selected.map(({row,metric,pair})=>{
      const group=`${row.hierarchy.ytm||'—'} / ${row.hierarchy.tm||'—'}`,isNew=sort==='hierarchy'&&group!==lastGroup;lastGroup=group;
      let header='';if(isNew){const index=groups.size;groups.set(group,index);header=`<tr class="ga-comparison-group"><th colspan="${visibleColumns.length}"><button type="button" class="ga-button" data-compare-group="${index}" aria-expanded="${!collapsed.has(group)}">${collapsed.has(group)?'▸':'▾'} ${h(group)}</button></th></tr>`;}
      if(sort==='hierarchy'&&collapsed.has(group))return header;
      const values=[row.hierarchy.ytm||'—',row.hierarchy.tm||'—',row.gridAnalyzerName||row.powerFactoryName||'—',row.gridAnalyzerId||row.powerFactoryFid||'—',metricLabels[metric]||metric,pair.comparable?f(pair.gridAnalyzer,5):'—',f(pair.powerFactory,5),pair.comparable?f(pair.delta,5):'—',pair.comparable?f(pair.absoluteDelta,5):'—',pair.comparable?f(pair.deltaPercent,2):'—',row.status,...(tab==='generator'?[row.generatorControl?.gridAnalyzerQState||'—',row.generatorControl?.powerFactoryControlModeRaw||'—',row.generatorControl?.busMatch||'—']:[])];
      return header+`<tr>${values.filter((_,index)=>!hidden.has(keys[index])).map(value=>`<td>${h(value)}</td>`).join('')}</tr>`;
    }).join('');
    body.innerHTML=`<div class="ga-table-wrap"><table class="ga-table"><thead><tr>${visibleColumns.map(x=>`<th>${h(x)}</th>`).join('')}</tr></thead><tbody>${lineMarkup}</tbody></table></div>`+(rows.length===0?note('Bu filtrede kayıt yok.'):note('Sayısal sıralama Grid Analyzer | PowerFactory | Δ | |Δ| | Δ% şeklindedir. Eşdeğerliği doğrulanmayan alanlarda Δ boş bırakılır.'));
    body.querySelectorAll<HTMLButtonElement>('[data-compare-group]').forEach(control=>control.onclick=()=>{const group=[...groups.keys()][Number(control.dataset.compareGroup)];if(collapsed.has(group))collapsed.delete(group);else collapsed.add(group);draw();});
  }
  return{render:setReport,selectedTab:()=>tab};
}
