import type {PowerFactoryComparison,ComparisonRow,MetricPair} from '../../analysis/validation/powerfactory-reference';
import type {ReferencePreflight} from '../../analysis/validation/powerfactory-preflight';
import {voltageBand} from '../../domain/model/voltage-band';
import {button,element,escapeHtml as h} from '../../ui/components/dom';

type Tab='summary'|'bus'|'line'|'transformer'|'generator'|'loss'|'unmatched'|'topology';
type MetricKey=keyof ComparisonRow['metrics'];
const labels:Record<Tab,string>={summary:'Özet',bus:'Gerilim & Açı',line:'Hatlar',transformer:'Trafolar',generator:'Üreticiler',loss:'Kayıplar',unmatched:'Eşleşmeyenler',topology:'Topoloji farkı'};
const metricLabels:Record<string,string>={voltagePu:'V pu',voltageKv:'V kV',angleDeg:'Açı ham',alignedAngleDeg:'Açı hizalı',nominalKv:'Nominal kV',pFromMw:'P uç A',qFromMvar:'Q uç A',pToMw:'P uç B',qToMvar:'Q uç B',pHvMw:'YG P',qHvMvar:'YG Q',pLvMw:'AG P',qLvMvar:'AG Q',pLossMw:'P kaybı',qLossMvar:'Q kaybı',currentFromA:'I uç A',currentToA:'I uç B',currentHvA:'YG I',currentLvA:'AG I',loadingPercent:'Yüklenme',tapPosition:'Kademe',tapRatio:'Tap oranı',phaseShiftDeg:'Faz',pMw:'P',qMvar:'Q'};
const metricsByTab:Partial<Record<Tab,MetricKey[]>>={bus:['voltagePu','voltageKv','angleDeg','alignedAngleDeg'],line:['pFromMw','qFromMvar','pToMw','qToMvar','currentFromA','currentToA','loadingPercent'],transformer:['pHvMw','qHvMvar','pLvMw','qLvMvar','currentHvA','currentLvA','loadingPercent','tapPosition','tapRatio'],generator:['pMw','qMvar']};
const unitByMetric:Record<string,string>={voltagePu:'pu',voltageKv:'kV',angleDeg:'°',alignedAngleDeg:'°',nominalKv:'kV',pFromMw:'MW',pToMw:'MW',pHvMw:'MW',pLvMw:'MW',pMw:'MW',qFromMvar:'MVAr',qToMvar:'MVAr',qHvMvar:'MVAr',qLvMvar:'MVAr',qMvar:'MVAr',pLossMw:'MW',qLossMvar:'MVAr',currentFromA:'A',currentToA:'A',currentHvA:'A',currentLvA:'A',loadingPercent:'%',tapPosition:'',tapRatio:'pu',phaseShiftDeg:'°'};

export function createComparisonView(host:HTMLElement){
  let report:PowerFactoryComparison|null=null,preflight:ReferencePreflight|null=null,tab:Tab='summary',page=0,query='',band='all',ytm='all',tm='all',status='all',onlyDifferences=false,sort='hierarchy';
  const collapsed=new Set<string>(),hidden=new Set<string>();
  const tabs=element('div','ga-tabs-small'),filters=element('div','ga-comparison-filters'),body=element('div'),pager=element('div','ga-pager'),
    search=element('input'),voltage=element('select'),ytmSelect=element('select'),tmSelect=element('select'),matchSelect=element('select'),sortSelect=element('select'),only=element('input'),columns=element('div','ga-comparison-columns');
  search.type='search';search.placeholder='Ad veya FID ara';search.setAttribute('aria-label','Karşılaştırma ara');search.oninput=()=>{query=search.value.toLocaleLowerCase('tr-TR');page=0;draw();};
  voltage.setAttribute('aria-label','Gerilim filtresi');voltage.innerHTML='<option value="all">Tüm gerilimler</option><option value="400">400 kV</option><option value="220">220 kV</option><option value="154">154 kV</option><option value="66">66 kV</option><option value="low">≤36 kV</option>';voltage.onchange=()=>{band=voltage.value;page=0;draw();};
  ytmSelect.setAttribute('aria-label','YTM filtresi');ytmSelect.onchange=()=>{ytm=ytmSelect.value;page=0;draw();};tmSelect.setAttribute('aria-label','TM filtresi');tmSelect.onchange=()=>{tm=tmSelect.value;page=0;draw();};
  matchSelect.setAttribute('aria-label','Eşleşme durumu filtresi');matchSelect.innerHTML='<option value="all">Tüm eşleşmeler</option><option value="MATCHED">Eşleşen</option><option value="UNMATCHED_REFERENCE">PF eşleşmeyen</option><option value="UNMATCHED_ACTUAL">GA eşleşmeyen</option><option value="AMBIGUOUS">Belirsiz</option>';matchSelect.onchange=()=>{status=matchSelect.value;page=0;draw();};
  sortSelect.setAttribute('aria-label','Karşılaştırma sıralaması');sortSelect.innerHTML='<option value="hierarchy">YTM → TM → ekipman</option><option value="absolute">En büyük mutlak fark</option><option value="delta">En büyük fark</option><option value="name">Ekipman adı</option>';sortSelect.onchange=()=>{sort=sortSelect.value;page=0;draw();};
  only.type='checkbox';only.setAttribute('aria-label','Yalnız farklar');only.onchange=()=>{onlyDifferences=only.checked;page=0;draw();};const onlyLabel=element('label','ga-check');onlyLabel.append(only,document.createTextNode('Yalnız farklar'));
  for(const[key,label]of [['YTM','YTM'],['TM','TM'],...Object.entries(metricLabels).map(([k,v])=>[k,v] as [string,string])]){const checkbox=element('input');checkbox.type='checkbox';checkbox.checked=true;checkbox.onchange=()=>{if(checkbox.checked)hidden.delete(key);else hidden.add(key);draw();};const item=element('label','ga-check');item.append(checkbox,document.createTextNode(label));columns.append(item);}
  for(const [key,label]of Object.entries(labels) as [Tab,string][]) {const control=button(label,()=>{tab=key;page=0;draw();});control.dataset.compareTab=key;tabs.append(control);}
  filters.append(search,voltage,ytmSelect,tmSelect,matchSelect,sortSelect,onlyLabel);host.append(tabs,filters,columns,body,pager);
  const card=(label:string,value:unknown)=>`<div class="ga-card"><small>${h(label)}</small><strong>${h(value)}</strong></div>`;
  const table=(headers:string[],rows:string[][])=>`<div class="ga-table-wrap"><table class="ga-table"><thead><tr>${headers.map(x=>`<th>${h(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(value=>`<td>${value}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
  const note=(text:string)=>`<p class="ga-muted">${h(text)}</p>`;
  const number=(value:number|null|undefined)=>value==null||!Number.isFinite(value)?'—':value.toLocaleString('tr-TR',{minimumFractionDigits:1,maximumFractionDigits:1});
  function selectOptions(select:HTMLSelectElement,values:string[],title:string,current:string){select.innerHTML=`<option value="all">${h(title)}</option>`+values.sort((a,b)=>a.localeCompare(b,'tr')).map(value=>`<option value="${h(value)}">${h(value)}</option>`).join('');select.value=values.includes(current)?current:'all';}
  function setReport(next:PowerFactoryComparison|null,nextPreflight:ReferencePreflight|null){if(next!==report){report=next;const ytmValues=[...new Set(next?.rows.map(row=>row.hierarchy.ytm).filter((x):x is string=>!!x)||[])],tmValues=[...new Set(next?.rows.map(row=>row.hierarchy.tm).filter((x):x is string=>!!x)||[])];selectOptions(ytmSelect,ytmValues,'Tüm YTM',ytm);selectOptions(tmSelect,tmValues,'Tüm TM',tm);page=0;}preflight=nextPreflight;draw();}
  function visible(row:ComparisonRow){const name=`${row.gridAnalyzerId||''} ${row.powerFactoryFid||''} ${row.gridAnalyzerName||''} ${row.powerFactoryName||''}`.toLocaleLowerCase('tr-TR');return(!query||name.includes(query))&&(band==='all'||voltageBand(row.hierarchy.voltageKv||0)===band)&&(ytm==='all'||row.hierarchy.ytm===ytm)&&(tm==='all'||row.hierarchy.tm===tm)&&(status==='all'||row.status===status);}
  function paginate<T>(rows:T[]):T[]{const count=Math.max(1,Math.ceil(rows.length/50));page=Math.min(page,count-1);pager.append(button('Önceki',()=>{page=Math.max(0,page-1);draw();}),element('span','',`${rows.length.toLocaleString('tr-TR')} ekipman · ${page+1}/${count}`),button('Sonraki',()=>{page=Math.min(count-1,page+1);draw();}));(pager.firstChild as HTMLButtonElement).disabled=page===0;(pager.lastChild as HTMLButtonElement).disabled=page>=count-1;return rows.slice(page*50,page*50+50);}
  function rowMetrics(row:ComparisonRow):MetricKey[]{if(tab==='loss')return ['pLossMw','qLossMvar'];return metricsByTab[tab]||[];}
  function diffMagnitude(row:ComparisonRow){return Math.max(0,...rowMetrics(row).map(key=>row.metrics[key]?.absoluteDelta??0));}
  function draw(){tabs.querySelectorAll<HTMLButtonElement>('button').forEach(control=>control.setAttribute('aria-pressed',String(control.dataset.compareTab===tab)));body.replaceChildren();pager.replaceChildren();filters.hidden=tab==='summary'||tab==='topology';columns.hidden=filters.hidden||tab==='unmatched';if(!report){body.textContent='PowerFactory referansı yükleyin.';return;}
    const blocked=report.compatibility.status==='BLOCKED'||preflight?.status==='BLOCKED';
    if(tab==='summary'){const p=preflight;body.innerHTML=`<div class="ga-card-grid">${card('Uyumluluk',blocked?'Bloklandı':'Doğrulandı')}${card('Eşleşen ekipman',report.summary.matchedTotal)}${card('PF eşleşmeyen',report.summary.unmatchedReference)}${card('Belirsiz',report.summary.ambiguousReference)}${card('PF bara değer çelişkisi',report.referenceValueConflicts.length)}${card('Elektriksel bara',p?.topology.electricalBusesChecked??'—')}${card('Dal uçları',p?.topology.branchEndpointsChecked??'—')}</div>`;
      if(blocked)body.innerHTML+=`<p class="ga-notice">${h([...(p?.reasons||[]),...report.compatibility.reasons].join(' · '))}</p>`;else body.innerHTML+=`<p class="ga-muted">${h(p?.topology.physicalTerminalsChecked)} aktif terminal doğrulandı · ${h(p?.topology.inactiveStubTerminals)} enjeksiyonsuz uç hesap grafiğinde yok · study time ${h(p?.studyTimeProvenance==='STUDY_CASE_NAME'?'study case adından':'doğrulanamadı')}</p>`;
      body.innerHTML+=table(['Ekipman','Metrik','N','Fark','Mutlak fark','En büyük fark','Birim'],report.metrics.map(row=>[h(labels[row.kind as Tab]||row.kind),h(metricLabels[row.metric]||row.metric),h(row.count),number(row.meanBias),number(row.mae),number(row.maxAbsoluteError),h(row.unit)]));body.innerHTML+=note('PF c:loading yalnız eşdeğer akım ve rating semantiği doğrulanınca karşılaştırılır. Ham açı saklanır; hizalı açı ada referansı veya medyan ofsetle gösterilir.');return;}
    if(tab==='topology'){const p=preflight;body.innerHTML=p?table(['Kontrol','Değer'],[['Durum',h(p.status)],['Model',h(p.context.modelId)],['Study case',h(p.context.studyCase)],['Study time',h(p.context.studyTime)],['Elektriksel bara grubu',h(p.topology.electricalBusesChecked)],['Fiziksel terminal',h(p.topology.physicalTerminalsChecked)],['Aktif olmayan eksik terminal',h(p.topology.inactiveStubTerminals)],['Dal ucu',h(p.topology.branchEndpointsChecked)],['Dal uç farkı',h(p.topology.branchEndpointConflicts)]]):note('PF topoloji bilgisi yok.');return;}
    if(tab==='unmatched'){const all=report.rows.filter(row=>row.status!=='MATCHED'&&visible(row));body.innerHTML=table(['Durum','Sınıf','Ekipman','Eşleşme yöntemi','YTM','TM','kV'],paginate(all).map(row=>[h(row.status),h(row.kind),h(row.powerFactoryName||row.gridAnalyzerName),h(row.matchMethod||'—'),h(row.hierarchy.ytm||'—'),h(row.hierarchy.tm||'—'),number(row.hierarchy.voltageKv)]));return;}
    let rows=report.rows.filter(row=>row.status==='MATCHED'&&visible(row)&&(tab==='loss'?(row.kind==='line'||row.kind==='transformer'):row.kind===tab));if(onlyDifferences)rows=rows.filter(row=>rowMetrics(row).some(key=>(row.metrics[key]?.absoluteDelta??0)>1e-6));
    if(sort==='absolute')rows.sort((a,b)=>diffMagnitude(b)-diffMagnitude(a));else if(sort==='delta')rows.sort((a,b)=>Math.max(...rowMetrics(b).map(k=>b.metrics[k]?.delta??-Infinity))-Math.max(...rowMetrics(a).map(k=>a.metrics[k]?.delta??-Infinity)));else if(sort==='name')rows.sort((a,b)=>(a.gridAnalyzerName||a.powerFactoryName||'').localeCompare(b.gridAnalyzerName||b.powerFactoryName||'','tr'));else rows.sort((a,b)=>`${a.hierarchy.ytm||''}|${a.hierarchy.tm||''}|${a.gridAnalyzerName||a.powerFactoryName||''}`.localeCompare(`${b.hierarchy.ytm||''}|${b.hierarchy.tm||''}|${b.gridAnalyzerName||b.powerFactoryName||''}`,'tr'));
    const selected=paginate(rows),visibleMetrics=[...new Set(selected.flatMap(rowMetrics))].filter(key=>!hidden.has(key)),includeYtm=!hidden.has('YTM'),includeTm=!hidden.has('TM'),baseHeaders=[...(includeYtm?['YTM']:[]),...(includeTm?['TM']:[]),'Ekipman',...(tab==='generator'?['GA Q durumu','PF kontrol modu','Bara eşleşmesi']:[])],headerCells=baseHeaders.map(x=>`<th rowspan="2">${h(x)}</th>`).join('')+visibleMetrics.map(key=>`<th colspan="5">${h(metricLabels[key]||key)}${unitByMetric[key]?` <small>(${h(unitByMetric[key])})</small>`:''}</th>`).join(''),subHeaders=visibleMetrics.flatMap(()=>['Grid Analyzer','PowerFactory','Fark','Mutlak fark','Fark %']).map(x=>`<th>${h(x)}</th>`).join('');
    let previousGroup='';const groups=new Map<string,number>(),bodyRows=selected.map(row=>{const group=`${row.hierarchy.ytm||'—'} / ${row.hierarchy.tm||'—'}`,newGroup=sort==='hierarchy'&&group!==previousGroup;previousGroup=group;let groupHeader='';if(newGroup){const index=groups.size;groups.set(group,index);groupHeader=`<tr class="ga-comparison-group"><th colspan="${baseHeaders.length+visibleMetrics.length*5}"><button type="button" class="ga-button" data-compare-group="${index}" aria-expanded="${!collapsed.has(group)}">${collapsed.has(group)?'▸':'▾'} ${h(group)}</button></th></tr>`;}if(sort==='hierarchy'&&collapsed.has(group))return groupHeader;const equipment=row.gridAnalyzerName||row.powerFactoryName||'—',values=[...(includeYtm?[row.hierarchy.ytm||'—']:[]),...(includeTm?[row.hierarchy.tm||'—']:[]),equipment,...(tab==='generator'?[row.generatorControl?.gridAnalyzerQState||'—',row.generatorControl?.powerFactoryControlModeRaw||'—',row.generatorControl?.busMatch||'—']:[])];for(const key of visibleMetrics){const pair=row.metrics[key];values.push(number(pair?.gridAnalyzer),number(pair?.powerFactory),pair?.comparable?number(pair.delta):'—',pair?.comparable?number(pair.absoluteDelta):'—',pair?.comparable?number(pair.deltaPercent):'—');}return groupHeader+`<tr>${values.map(value=>`<td>${h(value)}</td>`).join('')}</tr>`;}).join('');
    const lossSummary=tab==='loss'?table(['Ekipman','Metrik','Fark','Mutlak fark','En büyük fark','Birim'],report.metrics.filter(metric=>(metric.kind==='line'||metric.kind==='transformer')&&(metric.metric==='pLossMw'||metric.metric==='qLossMvar')).map(metric=>[h(labels[metric.kind]),h(metricLabels[metric.metric]),number(metric.meanBias),number(metric.mae),number(metric.maxAbsoluteError),h(metric.unit)])):'';
    body.innerHTML=lossSummary+`<div class="ga-table-wrap ga-comparison-equipment-wrap"><table class="ga-table ga-comparison-equipment"><thead><tr>${headerCells}</tr><tr>${subHeaders}</tr></thead><tbody>${bodyRows||`<tr><td colspan="${baseHeaders.length+visibleMetrics.length*5}" class="ga-empty">Bu filtrelerde kayıt yok.</td></tr>`}</tbody></table></div>${rows.length?note('Her satır bir ekipmanı gösterir. Sayısal düzen: Grid Analyzer | PowerFactory | Fark | Mutlak fark | Fark %. Akım karşılaştırması yalnız iki kaynakta da ölçüm varsa yapılır.') : ''}`;
    body.querySelectorAll<HTMLButtonElement>('[data-compare-group]').forEach(control=>control.onclick=()=>{const group=[...groups.keys()][Number(control.dataset.compareGroup)];if(collapsed.has(group))collapsed.delete(group);else collapsed.add(group);draw();});
  }
  return{render:setReport,selectedTab:()=>tab};
}
