import type {AppContext} from '../../app/contracts';
import type {CanonicalNetwork} from '../../domain/model/network';
import {effectiveNetwork,scenarioChanged} from '../../domain/scenario/overlay';
import {buildTopology} from '../../topology/electrical-topology';
import {buildSplitBusTopology,type SplitBusTopology} from '../../topology/split-bus';
import type {ReferencePreflight} from '../../analysis/validation/powerfactory-preflight';
import {button,element,escapeHtml as h} from '../../ui/components/dom';

type Section='islands'|'split'|'buses'|'terminals'|'branches'|'blocked'|'difference'|'pf';
const labels:Record<Section,string>={islands:'Gerçek elektriksel adalar',split:'154 kV Ayrık Bara / Yarı Ada',buses:'Elektriksel bara eşdeğerleri',terminals:'Fiziksel terminal → elektriksel bara',branches:'Dal uçları',blocked:'Bloke ekipman',difference:'Baz / senaryo farkı',pf:'PF topoloji karşılaştırması'};

export function createTopologyView(ctx:AppContext,host:HTMLElement){
  let source:CanonicalNetwork|null=null,revision=-1,base:SplitBusTopology|null=null,scenario:SplitBusTopology|null=null,active:Section='islands',query='',page=0,currentPreflight:ReferencePreflight|null=null;
  const tabs=element('div','ga-tabs-small'),body=element('div'),search=element('input'),pager=element('div','ga-pager');search.type='search';search.placeholder='YTM, TM, bara veya FID ara';search.setAttribute('aria-label','Topoloji kayıtlarında ara');search.oninput=()=>{query=search.value.toLocaleLowerCase('tr-TR');page=0;render();};
  for(const [key,label] of Object.entries(labels) as [Section,string][]) {const tab=button(label,()=>{active=key;page=0;render();});tab.dataset.section=key;tabs.append(tab);}
  host.append(tabs,search,body,pager);
  const siteById=()=>new Map((ctx.network?.sites||[]).map(site=>[site.id,site]));
  const table=(headers:string[],rows:(string|number)[][])=>`<div class="ga-table-wrap"><table class="ga-table"><thead><tr>${headers.map(x=>`<th>${h(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(value=>`<td>${h(value)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
  function render(preflight?:ReferencePreflight|null){if(preflight!==undefined)currentPreflight=preflight;const n=ctx.network;if(!n){body.textContent='Model yüklenmedi.';return;}if(source!==n||revision!==ctx.scenario.revision){source=n;revision=ctx.scenario.revision;base=buildSplitBusTopology(n);scenario=scenarioChanged(ctx.scenario.current)?buildSplitBusTopology(effectiveNetwork(n,ctx.scenario.current)):null;}
    const data=scenario&&ctx.resultStore.role==='scenario'?scenario:base!;const sites=siteById();tabs.querySelectorAll<HTMLButtonElement>('button').forEach(tab=>tab.setAttribute('aria-pressed',String(tab.dataset.section===active)));search.hidden=['difference','pf'].includes(active);body.replaceChildren();pager.replaceChildren();
    const unsupplied=data.islands.filter(row=>!row.referencePresent).length,splitSites=new Set(data.splitStations.map(row=>row.siteId).filter(Boolean)).size;
    const cards=element('div','ga-card-grid');for(const [label,value] of [['Elektriksel bara',data.electricalBusIslandIds.size],['Gerçek ada',data.islands.length],['Referanssız ada',unsupplied],['Ayrık 154 kV TM',splitSites],['Açık kuplaj',data.splitStations.length]] as const)cards.innerHTML+=`<div class="ga-card"><small>${h(label)}</small><strong>${h(value)}</strong></div>`;body.append(cards);
    const fit=(value:unknown)=>String(value??'').toLocaleLowerCase('tr-TR').includes(query);const pageRows=<T,>(rows:T[]):T[]=>{const pages=Math.max(1,Math.ceil(rows.length/50));page=Math.min(page,pages-1);pager.append(button('Önceki',()=>{page=Math.max(0,page-1);render(preflight);}),element('span','',`${rows.length} kayıt · ${page+1}/${pages}`),button('Sonraki',()=>{page=Math.min(pages-1,page+1);render(preflight);}));(pager.firstChild as HTMLButtonElement).disabled=page===0;(pager.lastChild as HTMLButtonElement).disabled=page>=pages-1;return rows.slice(page*50,page*50+50);};
    if(active==='islands'){const rows=data.islands.filter(island=>fit(island.islandId)||island.siteIds.some(id=>fit(sites.get(id)?.name)||fit(sites.get(id)?.areaName)));body.innerHTML+=table(['Ada','Sınıf','Referans','Besleme','Bara','Dal','YTM / TM'],pageRows(rows).map(island=>[island.islandId,island.classification,island.referenceSourceIds.join(', ')||'Yok',island.referencePresent?'Var':'Yok',island.busCount,island.branchCount,island.siteIds.slice(0,8).map(id=>`${sites.get(id)?.areaName||'—'} / ${sites.get(id)?.name||id}`).join(' · ')+(island.siteIds.length>8?' …':'')]));}
    else if(active==='split'){const rows=data.splitStations.filter(row=>fit(row.siteName)||fit(row.couplerId)||fit(row.bus1.busName)||fit(row.bus2.busName)||fit(sites.get(row.siteId||'')?.areaName));body.innerHTML+=`<p class="ga-muted">Açık kuplaj iki barayı ayırır; yan şebeke üzerinden bağlantı sürüyorsa gerçek ada değildir. Adlandırma veya TM bağı belirsizse sonuç heuristic olarak işaretlenir.</p>`+table(['YTM','TM','kV','Bara-1','Bara-2','Kuplaj FID','Durum','Fider B1/B2','Upstream / downstream','Sınıf / güven'],pageRows(rows).map(row=>[sites.get(row.siteId||'')?.areaName||'—',row.siteName||'—',row.voltageKv,row.bus1.busName+' ('+row.bus1.barDesignation+')',row.bus2.busName+' ('+row.bus2.barDesignation+')',row.couplerId,row.couplerClosed?'Kapalı':'Açık',`${row.bus1.feederCount} / ${row.bus2.feederCount}`,row.topologyRelation==='SAME_COMPONENT_VIA_ALTERNATE_PATH'?'Şebeke üzerinden alternatif yol':'Ayrı bağlı bileşen',`${row.classification} · ${row.confidence}${row.heuristic?' · heuristic':''}`]));}
    else if(active==='buses'){const electrical=buildTopology(scenario&&ctx.resultStore.role==='scenario'?effectiveNetwork(n,ctx.scenario.current):n);const rows=electrical.buses.filter(row=>fit(row.id)||fit(row.name)||row.siteIds.some(id=>fit(sites.get(id)?.name)));body.innerHTML+=table(['Elektriksel bara','Ad','kV','Fiziksel terminal sayısı','TM','Ada'],pageRows(rows).map(row=>[row.id,row.name,row.vnKv,row.terms.length,row.siteIds.map(id=>sites.get(id)?.name||id).join(', '),data.electricalBusIslandIds.get(row.id)?.join(', ')||'—']));}
    else if(active==='terminals'){const terminalById=new Map(n.buses.map(row=>[row.id,row]));const rows=[...data.terminalToElectricalBus].filter(([id,bus])=>fit(id)||fit(bus)||fit(terminalById.get(id)?.name));body.innerHTML+=table(['Fiziksel terminal FID','Ad','Elektriksel bara','TM'],pageRows(rows).map(([id,bus])=>[id,terminalById.get(id)?.name||'—',bus,terminalById.get(id)?.siteIds.map(site=>sites.get(site)?.name||site).join(', ')||'—']));}
    else if(active==='branches'){const rows=[...n.lines,...n.transformers,...n.seriesCompensators].filter(row=>fit(row.id)||fit(row.name)||fit(row.from)||fit(row.to));body.innerHTML+=table(['FID','Ekipman','Uç A','A elektriksel bara','Uç B','B elektriksel bara','Durum'],pageRows(rows).map(row=>[row.id,row.name,row.from,data.terminalToElectricalBus.get(row.from)||'—',row.to,data.terminalToElectricalBus.get(row.to)||'—',row.inService?'Serviste':'Servis dışı']));}
    else if(active==='blocked'){const electrical=buildTopology(scenario&&ctx.resultStore.role==='scenario'?effectiveNetwork(n,ctx.scenario.current):n),rows=[...electrical.blockedEquipment].filter(fit);body.innerHTML+=table(['Bloke ekipman FID','Neden'],pageRows(rows).map(id=>[id,'Açık StaSwitch veya servis dışı bağlantı']));}
    else if(active==='difference'){const before=base!,after=scenario,changed=[...Object.entries(ctx.scenario.current.lineStatus),...Object.entries(ctx.scenario.current.transformerStatus),...Object.entries(ctx.scenario.current.switchState),...Object.entries(ctx.scenario.current.busOrTerminalStatus)];body.innerHTML+=`<p class="ga-muted">${after?'Senaryo topolojisi hesaplandı.':'Aktif topoloji senaryosu yok.'}</p>`+table(['Ölçü','Baz','Senaryo'],[['Gerçek ada',before.islands.length,after?.islands.length??before.islands.length],['Referanssız ada',before.islands.filter(row=>!row.referencePresent).length,after?.islands.filter(row=>!row.referencePresent).length??before.islands.filter(row=>!row.referencePresent).length],['154 kV açık ayrık kuplaj',before.splitStations.length,after?.splitStations.length??before.splitStations.length],['Senaryoda değişen ekipman',0,changed.length]]);}
    else {const p=currentPreflight;body.innerHTML+=p?`<p class="ga-notice">${p.status==='COMPATIBLE'?'PF topolojisi eşleşti.':h(p.reasons.join(' · '))}</p>`+table(['Kontrol','Sonuç'],[['Fiziksel terminal eşleşmesi',p.topology.physicalTerminalsChecked],['Elektriksel bara grubu',p.topology.electricalBusesChecked],['Dal uçları',p.topology.branchEndpointsChecked],['Eksik terminal',p.topology.missingTerminals],['Bara bölünme / birleşme farkı',p.topology.busPartitionConflicts],['Eksik dal',p.topology.missingBranches],['Dal uç farkı',p.topology.branchEndpointConflicts]]):'<p>PF referansı yüklenmedi.</p>';}
  }
  return{render};
}
