export interface HelpEntry {id:string;title:string;shortText:string;fullText:string;section:string;relatedScreen:string;relatedField:string;tags:readonly string[];methodCaveat?:string}
function entry(id:string,title:string,shortText:string,fullText:string,screen:string,methodCaveat?:string):HelpEntry{return {id,title,shortText,fullText,section:id.split('.')[0],relatedScreen:screen,relatedField:id,tags:[id.split('.')[0],title],methodCaveat};}
export const helpRegistry:readonly HelpEntry[]=[
  entry('compare.scorecard','PF–GA doğruluk karnesi','Her analiz, kV, ekipman ve metrik ayrı değerlendirilir. MAE, P95 ve maksimum hata aynı birimle gösterilir.','Her analiz, kV, ekipman ve metrik ayrı değerlendirilir. MAE, P95 ve maksimum hata aynı birimle gösterilir.','comparison'),
  entry('compare.coverage','Sayısal eşleşme kapsamı','Kapsam = kimliği ve sayısı eşleşen çift / uygun PF kayıtları × 100. Eksik sayılar ve dışlanma nedenleri ayrıca gösterilir.','Kapsam = kimliği ve sayısı eşleşen çift / uygun PF kayıtları × 100. Eksik sayılar ve dışlanma nedenleri ayrıca gösterilir.','comparison'),
  entry('compare.tolerance','Mühendislik toleransı','GA-ENGINEERING-1.0: P/Q/S için 1 birim + %1 |PF|; V için 0.5 kV veya 0.005 pu + %0.5 |PF|. Standart uygunluk sertifikası değildir.','GA-ENGINEERING-1.0: P/Q/S için 1 birim + %1 |PF|; V için 0.5 kV veya 0.005 pu + %0.5 |PF|. Standart uygunluk sertifikası değildir.','comparison'),
  entry('compare.identity','Kimlik ve uç eşleşmesi','StudyCase, model, senaryo, FID, uç, yön, nominal gerilim, partition ve yöntem kapıları aynı çift için geçmelidir.','StudyCase, model, senaryo, FID, uç, yön, nominal gerilim, partition ve yöntem kapıları aynı çift için geçmelidir.','comparison'),
  entry('compare.parity','Yöntem ve parite','LF tanısal karşılaştırmadır. N-1 PF post-case eksikse ve SC IEC/partition doğrulanmadıysa tolerans içi oran HESAPLANAMAZ.','LF tanısal karşılaştırmadır. N-1 PF post-case eksikse ve SC IEC/partition doğrulanmadıysa tolerans içi oran HESAPLANAMAZ.','comparison'),
  entry('compare.versionTrend','Sürümler arası ölçüm','Gerçek önceki karne, farklı Git SHA ve aynı model, referans, ayar, ControlContext, tolerans gerekir. Önceki kayıt yoksa gelişme yüzdesi üretilmez.','Gerçek önceki karne, farklı Git SHA ve aynı model, referans, ayar, ControlContext, tolerans gerekir. Önceki kayıt yoksa gelişme yüzdesi üretilmez.','comparison'),
  entry('map.scenarioDelta','GA senaryo farkı','GA senaryo − GA referans ve GA − PF ayrı kaynaklardır.','B0/S1/S2 farkı yalnız aynı model/motor/ayar ve bire bir elektriksel terminal partition ile hesaplanır. PF yöntem veya kimlik doğrulanmadıysa sertifikalı PF farkı null kalır.','map'),
  entry('map.voltage.400','400 kV katmanı','400 kV nominal gerilimli ekipmanı gösterir; hesap kapsamını değiştirmez.','Gerilim nominal kaynak değerinden sınıflanır. Sonucu olmayan veya stale ekipman gri kalır; görünüm filtresi elektriksel şebekeyi kesmez.','map'),
  entry('map.voltage.220','220 kV katmanı','220 kV nominal gerilimli ekipmanı gösterir; hesap kapsamını değiştirmez.','Gerilim nominal kaynak değerinden sınıflanır. Sonucu olmayan veya stale ekipman gri kalır; görünüm filtresi elektriksel şebekeyi kesmez.','map'),
  entry('map.voltage.154','154 kV katmanı','154 kV nominal gerilimli ekipmanı gösterir; hesap kapsamını değiştirmez.','Gerilim nominal kaynak değerinden sınıflanır. Sonucu olmayan veya stale ekipman gri kalır; görünüm filtresi elektriksel şebekeyi kesmez.','map'),
  entry('map.voltage.66','66 kV katmanı','66 kV nominal gerilimli ekipmanı gösterir; hesap kapsamını değiştirmez.','Gerilim nominal kaynak değerinden sınıflanır. Sonucu olmayan veya stale ekipman gri kalır; görünüm filtresi elektriksel şebekeyi kesmez.','map'),
  entry('map.voltage.low','≤36 kV katmanı','≤36 kV nominal gerilimli ekipmanı gösterir; hesap kapsamını değiştirmez.','Gerilim nominal kaynak değerinden sınıflanır. Sonucu olmayan veya stale ekipman gri kalır; görünüm filtresi elektriksel şebekeyi kesmez.','map'),
  entry('map.flow','Akış okları','P/Q yönünü gösterir; hareket fiziksel hız değildir.','P/Q yönünü gösterir; hareket fiziksel hız değildir. Hesap ve kaynak kimliği korunur.','map'),
  entry('map.sites','Trafo merkezleri','Coğrafi TM işaretleri elektriksel bara birleşimi değildir.','Coğrafi TM işaretleri elektriksel bara birleşimi değildir. Hesap ve kaynak kimliği korunur.','map'),
  entry('map.labels','Harita etiketleri','Yakın zoomda ekipman adlarını gösterir.','Yakın zoomda ekipman adlarını gösterir. Hesap ve kaynak kimliği korunur.','map'),
  entry('map.route','Sade güzergâh','Coğrafi çizgiyi sadeleştirir; elektriksel bağlantıyı değiştirmez.','Coğrafi çizgiyi sadeleştirir; elektriksel bağlantıyı değiştirmez. Hesap ve kaynak kimliği korunur.','map'),
  entry('model.modelHash','Model kimliği','Tek aktif model kullanılır; model değişince referanslar ve sonuçlar temizlenir.','GA modelHash JSON baytlarının SHA-256 değeridir. PF exporter yapısal hash algoritması farklı olabilir; aynı StudyCase adı tek başına sayısal pariteyi kanıtlamaz. ZIP içinden bir DGS JSON seçilir; dosyalar yerel tarayıcıda işlenir.','model'),
  entry('model.quality','Model kalitesi','Denetim kaynak modeli değiştirmez. Baz ve senaryo kapsamını seçin.','Topoloji, elektrik verisi, kapasite, controller, indirgenmiş model ve provenans bulgularını önem, kategori, kV ve grup ile filtreleyin. Arama, sıralama, sayfalama ve CSV/JSON tüm bulgulara erişim sağlar. Uyarı yokluğu hesap doğruluğunu kanıtlamaz.','model'),
  entry('lf.fullAc','Yük akışı yöntemi','Tam AC tüm kV seviyelerini çözer. Hızlı AC ve DC 66 kV+ yaklaşımıdır.','Tam AC Full Newton–Raphson, PV/PQ, Q sınırları, snapshot tapları ve ayrı referanslı adaları kullanır. DC yalnız P/açı üretir; Q ve gerilim büyüklüğü boş kalır. Baz, senaryo ve Senaryo Δ sonuçları bağımsız kimlikle tutulur. XLSX/CSV sonuç panelindedir.','analysis:LF','DC sonuçları AC doğrulaması değildir.'),
  entry('lf.convergence','Newton bütçesi ve tolerans','Yakınsama bütçe ve P/Q artığına bağlıdır; daha büyük bütçe doğruluk kanıtı değildir.','İç/outer Newton iterasyonu, nodal kVA toleransı, model denklem toleransı, stagnation ve aktif denge düzeltmeleri ayrı bütçelerdir. Sonuç tanısı gerçek iterasyon, aktif-set turu ve faktorizasyon sayılarını gösterir.','analysis:LF'),
  entry('lf.qLimits','Q limitleri','Q sınırları PV→PQ geçişlerini etkiler.','Reaktif sınırlar etkinse Q limit aktif-set turları ve toleransı kullanılır. Limitlere ulaşmış üreticinin gerilim kontrolü sınırlanır. Sonuçlarda Q durumu ve tanı turları incelenebilir.','analysis:LF'),
  entry('lf.stationControlMode','İstasyon kontrolü','Droop, zeroDroop ve off farklı varsayımlardır; destek kanıtı gerekir.','Station Controller kaynak alanları korunur. Seçilen mod ve aktif dengelemenin support/fidelity tanıları incelenmelidir. Droop desteklenemiyorsa BLOCKED kalabilir; off kontrol sadakatini düşürür ve PF paritesi sağlamaz.','analysis:LF','Off yaklaşımı NOT_PF_PARITY olabilir.'),
  entry('lf.voltageBand','Gerilim ve sonuç kapsamı','Görüntü filtresi şebekeyi silmez; hesap yöntemi kendi kapsamını belirler.','YTM/TM ve gerilim filtresi sonuçları daraltır. Baz/Senaryo/Δ kaynağı ile Tam AC/Hızlı AC/DC sonuç türü bağımsız seçilir. Boş veya stale değerler sıfır sayılmaz.','analysis:LF'),
  entry('n1.dcScreen','DC N-1 taraması','DC PTDF/LODF P-only taramadır; ada ayıran veya taranamayan aday güvenli sayılmaz.','Hat/trafo, YTM/TM/kV ve taranabilirlik kataloğunu filtreleyin; filtredekileri veya tüm adayları seçin. Senaryolar, yüklenmeler, ada/kayıp ve kritik kısıtlar özgün sonuç alt sekmelerinde korunur.','analysis:N1'),
  entry('n1.scope','N-1 kapsamı','YTM/TM/kV ve uç kapsamı kesinti adaylarını seçer; bağlı şebeke korunur.','Boş çoklu seçim tüm kapsamı temsil eder. Küme içi, sınır, aynı YTM içi ve belirsiz uç kapsamı native site/area ilişkilerinden çıkarılır. Eksik uç bilgisi sessizce doğrulanmaz.','analysis:N1'),
  entry('n1.dcPromotion','AC promosyon politikası','DC %90 promosyon kullanıcı politikasıdır; %100 işletme limiti değildir.','DC aşımı, eksik rating, taranamayan, ada ayıran, açık seçim ve temiz vaka örneği Full AC kuyruğunu belirler. Eşik ve örnek sayısı gelişmiş ayarlardadır.','analysis:N1'),
  entry('n1.acBudget','AC vaka ve zaman bütçesi','Bütçe dışı vaka NOT_RUN_BUDGET; güvenli sayılmaz.','Vaka sayısı, vaka timeout ve global timeout ayrıdır. AC eşzamanlılığı 1. Durdur workerı sonlandırır; devam aynı model/senaryo/ayar/politika kimliği ile checkpoint üzerinden sürer. Kimlik değişince sonuç stale olur.','analysis:N1'),
  entry('n1.voltageLimits','AC işletme limitleri','0.90–1.10 Vpu ve yük limiti yalnız AC sonrasında uygulanır.','Gerilim ve termik sınırlar kullanıcı işletme profilidir. Limit aşımları sonuç durumlarını etkiler; DC akışını AC gerilim aşımı diye sunmayın.','analysis:N1'),
  entry('n1.ratingBasis','Rating ve mevsim','Eksik kapasite UNKNOWN; sıfır yüklenme değildir.','Nominal/yaz/kış/işletme ratingi ve akım/görünür güç bazı provenansta saklanır. Farklı rating temelleri yüklenme yüzdesi karşılaştırması için uyumlu olmalıdır.','analysis:N1'),
  entry('n1.studyProfile','Hibrit kontrol profili','CURRENT_SETTINGS destek ister. GA_APPROX_STATION_OFF açık yaklaşım seçimidir.','Profil kontrol sadakatini belirler; off yaklaşımı distributed active balancing desteğini kaldırmaz. CONTROL_FIDELITY_PARTIAL ve NOT_PF_PARITY tanıları sonuç/export içinde korunur.','analysis:N1'),
  entry('n1.constraintState','Kısıt değişim durumu','NEW/WORSENED/PERSISTENT/RELIEVED/UNKNOWN baz ve post sonuçlarına bağlıdır.','Yeni ihlal, kötüleşen ihlal, süren ihlal ve rahatlayan kısıt ayrıdır. Eksik baz/post/rating UNKNOWN kalır. Ada beslemesiz yük, termik ve gerilim kısıtları birlikte incelenir; PARTIAL_SOLUTION güvenlik kanıtı değildir.','analysis:N1'),
  entry('sc.faultMode','3PH MAX / MIN','MAX ve MIN farklı açık c profilleri kullanır. 1LG/LL/2LG desteklenmez.','YTM/TM/kV ve fiziksel terminal FID ile 3PH fault seçin. Native kaynak eksikse BLOCKED. Ikss/Skss hesaplanabilir; doğrulanmamış Ip/Ib/Ith null korunur. MAX referansı MIN hesabına eşlenmez.','analysis:SC','IEC kanıtı yoksa IEC_PASS verilmez.'),
  entry('sc.networkApproximation','Açık kaynak varsayımları','NETWORK_APPROXIMATION açık onay ister; IEC paritesi değildir.','Gelişmiş panelde approximation kutusunu etkinleştirin; varsayım kaynağını yazın. R/X override native sınıf+FID ve ohm ile girilir. Nominal baz normalizasyonu ayrıca onaylanır. Kaynak eksikleri audit ile gösterilir; PF değeri GA girdisi yapılmaz.','analysis:SC','CALCULATED_NETWORK_APPROXIMATION ≠ IEC_PASS.'),
  entry('sc.machineXdss','Makine R / X varsayımı','Eksik makine pu varsayımı ayrıca onay ister.','xdss ve r pu yalnız native R/X eksikliği için kullanıcı açıklamasıyla kullanılır. Konverter akım açısı ve bağlı terminal bazı açık approximation kapsamındadır. Adaptör audit provenansı export edilir.','analysis:SC'),
  entry('sc.externalGridFactor','Dış kaynak c ve fault c','c_source ile c_fault ayrı varsayımlardır; IEC doğrulaması sayılmaz.','MAX/MIN profilleri c değerlerini saklar. Fault ve zaman bütçesi kısmi kapsamı sınırlar. Dış kaynak R/X veya konverter katkısı eksikse engel nedeni korunur.','analysis:SC'),
  entry('sc.partition','Fiziksel / elektriksel bara','Fiziksel terminal, elektriksel bara ve cihaz kaydı farklıdır.','Kapalı anahtar elektriksel birleşim oluşturabilir. PF partition üyelikleri doğrulanmadığında SC sertifikalı Δ null kalır. Fault×device katkı eksikliği sıfır katkı değildir.','analysis:SC'),
  entry('compare.referencePackage','Referans paketleri','Aktif modele LF/N-1/SC üçlü ZIP veya birleşik dokuz dosya ekleyin.','Her analiz XLSX + referans JSON + LOG içerir. Workbook SHA/size, manifest, exporter ve log StudyCase doğrulanır. Yuvalar bağımsızdır; hata yeni paketi atomik reddeder. Farklı StudyCase veya exporter model/scenario/topology hash karışımı reddedilir. Model değişimi yuvaları temizler. Referans ekleme GA sonuçlarını değiştirmez. Eski JSON/CSV ve açık ControlContext ayrı paneldedir; ControlContext hesapları geçersiz kılar.','comparison'),
  entry('compare.methodGate','Karşılaştırma metot kapıları','Kimlik, yöntem veya rating doğrulanmadıysa sertifikalı Δ null kalır.','LF EXPLORATORY_ONLY, eksik N-1 PF post-case ve eksik SC partition kapıları aşılmaz. Boş NOT_RECORDED; sıfır RECORDED_NUMERIC_ZERO. GA sonucu eksikse Analizler ekranına gidin; karşılaştırma hesap çalıştırmaz.','comparison'),
  entry('compare.diagnosticDelta','Tanısal fark','Tanısal Δ açık seçilir; metot paritesi değildir.','Kaynak kimliği doğrulanıp metot kanıtı eksikse EXPLORATORY_DELTA_METHOD_UNVERIFIED gösterilebilir. Scatter/histogram, tablo, export ve harita kimlik/metrik kapılarını korur. Sertifikalı fark null kalır.','comparison'),
  entry('compare.staleGaResult','Güncel / stale sonuç','Model, senaryo veya ayar değişince eski GA sonucu fark üretmez.','Kimlik modelHash, scenarioHash ve ayar/politika profilini taşır. Ekran geçişi hesabı durdurmaz. Referans ekleme yeniden hesaplamaz; güncel GA sonucu varsa eşleme yenilenir.','comparison'),
  entry('compare.filters','Referans filtreleri ve export','FID/ad/vaka, YTM/TM/kV ve durum filtreleri listeyi daraltır; hesap çalıştırmaz.','Ham tablo veya tek metrik seçin. Kaynak, FID, ad, PF değer ya da mutlak fark sıralaması kullanılabilir. Tanısal fark seçilmedikçe doğrulanmamış Δ sıralamaya dahil edilmez. Sayfalama ekrandaki kayıtları sınırlar; CSV/XLSX/JSON filtreli listenin tamamını ve kaynak provenansını dışa aktarır.','comparison'),
  entry('inventory.filter','Envanter ve işletme','Sınıf, YTM/TM, gerilim ve arama listeyi filtreler.','Şebeke Envanteri kaynak alanlarını gösterir. İşletme Verileri servis durumunu senaryo overlay içinde değiştirir; kaynak JSON değişmez. Geri al ve sıfırla önceki/kaynak duruma döndürür. Değiştir + hesapla güncel sonuç üretir.','inventory'),
  entry('map.display','Harita ve tek hat','Gri renk geçerli sonuç yokluğunu gösterebilir; sıfır değildir.','Harita → Elektriksel Sonuçlar ile hat/trafo/bara listesinden servis değişikliklerini inceleyin. Devreye Alma bağlantı engellerini gösterir. Tek Hat Şeması TM/fider bağlantılarını açar. Kesikli çizgi servis dışıdır; açı haritası filtreli TM medyanı ve ada referansına bağlıdır. Akış okları fiziksel hız değildir.','map'),
  entry('settings.display','Görünüm ayarları','Tema, renk ve hassasiyet gösterimi değiştirir.','Gerilim ailelerinin renkleri Ayarlar ekranında saklanır. Kalıcı şebeke editörü, OPF, toprak arızası, Rust/WASM ve Tauri bu arayüzün kapsamı değildir.','settings'),
];
export function helpEntry(id:string){return helpRegistry.find(e=>e.id===id);}
export function helpForField(label:string,screen:string):HelpEntry{
  const l=label.toLocaleLowerCase('tr-TR')+' '+label.toLowerCase(),pick=(id:string)=>helpEntry(id)!;
  if(/referans|benchmark|raw tablo|controlcontext/.test(l))return pick('compare.referencePackage');
  if(/tanısal|diagnostic/.test(l))return pick('compare.diagnosticDelta');
  if(screen==='comparison')return pick(/metri|durum/.test(l)?'compare.methodGate':'compare.filters');
  if(screen==='model')return pick(/bulgu|kalite|kapsam/.test(l)?'model.quality':'model.modelHash');
  if(screen==='analysis:SC')return pick(/double prime|makine|konverter|akım açısı/.test(l)?'sc.machineXdss':/c faktör|c_source|zaman|bütçe/.test(l)?'sc.externalGridFactor':/varsayım|approximation|override|normalizasyon/.test(l)?'sc.networkApproximation':/terminal|bara/.test(l)?'sc.partition':'sc.faultMode');
  if(screen==='analysis:N1')return pick(/promosyon|dc aşım|temiz vaka|açık seçim/.test(l)?'n1.dcPromotion':/bütçe|zaman/.test(l)?'n1.acBudget':/vpu|yük limiti/.test(l)?'n1.voltageLimits':/mevsim|kapasite|rating/.test(l)?'n1.ratingBasis':/kontrol profili/.test(l)?'n1.studyProfile':/sonuç|ihlal|ada|kısıt/.test(l)?'n1.constraintState':/ytm|tm |gerilim|uç kapsam/.test(l)?'n1.scope':'n1.dcScreen');
  if(screen==='analysis:LF')return pick(/station|istasyon|droop|balanc|denge/.test(l)?'lf.stationControlMode':/q limit|reaktif/.test(l)?'lf.qLimits':/iter|toler|newton|budget|nodal|iyileşme/.test(l)?'lf.convergence':/gerilim|sonuç kaynağı/.test(l)?'lf.voltageBand':'lf.fullAc');
  return pick(screen==='map'||screen==='sld'?'map.display':screen==='settings'?'settings.display':'inventory.filter');
}
