import type {AppContext} from '../../app/contracts';
import {element,button,escapeHtml as h} from './dom';
import {activeResultId,workspaceMapSelection} from '../../domain/results/workspace';
export function createScenarioWorkspace(ctx:AppContext){
  const root=element('div','ga-scenario-workspace'),select=element('select'),name=element('input'),compare=element('select'),log=element('details'),events=element('ol'),state=element('small');
  select.setAttribute('aria-label','Aktif senaryo');compare.setAttribute('aria-label','Senaryo farkının referansı');name.setAttribute('aria-label','Senaryo adı');name.placeholder='Senaryo adı';
  select.onchange=()=>void ctx.selectScenario(select.value);compare.onchange=()=>{ctx.resultStore.comparisonScenarioId=compare.value;ctx.resultStore.role='delta';ctx.resultStore.analysisType='powerFlow';ctx.analysisTab='LF';Object.assign(ctx.resultView,{analysis:'LF',source:'Senaryo−Baz',phase:'CHANGE',metric:'pFromMw'});ctx.benchmarkMap=workspaceMapSelection(ctx);ctx.notify();};
  const drawer=element('details','ga-scenario-drawer');drawer.append(element('summary','','Senaryolar'),name,button('Adlandır',()=>{ctx.scenario.rename(ctx.scenario.selectedId,name.value);ctx.notify();}),button('Dallan',()=>ctx.branchScenario(name.value||undefined)),compare);root.append(select,state,drawer);log.append(element('summary','','Manevra günlüğü'),events);drawer.append(log);
  let revision=-1,signature='';function render(){const current=ctx.scenario.selected,options=ctx.scenario.snapshots.map(s=>`<option value="${h(s.id)}">${h(s.name)} (${s.id})</option>`).join('');if(options!==signature){signature=options;select.innerHTML=compare.innerHTML=options;}select.value=current.id;compare.value=ctx.resultStore.comparisonScenarioId;root.dataset.scenarioId=current.id;root.dataset.resultId=activeResultId(ctx)||'NOT_RUN';state.textContent=`${current.id} · ${ctx.resultView.analysis} · ${activeResultId(ctx)?'Sonuç hazır':'NOT_RUN / STALE'}`;if(revision!==ctx.scenario.revision){revision=ctx.scenario.revision;events.replaceChildren();for(const e of current.events)events.append(element('li','',`${e.order}. ${e.source} · ${e.action} · ${e.equipmentId} · ${JSON.stringify(e.before)??'kaynak'} → ${JSON.stringify(e.after)??'kaynak'} · ${e.timestamp}`));}select.disabled=compare.disabled=ctx.busy||!ctx.network;}
  return{element:root,render};
}
