import {createWorkspaceResults} from '../features/analysis/workspace-results';
import {activeResultId} from '../domain/results/workspace';
import {requestedRole,calculationLabel,baseResultNotice} from '../ui/components/calculation-controls';
import type {AppContext} from '../app/contracts';
import {element,button} from '../ui/components/dom';
import {ResultTable} from '../features/analysis/result-table';
import {scenarioChanged} from '../domain/scenario/overlay';
import {createScenarioWorkspace} from '../ui/components/scenario-workspace';
import {downloadResultWorkbook} from '../features/analysis/xlsx-export';
export function createLightningPanel(ctx:AppContext){
  const panel=element('section','ga-lightning'),head=element('header','ga-lightning-head'),title=element('strong','','⚡ Elektriksel Sonuçlar'),body=element('div','ga-lightning-body'),status=element('p','ga-scenario-state');panel.hidden=true;
  const hide=()=>{panel.hidden=true;};let scenariosOpen=false;
  const minimize=button('−',()=>{body.hidden=!body.hidden;minimize.textContent=body.hidden?'□':'−';},'Paneli küçült / geri aç'),close=button('×',hide,'Sonuç panelini kapat');head.append(title,minimize,close);panel.append(head,body);
  const families=element('nav','ga-tabs-small'),shared=createWorkspaceResults(ctx),scenarios=createScenarioWorkspace(ctx,true);for(const [key,label] of [['LF','Yük Akışı'],['N1','Kısıt (N-1)'],['SC','Kısa Devre']] as const){const b=button(label,()=>{scenariosOpen=false;ctx.resultView.analysis=ctx.analysisTab=key;ctx.notify();});b.dataset.family=key;b.dataset.helpId='map.analysis';families.append(b);}const scenarioTab=button('Senaryolar',()=>{scenariosOpen=true;render();});scenarioTab.dataset.family='SCENARIOS';scenarioTab.dataset.helpId='map.scenario';families.append(scenarioTab);body.append(families,scenarios.element,shared.element);
  const main=element('div','ga-tabs-small'),kinds=element('div','ga-tabs-small'),toolbar=element('div','ga-result-toolbar'),container=element('div','ga-result-container'),table=new ResultTable(ctx,container);
  for(const[key,label]of[['results','Sonuçlar'],['delta','Senaryo Δ'],['energize','Devreye Alma']]as const){const b=button(label,()=>{table.tab=key;table.page=0;render();});b.dataset.main=key;main.append(b);}
  for(const[key,label]of[['line','Hatlar'],['trafo','Trafolar'],['bus','Baralar']]as const){const b=button(label,()=>{table.kind=key;table.page=0;render();});b.dataset.kind=key;kinds.append(b);}
  const search=element('input');search.type='search';search.placeholder='Ad veya FID ara';search.setAttribute('aria-label','Elektriksel sonuçlarda ara');search.oninput=()=>{table.search=search.value;table.page=0;table.render(true);};
  const calculate=button('Hesapla',()=>void ctx.run(ctx.resultStore.analysisType,requestedRole(ctx))),source=element('small','ga-result-source');toolbar.append(search,calculate,source);const baseNotice=baseResultNotice(ctx);body.append(baseNotice.element,status,main,kinds,toolbar,container);
  const exports=element('div','ga-lightning-exports'),xlsx=button('LF XLSX',()=>{const r=ctx.resultStore.active;if(r&&ctx.network)downloadResultWorkbook(r,ctx.network);},'Elektriksel sonuçları XLSX indir'),exportTools=button('Dışa aktar / Analizler',()=>ctx.setView('analysis:'+ctx.resultView.analysis),'Analiz dışa aktarımına git');xlsx.dataset.helpId=exportTools.dataset.helpId='map.results';exports.append(xlsx,exportTools);body.append(exports);
  function render(){panel.dataset.scenarioId=ctx.scenario.selectedId;panel.dataset.resultId=activeResultId(ctx)??'NOT_RUN';if(ctx.view!=='map')hide();const family=ctx.resultView.analysis;exports.hidden=scenariosOpen;xlsx.hidden=family!=='LF'||ctx.resultView.source!=='GA';xlsx.disabled=!ctx.resultStore.active;families.querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.family===(scenariosOpen?'SCENARIOS':family))));scenarios.element.hidden=!scenariosOpen;if(scenariosOpen)scenarios.render();shared.element.hidden=scenariosOpen||family==='LF'&&ctx.resultView.source==='GA';for(const item of [main,kinds,toolbar,container,baseNotice.element,status])item.hidden=scenariosOpen||!shared.element.hidden;if(!shared.element.hidden&&!panel.hidden)shared.render();baseNotice.render();baseNotice.element.hidden=scenariosOpen||!shared.element.hidden||baseNotice.element.hidden;calculate.textContent=calculationLabel(ctx);calculate.setAttribute('aria-label',calculate.textContent);const changed=scenarioChanged(ctx.scenario.current);status.hidden=scenariosOpen||!shared.element.hidden||!changed;status.textContent=ctx.resultStore.get('scenario')?'Senaryo güncel':'Senaryo değişti · Güncel hesap bekleniyor';const r=ctx.resultStore.active;source.textContent=`${ctx.resultStore.analysisType==='powerFlow'?'Tam AC':ctx.resultStore.analysisType==='dc'?'DC':'Hızlı AC'} · ${table.tab==='delta'?'Fark':ctx.resultStore.role==='base'?'Baz':'Senaryo'}${r&&!r.converged?' · '+r.status:''}`;calculate.disabled=ctx.busy||!ctx.network;main.querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.main===table.tab)));kinds.querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.kind===table.kind)));if(!panel.hidden&&!scenariosOpen&&shared.element.hidden)table.render();}
  const escape=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!panel.hidden)hide();},outside=(e:PointerEvent)=>{const target=e.target as Element;if(!panel.hidden&&!panel.contains(target)&&!target.closest('.ga-lightning-toggle,.ga-map-scenario-chip'))hide();};
  document.addEventListener('keydown',escape);document.addEventListener('pointerdown',outside);
  return{element:panel,render,table,close:hide,open(tab?:'SCENARIOS'){scenariosOpen=tab==='SCENARIOS';panel.hidden=false;body.hidden=false;minimize.textContent='−';render();},toggle(){panel.hidden=!panel.hidden;if(!panel.hidden){body.hidden=false;minimize.textContent='−';}render();},dispose(){document.removeEventListener('keydown',escape);document.removeEventListener('pointerdown',outside);}};
}
