import {createWorkspaceResults} from '../features/analysis/workspace-results';
import {activeResultId,workspaceMapSelection} from '../domain/results/workspace';
import {requestedRole,calculationLabel,baseResultNotice} from '../ui/components/calculation-controls';
import type {AppContext} from '../app/contracts';
import {element,button} from '../ui/components/dom';
import {ResultTable} from '../features/analysis/result-table';
import {scenarioChanged} from '../domain/scenario/overlay';
import {createScenarioWorkspace} from '../ui/components/scenario-workspace';
import {downloadResultWorkbook} from '../features/analysis/xlsx-export';
import {solutionCompleteness} from '../domain/results/diagnostics';
export function createLightningPanel(ctx:AppContext){
  const panel=element('section','ga-lightning'),head=element('header','ga-lightning-head'),title=element('strong','','⚡ Elektriksel Sonuçlar'),identity=element('small'),body=element('div','ga-lightning-body'),status=element('p','ga-scenario-state'),summary=element('p','ga-result-context');panel.hidden=true;let scenariosOpen=false;
  const hide=()=>{panel.hidden=true;},minimize=button('−',()=>{body.hidden=!body.hidden;minimize.textContent=body.hidden?'□':'−';},'Paneli küçült / geri aç'),close=button('×',hide,'Sonuç panelini kapat');head.append(title,identity,minimize,close);panel.append(head,body);
  const families=element('nav','ga-tabs-small ga-lightning-tabs'),shared=createWorkspaceResults(ctx),scenarios=createScenarioWorkspace(ctx,true);
  for(const [key,label] of [['LF','Yük Akışı'],['N1','Kısıt (N-1)'],['SC','Kısa Devre']] as const){const b=button(label,()=>{scenariosOpen=false;if(ctx.resultView.analysis!==key){ctx.resultView.analysis=ctx.analysisTab=key;ctx.resultView.source='GA';ctx.resultView.metric=key==='LF'?'pFromMw':key==='N1'?'postPmw':'ikssKa';ctx.resultView.phase=key==='LF'?'BASE':'POST';ctx.benchmarkMap=workspaceMapSelection(ctx);}ctx.notify();});b.dataset.family=key;families.append(b);}const scenarioTab=button('Senaryolar',()=>{scenariosOpen=true;render();});scenarioTab.dataset.family='SCENARIOS';families.append(scenarioTab);body.append(families,scenarios.element,shared.element);
  const controls=element('div','ga-result-toolbar'),container=element('div','ga-result-container'),table=new ResultTable(ctx,container,true,true),kind=element('select'),view=element('select'),search=element('input');
  kind.setAttribute('aria-label','Elektriksel sonuç ekipmanı');kind.innerHTML='<option value="line">Hatlar</option><option value="trafo">Trafolar</option><option value="bus">Baralar</option>';view.setAttribute('aria-label','Elektriksel sonuç görünümü');view.innerHTML='<option value="results">Sonuçlar</option><option value="delta">Senaryo Δ</option><option value="energize">Devreye Alma</option>';
  const label=(text:string,field:HTMLElement)=>{const l=element('label','ga-result-filter');l.append(element('span','',text),field);return l;};
  kind.onchange=()=>{table.kind=kind.value as typeof table.kind;table.page=0;render();};view.onchange=()=>{table.tab=view.value as typeof table.tab;table.page=0;render();};search.type='search';search.placeholder='Ad veya FID ara';search.setAttribute('aria-label','Elektriksel sonuçlarda ara');search.oninput=()=>{table.search=search.value;table.page=0;table.render(true);};controls.append(label('Ekipman',kind),label('Görünüm',view),search);
  const baseNotice=baseResultNotice(ctx);body.append(summary,baseNotice.element,status,controls,container);
  const exports=element('div','ga-lightning-exports'),xlsx=button('LF XLSX',()=>{const r=ctx.resultStore.active;if(r&&ctx.network)downloadResultWorkbook(r,ctx.network);},'Elektriksel sonuçları XLSX indir'),calculate=button('Hesapla',()=>void ctx.run(ctx.resultStore.analysisType,requestedRole(ctx))),exportTools=button('Dışa aktar / Analizler',()=>ctx.setView('analysis:'+ctx.resultView.analysis),'Analiz dışa aktarımına git');exports.append(xlsx,calculate,exportTools);body.append(exports);
  function render(){
    const family=ctx.resultView.analysis,r=ctx.resultStore.active,lf=!scenariosOpen&&family==='LF'&&ctx.resultView.source==='GA';panel.dataset.scenarioId=ctx.scenario.selectedId;panel.dataset.resultId=activeResultId(ctx)??'NOT_RUN';identity.textContent=ctx.scenario.selectedId+' · '+(ctx.scenario.selectedId==='B0'?'Baz':'Senaryo');if(ctx.view!=='map')hide();
    for(const b of families.querySelectorAll<HTMLButtonElement>('button'))b.setAttribute('aria-pressed',String(b.dataset.family===(scenariosOpen?'SCENARIOS':family)));scenarios.element.hidden=!scenariosOpen;shared.element.hidden=scenariosOpen||lf;
    if(scenariosOpen)scenarios.render();if(!shared.element.hidden&&!panel.hidden)shared.render();
    for(const item of [summary,controls,container,baseNotice.element,status])item.hidden=!lf;exports.hidden=scenariosOpen;xlsx.hidden=calculate.hidden=!lf;xlsx.disabled=!r;calculate.textContent=calculationLabel(ctx);calculate.setAttribute('aria-label',calculate.textContent);calculate.disabled=ctx.busy||!ctx.network;
    if(lf){const completeness=solutionCompleteness(r);summary.textContent=`${ctx.scenario.selectedId} · ${r?r.buses.length+' bara / '+r.branches.length+' dal':'Sonuç yok'} · ${r?completeness.fullSolution?'Full AC':'Full AC / kısmi':'NOT_RUN'}`;baseNotice.render();status.hidden=!scenarioChanged(ctx.scenario.current);status.textContent=ctx.resultStore.get('scenario')?'Senaryo güncel':'Senaryo değişti · Güncel hesap bekleniyor';kind.value=table.kind;view.value=table.tab;if(!panel.hidden)table.render();}
  }
  const escape=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!panel.hidden)hide();},outside=(e:PointerEvent)=>{const target=e.target as Element;if(!panel.hidden&&!panel.contains(target)&&!target.closest('.ga-lightning-toggle,.ga-map-scenario-chip'))hide();};document.addEventListener('keydown',escape);document.addEventListener('pointerdown',outside);
  return {element:panel,render,table,close:hide,open(tab?:'SCENARIOS'|'RESULTS'){if(tab)scenariosOpen=tab==='SCENARIOS';panel.hidden=false;body.hidden=false;minimize.textContent='−';render();},toggle(){panel.hidden=!panel.hidden;if(!panel.hidden){body.hidden=false;minimize.textContent='−';}render();},dispose(){document.removeEventListener('keydown',escape);document.removeEventListener('pointerdown',outside);}};
}
