import {createVoltageFilter} from '../ui/components/voltage-filter';
import {voltageMatches} from '../domain/model/voltage-band';
import {capacitySession,setCapacitySeason,type CapacitySeason} from '../domain/model/capacity';
import type {AppContext,Feature} from '../app/contracts';
import {element,button,escapeHtml as h} from '../ui/components/dom';
import {CanvasMapRenderer} from './canvas-renderer';
import {createLightningPanel} from './lightning-panel';
import {scenarioChanged} from '../domain/scenario/overlay';
export function createMapView(ctx:AppContext):Feature{
  const root=element('section','ga-map-view'),bar=element('div','ga-map-toolbar'),filters=element('div','ga-map-filters'),wrap=element('div','ga-map-wrap'),canvas=element('canvas','ga-network-canvas'),overlay=element('canvas','ga-flow-canvas'),tooltip=element('div','ga-map-tooltip'),legend=element('aside','ga-map-legend'),detail=element('div','ga-map-selection');tooltip.hidden=true;
  canvas.id='networkCanvas';wrap.append(canvas,overlay,tooltip,legend,detail);root.append(bar,filters,wrap);const renderer=new CanvasMapRenderer(ctx,canvas,overlay,tooltip),panel=createLightningPanel(ctx);wrap.append(panel.element);
  const lightning=button('⚡',()=>panel.toggle(),'Elektriksel Sonuçlar');lightning.className+=' ga-lightning-toggle';wrap.append(lightning);
  const area=element('select'),site=element('select'),mode=element('select'),layout=element('select'),role=element('select'),search=element('input');
  area.setAttribute('aria-label','YTM filtresi');area.id='mapArea';site.setAttribute('aria-label','Trafo merkezi seçimi');site.id='mapSite';mode.setAttribute('aria-label','Harita renk modu');layout.setAttribute('aria-label','Hat yerleşimi');role.setAttribute('aria-label','Sonuç kaynağı');search.placeholder='Hat adı veya FID';search.setAttribute('aria-label','Haritada hat ara');search.type='search';
  mode.innerHTML='<option value="nominal">Nominal gerilim</option><option value="loading">Yüklenme</option><option value="delta">Senaryo farkı</option>';layout.innerHTML='<option value="standard">Standart</option><option value="separated">Ayrık hatlar</option>';role.innerHTML='<option value="base">Baz sonuç</option><option value="scenario">Senaryo sonucu</option><option value="delta">Baz / Senaryo Δ</option>';
  const capacity=element('select');capacity.setAttribute('aria-label','Harita kapasite sınırı');capacity.innerHTML='<option value="nominal">DGS nominal kapasite</option><option value="summer">Yaz kapasitesi</option><option value="winter">Kış kapasitesi</option><option value="operational">İşletme adayı (doğrulanmamış)</option>';capacity.onchange=()=>{if(ctx.network){setCapacitySeason(ctx.network.modelHash,capacity.value as CapacitySeason);ctx.notify();}};
  const calc=button('Hesapla',()=>void ctx.run(ctx.resultStore.analysisType)),reset=button('Sıfırla',()=>ctx.resetScenario(),'Senaryoyu sıfırla'),undo=button('Geri al',()=>ctx.undoScenario(),'Son senaryo değişikliğini geri al');bar.append(area,site,mode,layout,role,capacity,calc,undo,reset,button('Sığdır',()=>renderer.reset()));
  const voltageFilter=createVoltageFilter(ctx,'Harita gerilim grupları'),voltages=voltageFilter.element;voltages.id='voltageLayers';const flag=(text:string,checked:boolean,action:(v:boolean)=>void)=>{const label=element('label','ga-check'),input=element('input');input.type='checkbox';input.checked=checked;input.onchange=()=>action(input.checked);label.append(input,document.createTextNode(text));return{label,input};};
  const flow=flag('Akış',ctx.settings.value.flowDefault,value=>{ctx.settings.update({flowDefault:value});ctx.notify();}),sites=flag('TM',true,value=>{renderer.showSites=value;renderer.render();}),labels=flag('Etiketler',false,value=>{renderer.showLabels=value;renderer.render();}),simple=flag('Temsili güzergâh',false,value=>{renderer.simple=value;renderer.render();});
  filters.append(voltages,flow.label,sites.label,labels.label,simple.label,search,button('Bul',()=>{const q=search.value.trim().toLocaleLowerCase('tr-TR'),line=ctx.network?.lines.find(l=>`${l.name} ${l.id}`.toLocaleLowerCase('tr-TR').includes(q));if(line&&q){ctx.select(line.id,'ElmLne');renderer.focus(line.id,'ElmLne');}else ctx.setMessage('Hat bulunamadı.');}));
  search.onkeydown=e=>{if(e.key==='Enter')(search.nextElementSibling as HTMLButtonElement).click();};
  function syncScope(){ctx.filters.areaId=area.value;ctx.filters.siteId='';ctx.selection=null;panel.table.page=0;refillSites();ctx.notify();}
  area.onchange=syncScope;site.onchange=()=>{ctx.filters.siteId=site.value;if(site.value){ctx.select(site.value,'ElmSite');renderer.focus(site.value,'ElmSite');}else{ctx.selection=null;ctx.notify();}};
  mode.onchange=()=>{ctx.settings.update({displayMode:mode.value as 'nominal'|'loading'|'delta'});if(mode.value==='delta')ctx.resultStore.role='delta';ctx.notify();};layout.onchange=()=>{ctx.settings.update({layoutMode:layout.value as 'standard'|'separated'});ctx.notify();};role.onchange=()=>{ctx.resultStore.role=role.value as 'base'|'scenario'|'delta';if(role.value==='delta')ctx.settings.update({displayMode:'delta'});else if(ctx.settings.value.displayMode==='delta')ctx.settings.update({displayMode:'nominal'});ctx.notify();};
  let modelHash='',lastSelection='';
  function refillSites(){const rows=ctx.network?.sites.filter(s=>(!area.value||s.areaId===area.value)&&s.voltages.some(v=>voltageMatches(v,ctx.filters.voltages)))||[];site.innerHTML='<option value="">Trafo merkezi seçin</option>'+rows.map(s=>`<option value="${h(s.id)}">${h(s.name)}</option>`).join('');site.value=ctx.filters.siteId;}
  function render(){const n=ctx.network;
    if(n?.modelHash!==modelHash){modelHash=n?.modelHash||'';const areas=new Map(n?.sites.map(s=>[s.areaId,s.areaName])||[]);area.innerHTML='<option value="">Tüm YTM</option>'+[...areas].sort((a,b)=>a[1].localeCompare(b[1],'tr')).map(([id,name])=>`<option value="${h(id)}">${h(name)}</option>`).join('');refillSites();renderer.reset();}
    voltageFilter.render();area.value=ctx.filters.areaId;refillSites();capacity.value=n?capacitySession(n.modelHash).season:'nominal';mode.value=ctx.settings.value.displayMode;layout.value=ctx.settings.value.layoutMode;role.value=ctx.resultStore.role;flow.input.checked=ctx.settings.value.flowDefault;calc.disabled=ctx.busy||!n;reset.disabled=!scenarioChanged(ctx.scenario.current);undo.disabled=reset.disabled;
    legend.hidden=!ctx.settings.value.legend;legend.innerHTML=ctx.settings.value.displayMode==='nominal'?`<b>Nominal gerilim</b><span><i style="background:${ctx.settings.value.color400}"></i>400 kV</span><span><i style="background:${ctx.settings.value.colorMid}"></i>66 / 154 / 220 kV</span><span>┄ Servis dışı</span>`:ctx.settings.value.displayMode==='loading'?`<b>Yüklenme (%)</b><span>${ctx.settings.value.thresholds.join(' / ')}</span><span>Gri: geçerli sonuç yok</span>`:`<b>Senaryo farkı</b><span><i style="background:${ctx.settings.value.deltaUp}"></i>Artış</span><span><i style="background:${ctx.settings.value.deltaDown}"></i>Azalış</span><span><i style="background:${ctx.settings.value.deltaNeutral}"></i>Nötr</span><span>Gri: karşılaştırma yok</span>`;
    const selected=ctx.selection,entity=selected?(selected.sourceClass==='ElmSite'?n?.sites:selected.sourceClass==='ElmLne'?n?.lines:selected.sourceClass==='ElmTr2'?n?.transformers:n?.buses)?.find(e=>e.id===selected.id):null;
    detail.replaceChildren();if(entity){const name=element('strong','',entity.name),id=element('small','',`${entity.sourceClass} · ${entity.id}`);detail.append(name,id,button('Tek hat',()=>ctx.select(entity.id,entity.sourceClass,'sld')),button('Temizle',()=>{ctx.selection=null;ctx.notify();}));if(entity.sourceClass==='ElmLne')detail.append(button('Sonuç / Senaryo',()=>{panel.element.hidden=false;panel.table.kind='line';panel.table.search=entity.id;panel.table.expanded=entity.id;panel.render();}));}else detail.textContent='TM veya hat seçin · Tekerlek: yakınlaştır · Sürükle: kaydır';
    const selectionKey=selected?`${selected.sourceClass}|${selected.id}`:'';if(selectionKey!==lastSelection){lastSelection=selectionKey;if(selected&&selected.sourceClass!=='ElmTerm')renderer.focus(selected.id,selected.sourceClass);}
    renderer.render();panel.render();
  }
  return{element:root,render,dispose:()=>renderer.dispose()};
}
