import {deltaLabels,deltaMaximum} from './delta-style';
import type {Settings} from '../persistence/settings';
import type {Line} from '../domain/model/network';
import {requestedRole,calculationLabel,baseResultNotice} from '../ui/components/calculation-controls';
import {createVoltageFilter} from '../ui/components/voltage-filter';
import {voltageMatches} from '../domain/model/voltage-band';
import {capacitySession,setCapacitySeason,type CapacitySeason} from '../domain/model/capacity';
import type {AppContext,Feature} from '../app/contracts';
import {element,button,escapeHtml as h} from '../ui/components/dom';
import {CanvasMapRenderer} from './canvas-renderer';
import {createLightningPanel} from './lightning-panel';
import {scenarioChanged} from '../domain/scenario/overlay';
import {calculationEngineLabel,calculationSessionStatus} from '../ui/components/calculation-controls';
import {createBenchmarkMapControls} from './benchmark-controls';
export function createMapView(ctx:AppContext):Feature{
  const root=element('section','ga-map-view'),bar=element('div','ga-map-toolbar'),filters=element('div','ga-map-filters'),wrap=element('div','ga-map-wrap'),baseCanvas=element('canvas','ga-basemap-canvas'),selectionCanvas=element('canvas','ga-selection-canvas'),canvas=element('canvas','ga-network-canvas'),overlay=element('canvas','ga-flow-canvas'),tooltip=element('div','ga-map-tooltip'),legend=element('aside','ga-map-legend'),detail=element('div','ga-map-selection');tooltip.hidden=true;
  canvas.id='networkCanvas';wrap.append(baseCanvas,canvas,selectionCanvas,overlay,tooltip,legend,detail);root.append(bar,filters,wrap);const renderer=new CanvasMapRenderer(ctx,canvas,overlay,tooltip,baseCanvas,selectionCanvas),panel=createLightningPanel(ctx);wrap.append(panel.element);
  const session=calculationSessionStatus(ctx);root.append(session.element);
  const benchmarkControls=createBenchmarkMapControls(ctx);root.insertBefore(benchmarkControls.element,wrap);
  const lightning=button('⚡',()=>panel.toggle(),'Elektriksel Sonuçlar');lightning.className+=' ga-lightning-toggle';wrap.append(lightning);
  const area=element('select'),site=element('select'),mode=element('select'),layout=element('select'),role=element('select'),search=element('input');
  area.setAttribute('aria-label','YTM filtresi');area.id='mapArea';site.setAttribute('aria-label','Trafo merkezi seçimi');site.id='mapSite';mode.setAttribute('aria-label','Harita renk modu');layout.setAttribute('aria-label','Hat yerleşimi');role.setAttribute('aria-label','Sonuç göster');search.placeholder='Hat adı veya FID';search.setAttribute('aria-label','Haritada hat ara');search.type='search';
  mode.innerHTML='<option value="nominal">Nominal gerilim</option><option value="loading">Yüklenme P (%)</option><option value="q">Yüklenme Q (%)</option><option value="v">Bara gerilimi V</option><option value="angle">Bara açısı θ</option><option value="delta">Senaryo farkı</option><option value="island">Elektrik adası</option><option value="n1-island">N-1 adaları</option><option value="n1-risk">N-1 termik risk</option>';layout.innerHTML='<option value="standard">Standart</option><option value="separated">Ayrık hatlar</option>';role.innerHTML='<option value="base">Baz</option><option value="scenario">Senaryo</option><option value="delta">Fark</option>';
  const capacity=element('select');capacity.setAttribute('aria-label','Harita kapasite sınırı');capacity.innerHTML='<option value="nominal">DGS nominal kapasite</option><option value="summer">Yaz kapasitesi</option><option value="winter">Kış kapasitesi</option><option value="operational">İşletme adayı (doğrulanmamış)</option>';capacity.onchange=()=>{if(ctx.network){setCapacitySeason(ctx.network.modelHash,capacity.value as CapacitySeason);ctx.notify();}};
  const calc=button('Hesapla',()=>void ctx.run(ctx.resultStore.analysisType,requestedRole(ctx))),reset=button('Sıfırla',()=>ctx.resetScenario(),'Senaryoyu sıfırla'),undo=button('Geri al',()=>ctx.undoScenario(),'Son senaryo değişikliğini geri al'),fullscreen=button('Tam Ekran',()=>{if(document.fullscreenElement===wrap)void document.exitFullscreen();else void wrap.requestFullscreen();});bar.append(area,site,mode,layout,role,capacity,calc,undo,reset,button('Sığdır',()=>renderer.reset()),fullscreen);document.addEventListener('fullscreenchange',()=>{fullscreen.textContent=document.fullscreenElement===wrap?'Tam Ekrandan Çık':'Tam Ekran';renderer.render();});
  const baseNotice=baseResultNotice(ctx);root.insertBefore(baseNotice.element,wrap);const metric=element('select');metric.setAttribute('aria-label','Fark metriği');metric.innerHTML='<option value="p">Fark: ΔP</option><option value="q">Fark: ΔQ</option><option value="v">Fark: ΔV</option><option value="loading">Fark: ΔYük %</option>';metric.onchange=()=>{ctx.settings.update({deltaMetric:metric.value as Settings['deltaMetric']});ctx.notify();};bar.insertBefore(metric,layout);
  legend.addEventListener('click',event=>{const choice=(event.target as HTMLElement).closest<HTMLElement>('[data-n1-island]');if(choice){const islandId=choice.dataset.n1Island||null;ctx.selectN1Island(ctx.selectedN1IslandId===islandId?null:islandId);}});
  const voltageFilter=createVoltageFilter(ctx,'Harita gerilim grupları'),voltages=voltageFilter.element;voltages.id='voltageLayers';const flag=(text:string,checked:boolean,action:(v:boolean)=>void)=>{const label=element('label','ga-check'),input=element('input');input.type='checkbox';input.checked=checked;input.onchange=()=>action(input.checked);label.append(input,document.createTextNode(text));return{label,input};};
  const flow=flag('Akış',ctx.settings.value.flowDefault,value=>{ctx.settings.update({flowDefault:value});ctx.notify();}),sites=flag('TM',true,value=>{renderer.showSites=value;renderer.render();}),labels=flag('Etiketler',false,value=>{renderer.showLabels=value;renderer.render();}),simple=flag('Sade güzergâh',false,value=>{renderer.simple=value;renderer.render();});
  filters.append(voltages,flow.label,sites.label,labels.label,simple.label,search,button('Bul',()=>{const q=search.value.trim().toLocaleLowerCase('tr-TR'),line=ctx.network?.lines.find(l=>`${l.name} ${l.id}`.toLocaleLowerCase('tr-TR').includes(q));if(line&&q){ctx.select(line.id,'ElmLne');renderer.focus(line.id,'ElmLne');}else ctx.setMessage('Hat bulunamadı.');}));
  search.onkeydown=e=>{if(e.key==='Enter')(search.nextElementSibling as HTMLButtonElement).click();};
  function syncScope(){ctx.filters.areaId=area.value;ctx.filters.siteId='';ctx.selection=null;panel.table.page=0;refillSites();ctx.notify();}
  area.onchange=syncScope;site.onchange=()=>{ctx.filters.siteId=site.value;if(site.value){ctx.select(site.value,'ElmSite');renderer.focus(site.value,'ElmSite');}else{ctx.selection=null;ctx.notify();}};
  mode.onchange=()=>{ctx.settings.update({displayMode:mode.value as Settings['displayMode']});ctx.notify();};layout.onchange=()=>{ctx.settings.update({layoutMode:layout.value as 'standard'|'separated'});ctx.notify();};role.onchange=()=>{ctx.resultStore.role=role.value as 'base'|'scenario'|'delta';ctx.notify();};
  let modelHash='',lastSelection='',lastN1Candidate='';
  function refillSites(){const rows=ctx.network?.sites.filter(s=>(!area.value||s.areaId===area.value)&&s.voltages.some(v=>voltageMatches(v,ctx.filters.voltages)))||[];site.innerHTML='<option value="">Trafo merkezi seçin</option>'+rows.map(s=>`<option value="${h(s.id)}">${h(s.name)}</option>`).join('');site.value=ctx.filters.siteId;}
  function render(){if(ctx.view!=='map')return;const n=ctx.network;
    benchmarkControls.render();
    if(n?.modelHash!==modelHash){modelHash=n?.modelHash||'';const areas=new Map(n?.sites.map(s=>[s.areaId,s.areaName])||[]);area.innerHTML='<option value="">Tüm YTM</option>'+[...areas].sort((a,b)=>a[1].localeCompare(b[1],'tr')).map(([id,name])=>`<option value="${h(id)}">${h(name)}</option>`).join('');refillSites();renderer.reset();}
    baseNotice.render();session.render();metric.hidden=ctx.settings.value.displayMode!=='delta';metric.value=ctx.settings.value.deltaMetric;calc.textContent=calculationLabel(ctx);calc.setAttribute('aria-label',calc.textContent);voltageFilter.render();area.value=ctx.filters.areaId;refillSites();capacity.value=n?capacitySession(n.modelHash).season:'nominal';mode.value=ctx.settings.value.displayMode;layout.value=ctx.settings.value.layoutMode;role.value=ctx.resultStore.role;flow.input.checked=ctx.settings.value.flowDefault;calc.disabled=ctx.busy||!n;reset.disabled=!scenarioChanged(ctx.scenario.current);undo.disabled=!ctx.scenario.historyLength;
    const settings=ctx.settings.value;legend.hidden=!settings.legend;renderer.render();
    const n1Detail=ctx.n1Detail?.candidate.candidateId===ctx.selectedN1CandidateId?ctx.n1Detail:null,n1Mode=settings.displayMode==='n1-island'||settings.displayMode==='n1-risk';if(n1Mode&&n1Detail&&lastN1Candidate!==n1Detail.candidateId){lastN1Candidate=n1Detail.candidateId;renderer.focus(n1Detail.outage.equipmentId,n1Detail.outage.sourceClass);}
    const delta=deltaLabels[settings.deltaMetric];const modes={nominal:'Nominal gerilim',loading:'Yüklenme P (%)',p:'Aktif güç akışı P',q:'Yüklenme Q (%)',v:'Bara gerilimi V',angle:'Bara açısı θ',delta:'Senaryo farkı',island:'Elektrik adası','n1-island':'N-1 adaları','n1-risk':'N-1 termik risk'};
    legend.innerHTML=`<b>${modes[settings.displayMode]}</b>`+(settings.displayMode==='island'?renderer.islandLegendMarkup(settings.colorNoResult):settings.displayMode==='n1-island'?renderer.n1IslandLegendMarkup(settings.colorNoResult):settings.displayMode==='n1-risk'?renderer.n1RiskLegendMarkup(settings.colorNoResult):settings.displayMode==='delta'?`<span><i style="background:${settings.deltaUp}"></i>${delta.name} artışı +${delta.unit}</span><span><i style="background:${settings.deltaDown}"></i>${delta.name} azalışı −${delta.unit}</span><span><i style="background:${settings.deltaNeutral}"></i>Nötr</span><span>Görsel maksimum: ±${deltaMaximum(settings)} ${delta.unit}</span>`:settings.displayMode==='v'?`<span class="ga-gradient-key" style="background:linear-gradient(90deg,${settings.voltageLowColor},${settings.voltageNeutralColor},${settings.voltageHighColor})"></span><span>${settings.voltageMin.toFixed(2)} – ${settings.voltageNeutral.toFixed(2)} – ${settings.voltageMax.toFixed(2)} pu</span><span>TM: en büyük |V − 1|</span>`:settings.displayMode==='angle'?`<span class="ga-gradient-key" style="background:linear-gradient(90deg,${settings.angleNegativeColor},${settings.angleNeutralColor},${settings.anglePositiveColor})"></span><span>${settings.angleMin}° – ${settings.angleNeutral}° – ${settings.angleMax}°</span><span>TM: ≥66 kV bara medyanı · ada referansına bağlı</span>`:settings.displayMode==='loading'?`<span>max |P uçları| / nominal MVA</span><span>Eşikler: ${settings.thresholds.join(' / ')} %</span>`:settings.displayMode==='q'?`<span>max |Q uçları| / Q-baz</span><span>400 kV: ${settings.qBase400Mvar} MVAr · 154 kV: ${settings.qBase154Mvar} MVAr</span><span>Eşikler: ${settings.qThresholds.join(' / ')} %</span><span>Hareketli uç okları MVAr yönünü ayrı gösterir</span><span>Değer için çizgiye gelin; sabit etiket yakın zoomda</span>`:`<span><i style="background:${settings.color400}"></i>400 kV</span><span><i style="background:${settings.color220}"></i>220 kV</span><span><i style="background:${settings.color154}"></i>154 kV</span><span><i style="background:${settings.color66}"></i>66 kV</span><span><i style="background:${settings.colorLow}"></i>≤36 kV</span>`)+`<span>Gri: sonuç yok · ┄ servis dışı</span><small>Altlık: geoBoundaries / OSM · CC BY-SA 2.0</small>`;
    const benchmarkLegend=renderer.benchmarkLegendMarkup();if(benchmarkLegend)legend.innerHTML=benchmarkLegend;
    const selected=ctx.selection,entity=selected?(selected.sourceClass==='ElmSite'?n?.sites:selected.sourceClass==='ElmLne'?n?.lines:selected.sourceClass==='ElmTr2'?n?.transformers:n?.buses)?.find(e=>e.id===selected.id):null;
    detail.replaceChildren();if(entity){detail.append(element('strong','',entity.name),element('small','ga-muted',`${entity.sourceClass} · ${entity.id}`));
      if(entity.sourceClass==='ElmLne'){const line=entity as Line,on=ctx.scenario.current.lineStatus[line.id]??line.inService;
        detail.append(element('span','',`${line.vnKv} kV · Kaynak: ${line.inService?'Serviste':'Servis dışı'} · Senaryo: ${on?'Serviste':'Servis dışı'}`));
        const toggle=button(on?'Servis dışı':'Servise al',()=>void ctx.setStatus('lineStatus',line.id,!on,line.inService)),calculate=button(`Değiştir + ${calculationEngineLabel(ctx)} Senaryo Hesapla`,()=>void ctx.setStatus('lineStatus',line.id,!on,line.inService,true));toggle.disabled=calculate.disabled=ctx.busy;detail.append(toggle,calculate,button('Sonuçlar',()=>{panel.element.hidden=false;panel.table.kind='line';panel.table.search=line.id;panel.table.expanded=line.id;panel.render();}));
        if(line.id in ctx.scenario.current.lineStatus||ctx.scenario.current.energizations?.[line.id])detail.append(button('Kaynağa dön',()=>void ctx.setStatus('lineStatus',line.id,line.inService,line.inService)));
        if(settings.displayMode!=='nominal')detail.append(element('small','ga-flow-detail',renderer.detailText(line)));
      }
      if(entity.sourceClass==='ElmSite'&&(settings.displayMode==='v'||settings.displayMode==='angle'||settings.displayMode==='island'||settings.displayMode==='delta'&&settings.deltaMetric==='v'))detail.append(element('small','ga-flow-detail',renderer.detailText(entity as import('../domain/model/network').Site)));
      detail.append(button('Tek Hat',()=>ctx.select(entity.id,entity.sourceClass,'sld')),button('Temizle',()=>{ctx.selection=null;ctx.notify();}));
    }else detail.textContent='TM veya hat seçin · Tekerlek: yakınlaştır · Sürükle: kaydır';
    const selectionKey=selected?`${selected.sourceClass}|${selected.id}`:'';if(selectionKey!==lastSelection){lastSelection=selectionKey;if(selected&&selected.sourceClass!=='ElmTerm')renderer.focus(selected.id,selected.sourceClass);}
    panel.render();
  }
  return{element:root,render,dispose:()=>renderer.dispose()};
}
