import type { AnalysisEngine, AnalysisRequest, Progress } from './engine';
import type { CanonicalNetwork } from '../../domain/model/network';
import { effectiveNetwork } from '../../domain/scenario/overlay';
import { prepareModel } from '../power-flow/preparation';
import { mapResults } from '../power-flow/results';
import {runStationControlledIslandV73,type ControlDiagnostic,type ControlTimings} from '../power-flow/station-controls-v73';
import { runReduced } from '../fast-ac/reduced-engine';
import {APP_VERSION} from '../../version';
import {analysisSettingsHash,effectiveFullAcLimits,profileFidelity,unsupportedFullAcSettings,unsupportedSharedSettings} from '../../domain/calculation/analysis-settings';
export class BrowserJsPowerFlowEngine implements AnalysisEngine {
  readonly name='BrowserJsEngine';readonly version=APP_VERSION;
  capabilities(network:CanonicalNetwork){return network.capabilities;}
  async runPowerFlow(request:AnalysisRequest,onProgress:Progress=()=>{}){
    onProgress('MODEL');const start=performance.now(),effective=effectiveNetwork(request.network,request.scenario);onProgress('TOPOLOGY');
    const built=prepareModel(effective),preparedMs=performance.now()-start;onProgress('INIT');
    let lastInnerProgressMs=-Infinity;
    const fullAcSettings=request.analysisSettings?.powerFlow,mappings=built.diagnostics.stationControllerMappings as {id:string;islandId:string|null;solverBusIndex:number|null}[],islandModels=[built,...(built.additionalIslands||[])],outputs=islandModels.map(part=>{
      const stationMode=request.stationControlMode??fullAcSettings?.stationControlMode??'off';
      const controlled=runStationControlledIslandV73(effective,part,mappings,stationMode,(stage,detail)=>{if(stage==='INNER_ITERATION'){const at=performance.now();if(at-lastInnerProgressMs<100)return;lastInnerProgressMs=at;}onProgress(stage==='YBUS_READY'?'YBUS':stage==='Q_LIMIT_UPDATE'?'Q_LIMIT':stage==='STATION_CONTROL'?'OUTER_CONTROL':'INNER_NR',{...detail,islandId:part.islandId});},request.stationControlImplementation??'SENSITIVITY',fullAcSettings);
      const numerical=controlled.result,mapStart=performance.now(),mapped=mapResults(controlled.prepared,numerical,request.identity);return{part:controlled.prepared,numerical,mapped,controlled,resultMapMs:performance.now()-mapStart};
    });
    onProgress('RESULT');const first=outputs[0].mapped,allConverged=outputs.every(o=>o.numerical.converged);
    for(const o of outputs.slice(1)){first.buses.push(...o.mapped.buses);first.branches.push(...o.mapped.branches);first.generators.push(...o.mapped.generators);first.warnings.push(...o.mapped.warnings);}
    first.converged=allConverged;first.status=allConverged?'CONVERGED_FULL_NR':outputs.length>1?'PARTIAL_ISLAND_FAILURE':first.status;
    first.iterations=outputs.reduce((sum,o)=>sum+o.numerical.iterations,0);first.rounds=Math.max(...outputs.map(o=>o.numerical.rounds));first.elapsedMs=performance.now()-start;
    first.maxMismatchMw=outputs.reduce<number|null>((max,o)=>o.numerical.maxMismatchMW==null?max:max==null?o.numerical.maxMismatchMW:Math.max(max,o.numerical.maxMismatchMW),null);
    first.quality.numericalStatus=allConverged?'NR_CONVERGED':'NR_NOT_CONVERGED';
    first.diagnostics.analysisSettings=fullAcSettings??null;
    first.diagnostics.qLimitActiveSet={stateModel:'PV_ACTIVE_TO_LIMITED_MONOTONIC',releaseSupport:'UNSUPPORTED',repeatedReactiveLimitDetectionApplied:false,configuredRepeatedDetection:fullAcSettings?.repeatedReactiveLimitDetection??null,rounds:outputs.flatMap(o=>o.numerical.qLimitRounds?.map(row=>({...row,islandId:o.part.islandId}))??[])};
    const adjustableLoads=effective.loads.filter(load=>load.inService),missingEligibility=adjustableLoads.filter(load=>load.activeBalanceEligibility===undefined),eligibleLoads=adjustableLoads.filter(load=>load.activeBalanceEligibility===true),fixedLoads=adjustableLoads.filter(load=>load.activeBalanceEligibility===false),activeBalanceIslands=outputs.map(o=>({islandId:o.part.islandId,eligibilityComplete:o.part.model.activeBalanceEligibilityComplete===true,eligibleLoadMw:Array.from(o.part.model.activeBalanceEligibleLoadMw||[]).reduce((sum,value)=>sum+value,0),iterations:o.numerical.activeBalanceIterations??0,finalMismatchMw:o.numerical.activeBalanceMismatchMw??null,adjustments:o.numerical.activeBalanceLoadAdjustmentsMw?.flatMap((mw,bus)=>Math.abs(mw)>1e-9?[{busId:o.part.buses[bus]?.id??null,loadAdjustmentMw:mw}]:[])??[]})),balanceWasApplied=activeBalanceIslands.some(island=>island.iterations>0),distributedRequested=fullAcSettings?.activeBalancingMode==='DISTRIBUTED_ADJUSTABLE_LOADS';
    const fixedQObserved=effective.diagnostics?.some(row=>row.code==='ACTIVE_BALANCE_FIXED_Q_OBSERVED')===true;
    const balanceFailed=balanceWasApplied&&activeBalanceIslands.some(island=>island.finalMismatchMw==null||Math.abs(island.finalMismatchMw)>((fullAcSettings?.nodalToleranceKva??5)/1000)),activeBalanceFidelity=distributedRequested?(missingEligibility.length?'MISSING_ELIGIBILITY':balanceFailed?'PARTIAL_NOT_CONVERGED':balanceWasApplied?fixedQObserved?'SOURCE_FIXED_Q_OBSERVED':'PARTIAL_Q_SCALING_UNVERIFIED':eligibleLoads.length?'NOT_APPLIED':'NO_ADJUSTABLE_LOADS'):'REFERENCE_ONLY',activeBalanceDiagnostic=distributedRequested?(missingEligibility.length?'ACTIVE_BALANCE_ELIGIBILITY_MISSING':balanceFailed?'ACTIVE_BALANCE_NOT_CONVERGED':balanceWasApplied?(fixedQObserved?null:'ACTIVE_BALANCE_Q_SCALING_UNVERIFIED'):eligibleLoads.length?'ACTIVE_BALANCE_NOT_APPLIED':'ACTIVE_BALANCE_NO_ELIGIBLE_LOADS'):null,effectiveBalanceMode=balanceWasApplied?'DISTRIBUTED_ADJUSTABLE_LOADS':'SINGLE_REFERENCE';
    first.diagnostics.activeBalancing={requestedActiveBalancingMode:fullAcSettings?.activeBalancingMode??'SINGLE_REFERENCE',effectiveActiveBalancingMode:effectiveBalanceMode,activeBalanceFidelity,requestedMode:fullAcSettings?.activeBalancingMode??'SINGLE_REFERENCE',effectiveMode:effectiveBalanceMode,fidelity:activeBalanceFidelity,eligibleLoadCount:eligibleLoads.length,fixedLoadCount:fixedLoads.length,missingEligibilityCount:missingEligibility.length,eligibilitySources:[...new Set(adjustableLoads.map(load=>load.activeBalanceEligibilitySource).filter(Boolean))],iterations:activeBalanceIslands.reduce((sum,island)=>sum+island.iterations,0),islands:activeBalanceIslands,diagnosticCode:activeBalanceDiagnostic,finalCorrections:outputs.reduce((sum,o)=>sum+(o.controlled.timings.finalBalanceCorrections??0),0)};
    first.diagnostics.finalControlRevalidation={perIsland:outputs.map(o=>o.controlled.finalRevalidation??null),revalidatedControllerCount:outputs.reduce((sum,o)=>sum+(o.controlled.finalRevalidation?.revalidatedControllerCount??0),0),controlResidualCount:outputs.reduce((sum,o)=>sum+(o.controlled.finalRevalidation?.controlResidualCount??0),0)};
    if(distributedRequested&&activeBalanceDiagnostic)first.warnings.push(missingEligibility.length?'ACTIVE_BALANCE_ELIGIBILITY_MISSING: adjustable-load eligibility is absent; calculation used single-reference balancing.':balanceFailed?'ACTIVE_BALANCE_NOT_CONVERGED: distributed active balancing stopped before the reference P target was met.':balanceWasApplied?'ACTIVE_BALANCE_Q_SCALING_UNVERIFIED: P balancing ran over sourced adjustable loads; Q response is not claimed.':eligibleLoads.length?'ACTIVE_BALANCE_NOT_APPLIED: no eligible-load participation was available in solved islands.':'ACTIVE_BALANCE_NO_ELIGIBLE_LOADS: all in-service loads are fixed.');
    first.diagnostics.externalGridResults=outputs.flatMap(o=>{
      const grids=o.part.externalGrids??[],reference=grids.find(grid=>grid.isReference);
      return grids.map(grid=>{const solvedP=o.numerical.P?.[grid.index],solvedQ=o.numerical.Q?.[grid.index],loadAdjustment=o.numerical.activeBalanceLoadAdjustmentsMw?.[grid.index]??0,fixedP=o.part.model.pSpec[grid.index]-(reference?.index===grid.index?reference.pMw:0)-loadAdjustment,fixedQ=o.part.model.qSpec[grid.index]-(reference?.index===grid.index?reference.qMvar:0),pMw=reference?.id===grid.id&&solvedP!=null?solvedP-fixedP:grid.pMw,qMvar=reference?.id===grid.id&&solvedQ!=null?solvedQ-fixedQ:grid.qMvar,hitLimit=reference?.id===grid.id&&o.numerical.pvToPq?.some(row=>row.bus===grid.index&&Math.abs(row.qLimit-qMvar)<=.03);return{id:grid.id,name:grid.name,busId:o.part.buses[grid.index]?.id??grid.bus,pMw,qMvar,voltagePu:o.numerical.Vm?.[grid.index]??null,qLimitState:hitLimit?(Math.abs(qMvar-(grid.qMin??Infinity))<=.03?'QMIN_LIMITED':'QMAX_LIMITED'):'VOLTAGE_CONTROL',isReference:grid.isReference,qMin:grid.qMin,qMax:grid.qMax};});
    });
    const islandDiagnostics=first.diagnostics.islands;if(Array.isArray(islandDiagnostics))for(const diagnostic of islandDiagnostics){if(!diagnostic||typeof diagnostic!=='object')continue;const row=diagnostic as {islandId:string;status:string;iterations:number|null};const found=outputs.find(o=>o.part.islandId===row.islandId);if(found){row.status=found.numerical.converged?(row.status==='MULTIPLE_REFERENCE_PARTIAL'?row.status:'CONVERGED'):found.numerical.status;row.iterations=found.numerical.iterations;}}
    const handled=new Set(outputs.flatMap(o=>o.controlled.controllers.map(c=>c.id))),controllerRows:ControlDiagnostic[]=outputs.flatMap(o=>o.controlled.controllers);
    for(const c of effective.stationControllers.filter(c=>c.inService&&!handled.has(c.id))){const mapping=mappings.find(m=>m.id===c.id);controllerRows.push({id:c.id,controllerId:c.id,remoteBus:c.remoteBus,islandId:mapping?.islandId??null,targetVpu:c.vmSet,initialVpu:null,finalVpu:null,voltageResidualPu:null,initialQ:null,finalQ:null,qMin:null,qMax:null,outerRounds:0,status:mapping?.islandId?'NO_REFERENCE_ISLAND':'REMOTE_BUS_UNRESOLVED',supported:false,unitIds:[...c.unitIds],actuatorBus:null,actuatorBuses:[],remoteBusIndex:null,participationKi:{},jacobianDimension:null,linearMethod:null,linearIterations:null,linearResidual:null,iluMinimumPivot:null,effectiveSlope:null,individualDvDqi:{},elapsedSensitivityMs:null,failureReason:null});}
    const supported=controllerRows.filter(c=>c.supported),residuals=supported.map(c=>Math.abs(c.voltageResidualPu??NaN)).filter(Number.isFinite),saturated=supported.filter(c=>c.status==='SATURATED_QMIN'||c.status==='SATURATED_QMAX').length,outerRounds=outputs.reduce((sum,o)=>sum+o.controlled.outerRounds,0);
    first.diagnostics.stationControllerResults=controllerRows;
    const statusCounts=Object.fromEntries([...new Set(controllerRows.map(c=>c.status))].sort().map(status=>[status,controllerRows.filter(c=>c.status===status).length]));
    const failureReasonCounts=Object.fromEntries([...new Set(controllerRows.map(c=>c.failureReason).filter(Boolean))].map(reason=>[reason,controllerRows.filter(c=>c.failureReason===reason).length]));
    const sourceById=new Map(effective.stationControllers.map(c=>[c.id,c])),droopRows=controllerRows.filter(c=>sourceById.get(c.id)?.droopModeRaw===1);
    const qSources=[...new Set(supported.map(c=>c.qDistributionSource).filter(Boolean))];
    first.diagnostics.stationControllerSummary={...(first.diagnostics.stationControllerSummary as object),active:controllerRows.length,zeroDroopActive:controllerRows.filter(c=>sourceById.get(c.id)?.droopModeRaw===0).length,zeroDroopSemanticallySupported:controllerRows.filter(c=>sourceById.get(c.id)?.droopModeRaw===0&&c.supported).length,integratedControllers:outputs.reduce((sum,o)=>sum+(o.controlled.integratedControllers||0),0),controlLimitRestarts:outputs.reduce((sum,o)=>sum+(o.controlled.controlLimitRestarts||0),0),numericallyControllable:supported.filter(c=>!['ROLLED_BACK_TO_LOCAL_PV','CONTROL_SOLVE_FAILED'].includes(c.status)).length,supported:supported.length,satisfied:supported.filter(c=>c.status==='SATISFIED').length,saturated,qLimitSaturated:saturated,saturatedQMin:supported.filter(c=>c.status==='SATURATED_QMIN').length,saturatedQMax:supported.filter(c=>c.status==='SATURATED_QMAX').length,noReactiveHeadroom:supported.filter(c=>c.status==='NO_REACTIVE_HEADROOM').length,unsupportedProfile:controllerRows.filter(c=>c.status==='UNSUPPORTED_PROFILE').length,localPvConflict:controllerRows.filter(c=>c.status==='LOCAL_PV_CONFLICT').length,rolledBack:controllerRows.filter(c=>c.status==='ROLLED_BACK_TO_LOCAL_PV').length,unsupported:controllerRows.length-supported.length,droopActive:droopRows.length,droopSafeCandidates:droopRows.filter(c=>c.supported).length,droopControlled:droopRows.filter(c=>['SATISFIED','SATURATED_QMIN','SATURATED_QMAX','MAX_OUTER_ROUNDS'].includes(c.status)).length,remoteConflict:droopRows.filter(c=>c.status==='REMOTE_CONTROL_CONFLICT').length,qLimitMissing:droopRows.filter(c=>{const source=sourceById.get(c.id);return source?.unitIds.some(id=>{const unit=effective.generators.find(g=>g.id===id);return unit?.inService&&(unit.qMin==null||unit.qMax==null);});}).length,outerControlRounds:outerRounds,maxVoltageResidualPu:residuals.length?Math.max(...residuals):null,meanVoltageResidualPu:residuals.length?residuals.reduce((a,b)=>a+b,0)/residuals.length:null,statusCounts,failureReasonCounts,controlSolveFailure:controllerRows.find(c=>c.controlSolveFailure)?.controlSolveFailure??null,ownershipUnallocatedMvar:supported.reduce((sum,c)=>sum+(c.ownershipUnallocatedMvar||0),0),coupledSolveDiagnostics:outputs.flatMap(o=>o.controlled.coupledSystems||[]),mode:request.stationControlMode??'off',droop:'SELF_CUBICLE_PARTIAL',qDistribution:qSources.length===1?qSources[0]:qSources.length?'MIXED':'UNAVAILABLE'};
    const controllerSummary=first.diagnostics.stationControllerSummary as Record<string,unknown>;
    controllerSummary.implementation=request.stationControlImplementation??'SENSITIVITY';
    controllerSummary.mode=request.stationControlMode??fullAcSettings?.stationControlMode??'off';
    controllerSummary.semanticallyEligible=controllerRows.filter(c=>sourceById.get(c.id)?.droopModeRaw===0&&c.supported).length;
    controllerSummary.sensitivitySolved=controllerRows.filter(c=>sourceById.get(c.id)?.droopModeRaw===0&&c.linearResidual!=null&&c.linearResidual<=1e-6).length;
    controllerSummary.maxOuterRounds=controllerRows.filter(c=>c.status==='MAX_OUTER_ROUNDS').length;
    controllerSummary.stagnatedTrials=controllerRows.filter(c=>c.status==='STAGNATED_TRIAL').length;
    controllerSummary.classificationPasses=outputs.reduce((sum,o)=>sum+(o.controlled.classificationPasses??0),0);
    controllerSummary.classificationStable=outputs.every(o=>o.controlled.classificationStable!==false);
    const profileGroup=(rows:ControlDiagnostic[])=>({count:rows.length,statusCounts:Object.fromEntries([...new Set(rows.map(row=>row.status))].sort().map(status=>[status,rows.filter(row=>row.status===status).length])),reasonCounts:Object.fromEntries([...new Set(rows.map(row=>row.failureReason??row.status))].sort().map(reason=>[reason,rows.filter(row=>(row.failureReason??row.status)===reason).length]))});
    first.diagnostics.sourceProfileAccounting={totalInService:effective.stationControllers.filter(c=>c.inService).length,zeroDroop:profileGroup(controllerRows.filter(c=>sourceById.get(c.id)?.droopModeRaw===0)),droop:profileGroup(droopRows),note:'Group status/reason counts partition controllers; remote-conflict and missing-limit inventory flags can overlap.'};
    const provenances=outputs.map(o=>o.controlled.resultProvenance);
    first.diagnostics.resultProvenance=provenances.includes('BASELINE_FALLBACK')?'BASELINE_FALLBACK':provenances.includes('SENSITIVITY_STATION_CONTROL')?'SENSITIVITY_STATION_CONTROL':provenances.includes('INTEGRATED_STATION_CONTROL')?'INTEGRATED_STATION_CONTROL':provenances.includes('OWNERSHIP')?'OWNERSHIP':'LOCAL_PV';
    first.diagnostics.integratedFailure=outputs.find(o=>o.controlled.integratedFailure)?.controlled.integratedFailure??null;
    const solverBatches=outputs.flatMap(o=>o.controlled.sensitivitySolverDiagnostics||[]),rhsRows=solverBatches.flatMap(batch=>batch.rhs),quantile=(values:number[],p:number)=>{if(!values.length)return null;const sorted=values.sort((a,b)=>a-b),at=(sorted.length-1)*p,lo=Math.floor(at),hi=Math.ceil(at);return sorted[lo]+(sorted[hi]-sorted[lo])*(at-lo);};
    const methods:Record<string,number>={KLU_DIRECT_SUCCESS:0,ILU1_GMRES_SUCCESS:0,ILU2_GMRES_SUCCESS:0,ILU2_BICGSTAB_SUCCESS:0},failures:Record<string,number>={SENSITIVITY_RESIDUAL_TOO_HIGH:0,SENSITIVITY_LINEAR_SOLVE_FAILED:0};
    for(const batch of solverBatches){for(const[key,value]of Object.entries(batch.methodCounts))methods[key]=(methods[key]??0)+value;for(const[key,value]of Object.entries(batch.failureCounts))failures[key]=(failures[key]??0)+value;}
    first.diagnostics.sensitivitySolver={backend:solverBatches[0]?.backend??null,ordering:solverBatches[0]?.ordering??null,matrixDimension:solverBatches[0]?.dimension??null,matrixNnz:solverBatches[0]?.nnz??null,batchCount:solverBatches.length,factorizations:solverBatches.reduce((sum,batch)=>sum+batch.factorizations,0),totalRhsCount:solverBatches.reduce((sum,batch)=>sum+batch.rhsCount,0),uniqueRemoteRhsCount:rhsRows.length,distinctRemoteBusCount:new Set(rhsRows.map(row=>row.remoteBus)).size,cachedRhsHits:solverBatches.reduce((sum,batch)=>sum+batch.cachedRhsHits,0),methodCounts:methods,failureCounts:failures,medianIterations:quantile(rhsRows.map(row=>row.iterations),.5),p95Iterations:quantile(rhsRows.map(row=>row.iterations),.95),medianTrueResidual:quantile(rhsRows.map(row=>row.trueResidual).filter((value):value is number=>value!=null&&Number.isFinite(value)),.5),p95TrueResidual:quantile(rhsRows.map(row=>row.trueResidual).filter((value):value is number=>value!=null&&Number.isFinite(value)),.95),maxTrueResidual:rhsRows.reduce<number|null>((max,row)=>row.trueResidual==null?max:Math.max(max??0,row.trueResidual),null),orderingMs:solverBatches.reduce((sum,batch)=>sum+batch.orderingMs,0),cscConversionMs:solverBatches.reduce((sum,batch)=>sum+batch.cscConversionMs,0),symbolicFactorMs:solverBatches.reduce((sum,batch)=>sum+batch.symbolicFactorMs,0),numericFactorMs:solverBatches.reduce((sum,batch)=>sum+batch.numericFactorMs,0),directSolveMs:solverBatches.reduce((sum,batch)=>sum+batch.directSolveMs,0),ilu1FactorMs:solverBatches.reduce((sum,batch)=>sum+batch.ilu1FactorMs,0),ilu2FactorMs:solverBatches.reduce((sum,batch)=>sum+batch.ilu2FactorMs,0),iterativeSolveMs:solverBatches.reduce((sum,batch)=>sum+batch.iterativeSolveMs,0),fallbackCount:rhsRows.reduce((sum,row)=>sum+row.fallbackCount,0),rhs:rhsRows};
    const keys:(keyof ControlTimings)[]=['baseNrMs','controllerClassificationMs','jacobianBuildMs','rcmReorderMs','ilu1FactorMs','ilu2FactorMs','iluFactorMs','sensitivityIterativeSolveMs','cscConversionMs','symbolicFactorMs','numericFactorMs','directRhsSolveMs','sensitivitySolveMs','classificationNrMs','outerTrialNrMs','finalNrMs','controlLimitRestartNrMs','fullNrSolves','totalNewtonIterations','kluNewtonFactorizations','finalBalanceCorrections'];const timings=Object.fromEntries(keys.map(key=>[key,outputs.reduce((sum,o)=>sum+o.controlled.timings[key],0)]));Object.assign(timings,{prepareMs:preparedMs,resultMapMs:outputs.reduce((sum,o)=>sum+o.resultMapMs,0),totalMs:first.elapsedMs});
    first.diagnostics.timings=timings;first.diagnostics.fullNrSolves=outputs.reduce((sum,o)=>sum+o.controlled.timings.fullNrSolves,0);first.diagnostics.totalNewtonIterations=outputs.reduce((sum,o)=>sum+o.controlled.timings.totalNewtonIterations,0);first.diagnostics.kluNewtonFactorizations=outputs.reduce((sum,o)=>sum+o.controlled.timings.kluNewtonFactorizations,0);first.diagnostics.stationTrialAttempts=outputs.flatMap(o=>o.controlled.trialAttempts||[]);first.diagnostics.preparationMs=preparedMs;first.diagnostics.outerControlRounds=outerRounds;
    // Convergence is reported per concern. A converged Newton solve does not imply a
    // converged active balance or a converged station-controller operating point, and an
    // unresolved SL1 mismatch or remote-controller residual must not be presented as a
    // fully control-converged operating point.
    const activeBalanceConverged=!distributedRequested||activeBalanceDiagnostic===null;
    const pendingControlStatuses=['STAGNATED_TRIAL','MAX_OUTER_ROUNDS','CONTROL_SOLVE_FAILED','CONTROL_RESIDUAL_AFTER_FINAL_BALANCE'];
    const stationControlPending=controllerRows.some(row=>pendingControlStatuses.includes(row.status));
    const stationControlConverged=!stationControlPending&&(controllerSummary.mode==='off'||controllerRows.every(row=>!row.supported||['SATISFIED','SATURATED_QMIN','SATURATED_QMAX'].includes(row.status)));
    first.diagnostics.convergence={
      newtonRaphson:allConverged?'NR_CONVERGED':'NR_NOT_CONVERGED',
      activeBalance:activeBalanceConverged?'ACTIVE_BALANCE_CONVERGED':'ACTIVE_BALANCE_PARTIAL',
      stationControl:stationControlConverged?'STATION_CONTROL_CONVERGED':'STATION_CONTROL_PARTIAL',
      powerFactoryComparability:allConverged&&activeBalanceConverged&&stationControlConverged?'COMPARABLE':'NOT_FULLY_COMPARABLE',
      pendingControllerStatuses:Object.fromEntries([...new Set(controllerRows.map(row=>row.status))].sort().filter(status=>pendingControlStatuses.includes(status)).map(status=>[status,controllerRows.filter(row=>row.status===status).length])),
    };
    (first.quality as Record<string,unknown>).controlFidelity=stationControlConverged?'CONVERGED':'PARTIAL';
    const effectiveLimits=effectiveFullAcLimits(fullAcSettings??undefined),profileClaim=profileFidelity(fullAcSettings?.profile);
    first.diagnostics.effectiveLimits=effectiveLimits;
    first.diagnostics.unsupportedSettings={shared:unsupportedSharedSettings(),powerFlow:unsupportedFullAcSettings()};
    first.diagnostics.calculationProvenance={profile:fullAcSettings?.profile??null,profileFidelity:profileClaim.fidelity,profileLabel:profileClaim.label,profileLimits:profileClaim.limits,effectiveLimits,unsupportedSettings:first.diagnostics.unsupportedSettings,activeSettings:request.analysisSettings?{shared:request.analysisSettings.shared,powerFlow:fullAcSettings}:null,activeSettingsHash:request.analysisSettings?analysisSettingsHash(request.analysisSettings,'powerFlow'):null,calculationOptionsHash:request.identity.optionsHash,engine:this.name,engineVersion:this.version,modelHash:request.identity.modelHash,scenarioHash:request.identity.scenarioHash,studyCase:effective.studyCase??null,studyTime:null,studyTimeSource:null,effectiveActiveBalancingMode:effectiveBalanceMode,activeBalanceFidelity,stationControlMode:controllerSummary.mode,stationControlFidelity:controllerRows.some(row=>pendingControlStatuses.includes(row.status))?'PARTIAL':controllerSummary.mode==='off'?'NOT_APPLIED':controllerSummary.mode==='droop'?'PARTIAL_DROOP_MODELED':'PARTIAL_ZERO_DROOP',qLimitFidelity:'MONOTONIC_PV_TO_LIMITED; RELEASE_UNSUPPORTED'};
    return first;
  }
  async runDcPowerFlow(request:AnalysisRequest,onProgress:Progress=()=>{}){return runReduced(request,'dc',onProgress);}
  async runFastAc(request:AnalysisRequest,onProgress:Progress=()=>{}){return runReduced(request,'fastAc',onProgress);}
}
