import type { AnalysisEngine, AnalysisRequest, Progress } from './engine';
import type { CanonicalNetwork } from '../../domain/model/network';
import { effectiveNetwork } from '../../domain/scenario/overlay';
import { prepareModel } from '../power-flow/preparation';
import { mapResults } from '../power-flow/results';
import {runStationControlledIslandV73,type ControlDiagnostic,type ControlTimings} from '../power-flow/station-controls-v73';
import { runReduced } from '../fast-ac/reduced-engine';
import {APP_VERSION} from '../../version';
export class BrowserJsPowerFlowEngine implements AnalysisEngine {
  readonly name='BrowserJsEngine';readonly version=APP_VERSION;
  capabilities(network:CanonicalNetwork){return network.capabilities;}
  async runPowerFlow(request:AnalysisRequest,onProgress:Progress=()=>{}){
    onProgress('MODEL');const start=performance.now(),effective=effectiveNetwork(request.network,request.scenario);onProgress('TOPOLOGY');
    const built=prepareModel(effective),preparedMs=performance.now()-start;onProgress('INIT');
    const mappings=built.diagnostics.stationControllerMappings as {id:string;islandId:string|null;solverBusIndex:number|null}[],islandModels=[built,...(built.additionalIslands||[])],outputs=islandModels.map(part=>{
      const controlled=runStationControlledIslandV73(effective,part,mappings,request.stationControlMode??'zeroDroop',(stage,detail)=>onProgress(stage==='YBUS_READY'?'YBUS':stage==='Q_LIMIT_UPDATE'?'Q_LIMIT':stage==='STATION_CONTROL'?'OUTER_CONTROL':'INNER_NR',{...detail,islandId:part.islandId}),request.stationControlImplementation??'SENSITIVITY');
      const numerical=controlled.result,mapStart=performance.now(),mapped=mapResults(controlled.prepared,numerical,request.identity);return{part:controlled.prepared,numerical,mapped,controlled,resultMapMs:performance.now()-mapStart};
    });
    onProgress('RESULT');const first=outputs[0].mapped,allConverged=outputs.every(o=>o.numerical.converged);
    for(const o of outputs.slice(1)){first.buses.push(...o.mapped.buses);first.branches.push(...o.mapped.branches);first.generators.push(...o.mapped.generators);first.warnings.push(...o.mapped.warnings);}
    first.converged=allConverged;first.status=allConverged?'CONVERGED_FULL_NR':outputs.length>1?'PARTIAL_ISLAND_FAILURE':first.status;
    first.iterations=outputs.reduce((sum,o)=>sum+o.numerical.iterations,0);first.rounds=Math.max(...outputs.map(o=>o.numerical.rounds));first.elapsedMs=performance.now()-start;
    first.maxMismatchMw=outputs.reduce<number|null>((max,o)=>o.numerical.maxMismatchMW==null?max:max==null?o.numerical.maxMismatchMW:Math.max(max,o.numerical.maxMismatchMW),null);
    first.quality.numericalStatus=allConverged?'CONVERGED':'NOT_CONVERGED';
    const islandDiagnostics=first.diagnostics.islands;if(Array.isArray(islandDiagnostics))for(const diagnostic of islandDiagnostics){if(!diagnostic||typeof diagnostic!=='object')continue;const row=diagnostic as {islandId:string;status:string;iterations:number|null};const found=outputs.find(o=>o.part.islandId===row.islandId);if(found){row.status=found.numerical.converged?(row.status==='MULTIPLE_REFERENCE_PARTIAL'?row.status:'CONVERGED'):found.numerical.status;row.iterations=found.numerical.iterations;}}
    const handled=new Set(outputs.flatMap(o=>o.controlled.controllers.map(c=>c.id))),controllerRows:ControlDiagnostic[]=outputs.flatMap(o=>o.controlled.controllers);
    for(const c of effective.stationControllers.filter(c=>c.inService&&!handled.has(c.id))){const mapping=mappings.find(m=>m.id===c.id);controllerRows.push({id:c.id,controllerId:c.id,remoteBus:c.remoteBus,islandId:mapping?.islandId??null,targetVpu:c.vmSet,initialVpu:null,finalVpu:null,voltageResidualPu:null,initialQ:null,finalQ:null,qMin:null,qMax:null,outerRounds:0,status:mapping?.islandId?'NO_REFERENCE_ISLAND':'REMOTE_BUS_UNRESOLVED',supported:false,unitIds:[...c.unitIds],actuatorBus:null,actuatorBuses:[],remoteBusIndex:null,participationKi:{},jacobianDimension:null,linearMethod:null,linearIterations:null,linearResidual:null,iluMinimumPivot:null,effectiveSlope:null,individualDvDqi:{},elapsedSensitivityMs:null,failureReason:null});}
    const supported=controllerRows.filter(c=>c.supported),residuals=supported.map(c=>Math.abs(c.voltageResidualPu??NaN)).filter(Number.isFinite),saturated=supported.filter(c=>c.status==='SATURATED_QMIN'||c.status==='SATURATED_QMAX').length,outerRounds=outputs.reduce((sum,o)=>sum+o.controlled.outerRounds,0);
    first.diagnostics.stationControllerResults=controllerRows;
    const statusCounts=Object.fromEntries([...new Set(controllerRows.map(c=>c.status))].sort().map(status=>[status,controllerRows.filter(c=>c.status===status).length]));
    const failureReasonCounts=Object.fromEntries([...new Set(controllerRows.map(c=>c.failureReason).filter(Boolean))].map(reason=>[reason,controllerRows.filter(c=>c.failureReason===reason).length]));
    const sourceById=new Map(effective.stationControllers.map(c=>[c.id,c])),droopRows=controllerRows.filter(c=>sourceById.get(c.id)?.droopModeRaw===1);
    first.diagnostics.stationControllerSummary={...(first.diagnostics.stationControllerSummary as object),active:controllerRows.length,zeroDroopActive:controllerRows.filter(c=>sourceById.get(c.id)?.droopModeRaw===0).length,zeroDroopSemanticallySupported:controllerRows.filter(c=>sourceById.get(c.id)?.droopModeRaw===0&&c.supported).length,integratedControllers:outputs.reduce((sum,o)=>sum+(o.controlled.integratedControllers||0),0),controlLimitRestarts:outputs.reduce((sum,o)=>sum+(o.controlled.controlLimitRestarts||0),0),numericallyControllable:supported.filter(c=>!['ROLLED_BACK_TO_LOCAL_PV','CONTROL_SOLVE_FAILED'].includes(c.status)).length,supported:supported.length,satisfied:supported.filter(c=>c.status==='SATISFIED').length,saturated,qLimitSaturated:saturated,saturatedQMin:supported.filter(c=>c.status==='SATURATED_QMIN').length,saturatedQMax:supported.filter(c=>c.status==='SATURATED_QMAX').length,noReactiveHeadroom:supported.filter(c=>c.status==='NO_REACTIVE_HEADROOM').length,unsupportedProfile:controllerRows.filter(c=>c.status==='UNSUPPORTED_PROFILE').length,localPvConflict:controllerRows.filter(c=>c.status==='LOCAL_PV_CONFLICT').length,rolledBack:controllerRows.filter(c=>c.status==='ROLLED_BACK_TO_LOCAL_PV').length,unsupported:controllerRows.length-supported.length,droopActive:droopRows.length,droopSafeCandidates:droopRows.filter(c=>c.supported).length,droopControlled:droopRows.filter(c=>['SATISFIED','SATURATED_QMIN','SATURATED_QMAX','MAX_OUTER_ROUNDS'].includes(c.status)).length,remoteConflict:droopRows.filter(c=>c.status==='REMOTE_CONTROL_CONFLICT').length,qLimitMissing:droopRows.filter(c=>{const source=sourceById.get(c.id);return source?.unitIds.some(id=>{const unit=effective.generators.find(g=>g.id===id);return unit?.inService&&(unit.qMin==null||unit.qMax==null);});}).length,outerControlRounds:outerRounds,maxVoltageResidualPu:residuals.length?Math.max(...residuals):null,meanVoltageResidualPu:residuals.length?residuals.reduce((a,b)=>a+b,0)/residuals.length:null,statusCounts,failureReasonCounts,controlSolveFailure:controllerRows.find(c=>c.controlSolveFailure)?.controlSolveFailure??null,ownershipUnallocatedMvar:supported.reduce((sum,c)=>sum+(c.ownershipUnallocatedMvar||0),0),coupledSolveDiagnostics:outputs.flatMap(o=>o.controlled.coupledSystems||[]),mode:request.stationControlMode??'zeroDroop',droop:'SAFE_EXPERIMENTAL_ONLY',qDistribution:'DISPATCHED_ACTIVE_POWER'};
    const controllerSummary=first.diagnostics.stationControllerSummary as Record<string,unknown>;
    controllerSummary.implementation=request.stationControlImplementation??'SENSITIVITY';
    controllerSummary.semanticallyEligible=controllerRows.filter(c=>sourceById.get(c.id)?.droopModeRaw===0&&c.supported).length;
    controllerSummary.sensitivitySolved=controllerRows.filter(c=>sourceById.get(c.id)?.droopModeRaw===0&&c.linearResidual!=null&&c.linearResidual<=1e-6).length;
    controllerSummary.maxOuterRounds=controllerRows.filter(c=>c.status==='MAX_OUTER_ROUNDS').length;
    const profileGroup=(rows:ControlDiagnostic[])=>({count:rows.length,statusCounts:Object.fromEntries([...new Set(rows.map(row=>row.status))].sort().map(status=>[status,rows.filter(row=>row.status===status).length])),reasonCounts:Object.fromEntries([...new Set(rows.map(row=>row.failureReason??row.status))].sort().map(reason=>[reason,rows.filter(row=>(row.failureReason??row.status)===reason).length]))});
    first.diagnostics.sourceProfileAccounting={totalInService:effective.stationControllers.filter(c=>c.inService).length,zeroDroop:profileGroup(controllerRows.filter(c=>sourceById.get(c.id)?.droopModeRaw===0)),droop:profileGroup(droopRows),note:'Group status/reason counts partition controllers; remote-conflict and missing-limit inventory flags can overlap.'};
    const provenances=outputs.map(o=>o.controlled.resultProvenance);
    first.diagnostics.resultProvenance=provenances.includes('BASELINE_FALLBACK')?'BASELINE_FALLBACK':provenances.includes('SENSITIVITY_STATION_CONTROL')?'SENSITIVITY_STATION_CONTROL':provenances.includes('INTEGRATED_STATION_CONTROL')?'INTEGRATED_STATION_CONTROL':provenances.includes('OWNERSHIP')?'OWNERSHIP':'LOCAL_PV';
    first.diagnostics.integratedFailure=outputs.find(o=>o.controlled.integratedFailure)?.controlled.integratedFailure??null;
    const solverBatches=outputs.flatMap(o=>o.controlled.sensitivitySolverDiagnostics||[]),rhsRows=solverBatches.flatMap(batch=>batch.rhs),quantile=(values:number[],p:number)=>{if(!values.length)return null;const sorted=values.sort((a,b)=>a-b),at=(sorted.length-1)*p,lo=Math.floor(at),hi=Math.ceil(at);return sorted[lo]+(sorted[hi]-sorted[lo])*(at-lo);};
    const methods:Record<string,number>={ILU1_GMRES_SUCCESS:0,ILU2_GMRES_SUCCESS:0,ILU2_BICGSTAB_SUCCESS:0},failures:Record<string,number>={SENSITIVITY_RESIDUAL_TOO_HIGH:0,SENSITIVITY_LINEAR_SOLVE_FAILED:0};
    for(const batch of solverBatches){for(const[key,value]of Object.entries(batch.methodCounts))methods[key]=(methods[key]??0)+value;for(const[key,value]of Object.entries(batch.failureCounts))failures[key]=(failures[key]??0)+value;}
    first.diagnostics.sensitivitySolver={ordering:solverBatches[0]?.ordering??null,matrixDimension:solverBatches[0]?.dimension??null,matrixNnz:solverBatches[0]?.nnz??null,batchCount:solverBatches.length,totalRhsCount:solverBatches.reduce((sum,batch)=>sum+batch.rhsCount,0),uniqueRemoteRhsCount:rhsRows.length,distinctRemoteBusCount:new Set(rhsRows.map(row=>row.remoteBus)).size,cachedRhsHits:solverBatches.reduce((sum,batch)=>sum+batch.cachedRhsHits,0),methodCounts:methods,failureCounts:failures,medianIterations:quantile(rhsRows.map(row=>row.iterations),.5),p95Iterations:quantile(rhsRows.map(row=>row.iterations),.95),medianTrueResidual:quantile(rhsRows.map(row=>row.trueResidual).filter((value):value is number=>value!=null&&Number.isFinite(value)),.5),p95TrueResidual:quantile(rhsRows.map(row=>row.trueResidual).filter((value):value is number=>value!=null&&Number.isFinite(value)),.95),orderingMs:solverBatches.reduce((sum,batch)=>sum+batch.orderingMs,0),ilu1FactorMs:solverBatches.reduce((sum,batch)=>sum+batch.ilu1FactorMs,0),ilu2FactorMs:solverBatches.reduce((sum,batch)=>sum+batch.ilu2FactorMs,0),iterativeSolveMs:solverBatches.reduce((sum,batch)=>sum+batch.iterativeSolveMs,0),fallbackCount:rhsRows.reduce((sum,row)=>sum+row.fallbackCount,0),rhs:rhsRows};
    const keys:(keyof ControlTimings)[]=['baseNrMs','controllerClassificationMs','jacobianBuildMs','rcmReorderMs','ilu1FactorMs','ilu2FactorMs','iluFactorMs','sensitivityIterativeSolveMs','sensitivitySolveMs','outerTrialNrMs','finalNrMs','controlLimitRestartNrMs'];const timings=Object.fromEntries(keys.map(key=>[key,outputs.reduce((sum,o)=>sum+o.controlled.timings[key],0)]));Object.assign(timings,{prepareMs:preparedMs,resultMapMs:outputs.reduce((sum,o)=>sum+o.resultMapMs,0),totalMs:first.elapsedMs});
    first.diagnostics.timings=timings;first.diagnostics.stationTrialAttempts=outputs.flatMap(o=>o.controlled.trialAttempts||[]);first.diagnostics.preparationMs=preparedMs;first.diagnostics.outerControlRounds=outerRounds;return first;
  }
  async runDcPowerFlow(request:AnalysisRequest,onProgress:Progress=()=>{}){return runReduced(request,'dc',onProgress);}
  async runFastAc(request:AnalysisRequest,onProgress:Progress=()=>{}){return runReduced(request,'fastAc',onProgress);}
}
