import type { CalculationResult } from '../../domain/results/types';
import { voltageBand, type VoltageBand } from '../../domain/model/voltage-band';

export type ReferenceKind='bus'|'line'|'transformer'|'generator';
export interface PowerFactoryReferenceMetadata { modelId?:string; modelName?:string; modelHash?:string; studyCase?:string; studyTime?:string; topologyHash?:string; scenarioHash?:string; sourceFile?:string; calculationSettingsHash?:string; calculationSettingsHashAlgorithm?:string; loadFlowSettingsRaw?:string; loadFlowSettingsSemantic?:string; [key:string]:string|undefined }
export type ComLdfOption='i_power'|'iPbalancing'|'iopt_lim'|'itrlx'|'ictrlx'|'iopt_net'|'iopt_chctr'|'iShowOutLoopMsg'|'iopt_initOPF'|'iItAlgStag'|'iInterChg'|'iInterType'|'iopt_apdist'|'iopt_plim'|'iopt_pq'|'iopt_tem'|'iopt_fls'|'iopt_at'|'iopt_asht'|'iPST_at'|'nsteps'|'errlf'|'erreq';
export interface PowerFactoryLoadFlowSettings { raw:Partial<Record<ComLdfOption,number|string>>; semantic:Record<string,string>; profile:'POWERFACTORY_TEIAS_PARITY'|'UNKNOWN' }
export interface PowerFactoryReferenceRecord {
  kind:ReferenceKind; fid?:string; name:string; nominalKv?:number; voltageKv?:number; voltagePu?:number; angleDeg?:number;
  pFromMw?:number; qFromMvar?:number; pToMw?:number; qToMvar?:number; pHvMw?:number; qHvMvar?:number; pLvMw?:number; qLvMvar?:number;
  currentFromA?:number; currentToA?:number; currentHvA?:number; currentLvA?:number; ratedCurrentFromA?:number; ratedCurrentToA?:number; loadingPercent?:number;
  pLossMw?:number; qLossMvar?:number; tapPosition?:number; tapRatio?:number; phaseShiftDeg?:number; pMw?:number; qMvar?:number;
  calculationBusFid?:string; calculationBusKey?:string; electricalBusKey?:string; physicalTerminalFid?:string; physicalTerminalName?:string;
  physicalTerminalFids?:string[]; resultBearingPhysicalTerminalCount?:number; fids?:string[]; conflictedMetrics?:string[];
  fromBusFid?:string; toBusFid?:string; fromCalculationBusFid?:string; toCalculationBusFid?:string; fromCalculationBusKey?:string; toCalculationBusKey?:string;
  connectedBusFid?:string; connectedCalculationBusKey?:string; controlModeRaw?:string;
  ytmName?:string; siteName?:string; substationName?:string; voltageLevelKv?:number; feederName?:string; sourceClass?:string; isReferenceBus?:boolean;
  resultAvailable?:boolean; raw?:Record<string,string>;
}
export interface ReferenceValueConflict {calculationBusKey:string;metric:string;values:number[];fids:string[]}
export interface PowerFactoryLoadRecord { fid:string; name?:string; sourceClass?:string; adjustedByLoadScaling?:boolean; activeBalanceEligibility?:boolean; iScaleRaw?:string; scaleRaw?:string; scale0Raw?:string; initialPMw?:number; initialQMvar?:number; finalPMw?:number; finalQMvar?:number; balancingParticipation?:number|string; raw:Record<string,string> }
export interface PowerFactoryReference { metadata:PowerFactoryReferenceMetadata; records:PowerFactoryReferenceRecord[]; loadRecords?:PowerFactoryLoadRecord[]; valueConflicts?:ReferenceValueConflict[] }
const comLdfOptions:ComLdfOption[]=['i_power','iPbalancing','iopt_lim','itrlx','ictrlx','iopt_net','iopt_chctr','iShowOutLoopMsg','iopt_initOPF','iItAlgStag','iInterChg','iInterType','iopt_apdist','iopt_plim','iopt_pq','iopt_tem','iopt_fls','iopt_at','iopt_asht','iPST_at','nsteps','errlf','erreq'];
/** Decodes only explicitly exported semantic labels. Numeric ComLdf enums are kept raw and never assigned meanings here. */
export function powerFactoryLoadFlowSettings(reference:PowerFactoryReference):PowerFactoryLoadFlowSettings {
 const metadata=reference.metadata,raw:Partial<Record<ComLdfOption,number|string>>={};
 let source:Record<string,unknown>={};try{const parsed=JSON.parse(metadata.loadFlowSettingsRaw||'{}');if(parsed&&typeof parsed==='object'&&!Array.isArray(parsed))source=parsed as Record<string,unknown>;}catch{/* preserve invalid/raw source only through metadata */}
 for(const key of comLdfOptions){const value=source[key]??metadata[norm(`raw.ComLdf.${key}`)]??metadata[norm(`ComLdf.${key}`)];if(typeof value==='number'&&Number.isFinite(value)||typeof value==='string'&&value.trim())raw[key]=value as number|string;}
 const semantic:Record<string,string>={};try{const parsed=JSON.parse(metadata.loadFlowSettingsSemantic||'{}');if(parsed&&typeof parsed==='object'&&!Array.isArray(parsed))for(const[key,value]of Object.entries(parsed))if(typeof value==='string'&&value.trim())semantic[key]=value.trim();}catch{/* no semantic interpretation of malformed metadata */}
 return{raw,semantic,profile:semantic.profile==='POWERFACTORY_TEIAS_PARITY'?'POWERFACTORY_TEIAS_PARITY':'UNKNOWN'};
}
type Metric=Exclude<keyof PowerFactoryReferenceRecord,'kind'|'fid'|'fids'|'name'|'raw'|'conflictedMetrics'|'physicalTerminalFids'|'calculationBusFid'|'calculationBusKey'|'electricalBusKey'|'physicalTerminalFid'|'physicalTerminalName'|'fromBusFid'|'toBusFid'|'fromCalculationBusFid'|'toCalculationBusFid'|'fromCalculationBusKey'|'toCalculationBusKey'|'connectedBusFid'|'connectedCalculationBusKey'|'controlModeRaw'|'ytmName'|'siteName'|'substationName'|'feederName'|'sourceClass'>;
type ComparisonMetric=Metric|'alignedAngleDeg';
export type MatchMethod='FID'|'CALCULATION_BUS_KEY'|'ELECTRICAL_BUS_KEY'|'PHYSICAL_TERMINAL'|'ENDPOINT_HIERARCHY'|'EXACT_NAME';
export interface MetricError {kind:ReferenceKind;metric:ComparisonMetric;count:number;mae:number;maxAbsoluteError:number;p95AbsoluteError:number;meanBias:number;unit:string;semantics:string}
export interface MatchIssue {kind:ReferenceKind;fid?:string;name:string;reason:'UNMATCHED'|'AMBIGUOUS';source:'REFERENCE'|'ACTUAL';}
export interface MetricPair {gridAnalyzer:number|null;powerFactory:number|null;delta:number|null;absoluteDelta:number|null;deltaPercent:number|null;unit:string;comparable:boolean;semantics:string}
export interface ComparisonRow {
 kind:ReferenceKind;status:'MATCHED'|'UNMATCHED_REFERENCE'|'UNMATCHED_ACTUAL'|'AMBIGUOUS';matchMethod?:MatchMethod;
 gridAnalyzerId?:string;powerFactoryFid?:string;gridAnalyzerName?:string;powerFactoryName?:string;
 hierarchy:{ytm?:string;tm?:string;voltageKv?:number;feeder?:string};
 topology:{calculationBusFid?:string;calculationBusKey?:string;electricalBusKey?:string;physicalTerminalFid?:string;from?:string;to?:string;powerFactoryFrom?:string;powerFactoryTo?:string};
 generatorControl?:{gridAnalyzerQState?:string;powerFactoryControlModeRaw?:string;gridAnalyzerBusId?:string;powerFactoryConnectedBusFid?:string;powerFactoryConnectedCalculationBusKey?:string;busMatch:'MATCHED'|'MISMATCHED'|'UNKNOWN'};
 metrics:Partial<Record<ComparisonMetric,MetricPair>>;
}
export interface PowerFactoryComparison {
 compatibility:{status:'COMPATIBLE'|'COMPARABLE_PARTIAL'|'BLOCKED'|'BLOCKED_CALCULATION_SETTINGS_MISMATCH'|'EXPLORATORY_ONLY';reasons:string[];compared:{modelId?:string;studyCase?:string;studyTime?:string;topologyHash?:string;calculationSettingsHash?:string}};
 matched:Record<ReferenceKind,number>;matchMethods:Partial<Record<MatchMethod,number>>;unmatchedActual:Record<ReferenceKind,number>;unmatched:MatchIssue[];ambiguous:MatchIssue[];
 summary:{matchedTotal:number;unmatchedReference:number;ambiguousReference:number;unmatchedActualTotal:number};metrics:MetricError[];voltageBands:(MetricError&{band:VoltageBand})[];
 rows:ComparisonRow[];referenceValueConflicts:ReferenceValueConflict[];
 angleAlignment:{method:'REFERENCE_BUS'|'MEDIAN'|'PER_ISLAND'|'NONE';offsetDeg:number|null;matchedBusCount:number;islands:{islandId:string;method:'REFERENCE_BUS'|'MEDIAN';offsetDeg:number;matchedBusCount:number}[]};
 quality:'BLOCKED'|'COMPARABLE_PARTIAL'|'EXPLORATORY_ONLY'|'AVAILABLE_NOT_ACCEPTED'|'BENCHMARKED_PARTIAL';
}
export interface ComparisonContext {modelId?:string;modelHash?:string;studyCase?:string;studyTime?:string;topologyHash?:string;scenarioHash?:string;calculationSettingsHash?:string;calculationSettingsHashAlgorithm?:string;calculationSettingsSemanticsAvailable?:boolean;activeBalanceEligibilityAvailable?:boolean;effectiveActiveBalancingMode?:string;controlContextReferenceMatched?:boolean}
const aliases:Record<string,string>={kind:'kind',type:'kind',class:'kind',objecttype:'kind',elementtype:'kind',fid:'fid',id:'fid',loc_name:'name',name:'name',objectname:'name',
 uknom:'nominalKv',nominalkv:'nominalKv',ratedvoltagekv:'nominalKv',ukv:'nominalKv',voltagekv:'voltageKv',u_kv:'voltageKv',voltagepu:'voltagePu',vm:'voltagePu',vm_pu:'voltagePu',angle:'angleDeg',angledeg:'angleDeg',va:'angleDeg',
 pfrommw:'pFromMw',pf:'pFromMw',p_from:'pFromMw',qfrommvar:'qFromMvar',qf:'qFromMvar',q_from:'qFromMvar',ptomw:'pToMw',pt:'pToMw',p_to:'pToMw',qtomvar:'qToMvar',qt:'qToMvar',q_to:'qToMvar',
 phvmw:'pHvMw',phv:'pHvMw',qhvmvar:'qHvMvar',qhv:'qHvMvar',plvmw:'pLvMw',plv:'pLvMw',qlvmvar:'qLvMvar',qlv:'qLvMvar',loading:'loadingPercent',loadingpercent:'loadingPercent',loading_pct:'loadingPercent',
 ifroma:'currentFromA',itoa:'currentToA',ihva:'currentHvA',ilva:'currentLvA',ratedcurrentfroma:'ratedCurrentFromA',ratedcurrenttoa:'ratedCurrentToA',plossmw:'pLossMw',qlossmvar:'qLossMvar',tapposition:'tapPosition',tapratio:'tapRatio',phaseshiftdeg:'phaseShiftDeg',
 pmw:'pMw',presultmw:'pMw',qmvar:'qMvar',qresultmvar:'qMvar',calculationbusfid:'calculationBusFid',calculationbuskey:'calculationBusKey',electricalbuskey:'electricalBusKey',physicalterminalfid:'physicalTerminalFid',physicalterminalname:'physicalTerminalName',frombusfid:'fromBusFid',tobusfid:'toBusFid',fromcalculationbusfid:'fromCalculationBusFid',tocalculationbusfid:'toCalculationBusFid',fromcalculationbuskey:'fromCalculationBusKey',tocalculationbuskey:'toCalculationBusKey',connectedbusfid:'connectedBusFid',connectedcalculationbuskey:'connectedCalculationBusKey',controlmoderaw:'controlModeRaw',
 ytmname:'ytmName',sitename:'siteName',substationname:'substationName',voltagelevelkv:'voltageLevelKv',feedername:'feederName',sourceclass:'sourceClass',isreferencebus:'isReferenceBus',resultavailable:'resultAvailable'};
const semanticBool=(value:unknown):boolean|undefined=>{if(value===true||value===1)return true;if(value===false||value===0)return false;if(typeof value==='string'){const v=value.trim().toLowerCase();if(['true','1','yes'].includes(v))return true;if(['false','0','no'].includes(v))return false;}return undefined;};
function toLoadRecord(row:Record<string,unknown>):PowerFactoryLoadRecord|undefined {
 const raw=Object.fromEntries(Object.entries(row).map(([k,v])=>[k,String(v??'')])),values:Record<string,unknown>={};for(const[k,v]of Object.entries(row))values[norm(k).replace(/_/g,'')]=v;
 const fid=String(values.fid??values.id??'').trim();if(!fid)return;
 const balance=semanticBool(values.adjustedbyloadscaling),eligibility=semanticBool(values.activebalanceeligibility),participation=values.balancingparticipation??values.participationfactor;
 const participationNumber=num(participation);
 return{fid,name:String(values.name??values.loc_name??'').trim()||undefined,sourceClass:String(values.sourceclass??'ElmLod'),adjustedByLoadScaling:balance,activeBalanceEligibility:eligibility,
  iScaleRaw:values.iscale==null?undefined:String(values.iscale),scaleRaw:values.scale==null?undefined:String(values.scale),scale0Raw:values.scale0==null?undefined:String(values.scale0),
  initialPMw:num(values.initialpmw??values.pinitialmw??values.initialp),initialQMvar:num(values.initialqmvar??values.qinitialmvar??values.initialq),finalPMw:num(values.finalpmw??values.pfinalmw??values.finalp),finalQMvar:num(values.finalqmvar??values.qfinalmvar??values.finalq),
  balancingParticipation:participationNumber??(participation==null?undefined:String(participation)),raw};
}
const norm=(s:string)=>s.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9_]/g,'');
const parseKind=(x:unknown):ReferenceKind|undefined=>{const s=String(x??'').toLowerCase();if(s.includes('generator')||s.includes('genstat')||s==='elmgenstat')return'generator';if(s.includes('bus')||s.includes('term')||s==='elmterm')return'bus';if(s.includes('tr')||s.includes('transformer'))return'transformer';if(s.includes('line')||s==='elmlne')return'line';};
const num=(x:unknown):number|undefined=>{if(typeof x==='number')return Number.isFinite(x)?x:undefined;if(typeof x!=='string'||!x.trim())return;const s=x.trim().replace(/\s/g,'');const normalized=s.includes(',')&&s.includes('.')?s.replace(/\./g,'').replace(',','.'):s.replace(',','.');const n=Number(normalized);return Number.isFinite(n)?n:undefined;};
function csv(text:string):Record<string,string>[] {const source=text.replace(/^\uFEFF/,'').replace(/^sep=([^\r\n]+)\r?\n/i,'');const first=source.split(/\r?\n/,1)[0]||'',delimiter=(first.match(/;/g)?.length||0)>(first.match(/,/g)?.length||0)?';':',';const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<source.length;i++){const c=source[i];if(c==='"'){if(quoted&&source[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===delimiter&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&source[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell='';}else cell+=c;}row.push(cell);if(row.some(v=>v.trim()))rows.push(row);const headers=(rows.shift()||[]).map(h=>h.trim());return rows.map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??''])));}
function toRecord(row:Record<string,unknown>,implicit?:ReferenceKind):PowerFactoryReferenceRecord|undefined {const raw=Object.fromEntries(Object.entries(row).map(([k,v])=>[k,String(v??'')]));const v:Record<string,unknown>={};for(const[k,value]of Object.entries(row)){const a=aliases[norm(k)];if(a)v[a]=value;}const kind=parseKind(v.kind)||implicit,name=String(v.name??'').trim();if(!kind||!name)return;const out:Record<string,unknown>={kind,name,raw};for(const[k,value]of Object.entries(v)){if(k==='kind'||k==='name')continue;if(['fid','calculationBusFid','calculationBusKey','electricalBusKey','physicalTerminalFid','physicalTerminalName','fromBusFid','toBusFid','fromCalculationBusFid','toCalculationBusFid','fromCalculationBusKey','toCalculationBusKey','connectedBusFid','connectedCalculationBusKey','controlModeRaw','ytmName','siteName','substationName','feederName','sourceClass'].includes(k)){if(value!=null&&String(value).trim())out[k]=String(value).trim();}else if(k==='isReferenceBus'||k==='resultAvailable'){out[k]=['1','true','yes'].includes(String(value).toLowerCase());}else{const n=num(value);if(n!==undefined)out[k]=n;}}return out as unknown as PowerFactoryReferenceRecord;}
const metaAliases:Record<string,keyof PowerFactoryReferenceMetadata>={modelid:'modelId',modelname:'modelName',modelhash:'modelHash',studycase:'studyCase',studytime:'studyTimeUtc',studytimelocal:'studyTime',topologyhash:'topologyHash',scenariohash:'scenarioHash',calculationsettingshash:'calculationSettingsHash',analysissettingshash:'calculationSettingsHash',calculationsettingshashalgorithm:'calculationSettingsHashAlgorithm',loadflowsettingsraw:'loadFlowSettingsRaw',loadflowsettingssemantic:'loadFlowSettingsSemantic'};
function deduplicateCalculationBuses(records:PowerFactoryReferenceRecord[]):{records:PowerFactoryReferenceRecord[];conflicts:ReferenceValueConflict[]}{const groups=new Map<string,PowerFactoryReferenceRecord[]>(),other:PowerFactoryReferenceRecord[]=[];for(const r of records){const busKey=r.electricalBusKey||r.calculationBusKey;if(r.kind==='bus'&&busKey){const group=groups.get(busKey)||[];group.push(r);groups.set(busKey,group);}else other.push(r);}const conflicts:ReferenceValueConflict[]=[],tolerance:Record<string,number>={voltagePu:1e-8,angleDeg:1e-6,voltageKv:1e-5,nominalKv:1e-5};for(const[key,group]of groups){const selected=group.find(r=>r.resultAvailable)||group[0],fids=[...new Set(group.flatMap(r=>[...(r.fid?[r.fid]:[]),...(r.fids||[])]))],terminals=[...new Set(group.flatMap(r=>[...(r.physicalTerminalFid?[r.physicalTerminalFid]:[]),...(r.physicalTerminalFids||[])]))],conflicted:string[]=[];selected.fids=fids;selected.physicalTerminalFids=terminals;selected.resultBearingPhysicalTerminalCount=group.reduce((sum,row)=>sum+(row.resultAvailable===true?1:0),0);for(const metric of ['nominalKv','voltageKv','voltagePu','angleDeg'] as const){const values=[...new Set(group.map(r=>r[metric]).filter((v):v is number=>typeof v==='number'))];if(values.length>1&&Math.max(...values)-Math.min(...values)>tolerance[metric]){conflicted.push(metric);delete selected[metric];conflicts.push({calculationBusKey:key,metric,values,fids});}}if(conflicted.length)selected.conflictedMetrics=conflicted;other.push(selected);}return{records:other,conflicts};}
export function importPowerFactoryReferenceDocument(text:string,sourceFile?:string):PowerFactoryReference {const clean=text.replace(/^\uFEFF/,'').trim();if(!clean)throw new Error('PowerFactory reference is empty.');const metadata:PowerFactoryReferenceMetadata={};if(sourceFile)metadata.sourceFile=sourceFile;let records:PowerFactoryReferenceRecord[]=[],loadRecords:PowerFactoryLoadRecord[]=[];
 if(clean[0]==='{'||clean[0]==='['){let parsed:unknown;try{parsed=JSON.parse(clean);}catch{throw new Error('PowerFactory reference JSON is invalid.');}const root=Array.isArray(parsed)?{records:parsed}:parsed as Record<string,unknown>;if(root&&typeof root==='object'){const obj=root as Record<string,unknown>;if(obj.metadata&&typeof obj.metadata==='object')Object.assign(metadata,obj.metadata);for(const[k,v]of Object.entries(obj)){if(k==='metadata')continue;if(Array.isArray(v)){const implicit=parseKind(k);for(const x of v)if(x&&typeof x==='object'){const row=x as Record<string,unknown>,rowKind=String(row.kind??row.class??row.sourceClass??'').toLowerCase();if(['loadrecords','elmloads'].includes(norm(k))||norm(k)==='loads'||rowKind.includes('load')){const load=toLoadRecord(row);if(load)loadRecords.push(load);}else{const rec=toRecord(row,implicit);if(rec)records.push(rec);}}}}}}
 else {for(const row of csv(clean)){const kind=String(row.kind??row.Type??'').toLowerCase();if(kind==='meta'){const key=norm(row.metaKey||row.MetaKey||''),value=row.metaValue||row.MetaValue||'';const field=metaAliases[key];if(field)metadata[field]=value;else if(key)metadata[key]=value;continue;}if(kind.includes('load')||norm(row.sourceClass||row.class||'')==='elmlod'){const load=toLoadRecord(row);if(load)loadRecords.push(load);continue;}const rec=toRecord(row);if(rec)records.push(rec);}}
 const deduplicated=deduplicateCalculationBuses(records);return{metadata,records:deduplicated.records,loadRecords,valueConflicts:deduplicated.conflicts};}
export function importPowerFactoryReference(text:string):PowerFactoryReferenceRecord[]{return importPowerFactoryReferenceDocument(text).records;}

interface Actual {kind:ReferenceKind;id:string;ids:string[];name:string;nominalKv:number;islandId?:string;siteIds:string[];from?:string;to?:string;qState?:string;connectedBus?:string;ratedFromA?:number|null;ratedToA?:number|null;fromIsHv?:boolean;values:Partial<Record<Metric,number>>;keys:Partial<Record<'calculationBusFid'|'calculationBusKey'|'electricalBusKey'|'physicalTerminalFid',string>>}
function actualRecords(result:CalculationResult):Actual[]{const buses:Actual[]=result.buses.map(b=>({kind:'bus',id:b.id,ids:[b.id,...b.terms],name:b.name,nominalKv:b.vnKv,islandId:b.islandId,siteIds:b.siteIds,values:{nominalKv:b.vnKv,voltageKv:b.vmPu*b.vnKv,voltagePu:b.vmPu,angleDeg:b.angleRad*180/Math.PI},keys:{calculationBusFid:b.id,calculationBusKey:b.id,electricalBusKey:b.id}}));const volts=new Map<string,number>(),islandByBus=new Map<string,string|undefined>();for(const b of result.buses){islandByBus.set(b.id,b.islandId);for(const id of [b.id,...b.terms])volts.set(id,b.vnKv);}const branches:Actual[]=result.branches.map(b=>{const tr=b.sourceClass.toLowerCase().includes('tr'),high=(volts.get(b.from)??b.vnKv)>=(volts.get(b.to)??b.vnKv),values:Partial<Record<Metric,number>>={pLossMw:b.pLoss,qLossMvar:b.qLoss,currentFromA:b.ifA,currentToA:b.itA,loadingPercent:b.currentLoadingPercent??undefined};if(tr)Object.assign(values,high?{pHvMw:b.pf,qHvMvar:b.qf,pLvMw:b.pt,qLvMvar:b.qt,currentHvA:b.ifA,currentLvA:b.itA}:{pHvMw:b.pt,qHvMvar:b.qt,pLvMw:b.pf,qLvMvar:b.qf,currentHvA:b.itA,currentLvA:b.ifA});else Object.assign(values,{pFromMw:b.pf,qFromMvar:b.qf,pToMw:b.pt,qToMvar:b.qt});return{kind:tr?'transformer':'line',id:b.id,ids:[b.id],name:b.name,nominalKv:b.vnKv,islandId:b.islandId,siteIds:b.siteIds,from:b.from,to:b.to,ratedFromA:b.ratedCurrentFromA,ratedToA:b.ratedCurrentToA,fromIsHv:high,values,keys:{}};});const gens:Actual[]=result.generators.map(g=>({kind:'generator',id:g.id,ids:[g.id],name:g.name,nominalKv:volts.get(g.bus)??0,islandId:islandByBus.get(g.bus),siteIds:[],qState:g.qState,connectedBus:g.bus,values:{pMw:g.pMw,qMvar:g.qMvar??undefined},keys:{calculationBusFid:g.bus,calculationBusKey:g.bus,electricalBusKey:g.bus}}));return [...buses,...branches,...gens];}
const fields:Record<ReferenceKind,Metric[]>={bus:['nominalKv','voltageKv','voltagePu','angleDeg'],line:['pFromMw','qFromMvar','pToMw','qToMvar','pLossMw','qLossMvar','loadingPercent','currentFromA','currentToA'],transformer:['pHvMw','qHvMvar','pLvMw','qLvMvar','pLossMw','qLossMvar','loadingPercent','currentHvA','currentLvA','tapPosition','tapRatio','phaseShiftDeg'],generator:['pMw','qMvar']};
const unit=(m:Metric)=>m.toLowerCase().includes('angle')||m==='phaseShiftDeg'?'deg':m.toLowerCase().includes('kv')?'kV':m.toLowerCase().includes('pu')?'pu':m.toLowerCase().includes('mvar')?'MVAr':m.toLowerCase().includes('mw')?'MW':m.toLowerCase().includes('current')?'A':m.toLowerCase().includes('loading')?'%':'1';
function compatibility(doc:PowerFactoryReference,ctx:ComparisonContext|undefined):PowerFactoryComparison['compatibility']{
 const reasons:string[]=[],ref=doc.metadata,c=ctx||{};let settingsMismatch=false,exploratory=false,eligibilityMissing=false;
 const sameTypeModelPairs=[[ref.modelId,c.modelId],[ref.modelHash,c.modelHash]] as const,knownPairs=sameTypeModelPairs.filter(([a,b])=>!!a&&!!b);
 if(!knownPairs.length)reasons.push('model identity is unknown');else if(knownPairs.some(([a,b])=>a!==b))reasons.push('model mismatch');
 for(const[label,a,b]of [['study case',ref.studyCase,c.studyCase],['study time',ref.studyTime,c.studyTime],['topology',ref.topologyHash,c.topologyHash]] as const){if(!a||!b)reasons.push(`${label} identity is unknown`);else if(a!==b)reasons.push(`${label} mismatch`);}
 if(ref.calculationSettingsHash||c.calculationSettingsHash){
  const sharedHashAlgorithm=!!ref.calculationSettingsHashAlgorithm&&ref.calculationSettingsHashAlgorithm===c.calculationSettingsHashAlgorithm;
  if(!ref.calculationSettingsHash||!c.calculationSettingsHash||!sharedHashAlgorithm){reasons.push('calculation settings hash cannot be compared without a shared declared algorithm');exploratory=true;}
  else if(ref.calculationSettingsHash!==c.calculationSettingsHash){reasons.push('calculation settings mismatch');settingsMismatch=true;}
 }
 if(c.calculationSettingsSemanticsAvailable===false){reasons.push('PowerFactory calculation-setting semantics are unavailable or raw enum-only');exploratory=true;}
 if(c.activeBalanceEligibilityAvailable===false){reasons.push('adjustable-load active balancing eligibility is missing');eligibilityMissing=true;}
 if(c.controlContextReferenceMatched===false)reasons.push('ControlContext numeric reference mismatch');
 const pfBalancing=powerFactoryLoadFlowSettings(doc).semantic.activeBalancingMode;
 if(pfBalancing==='Distributed Slack by Loads'&&c.effectiveActiveBalancingMode&&c.effectiveActiveBalancingMode!=='DISTRIBUTED_ADJUSTABLE_LOADS'){
  reasons.push('PowerFactory distributed load balancing differs from the effective Grid Analyzer balancing mode');
  if(!eligibilityMissing)settingsMismatch=true;
 }
 const identityMismatch=reasons.some(x=>x==='model mismatch'||x==='study case mismatch'||x==='study time mismatch'||x==='topology mismatch'||x==='ControlContext numeric reference mismatch');
 const status=identityMismatch?'BLOCKED':settingsMismatch?'BLOCKED_CALCULATION_SETTINGS_MISMATCH':eligibilityMissing?'COMPARABLE_PARTIAL':exploratory?'EXPLORATORY_ONLY':reasons.length?'BLOCKED':'COMPATIBLE';
 return{status,reasons,compared:{modelId:ref.modelId,studyCase:ref.studyCase,studyTime:ref.studyTime,topologyHash:ref.topologyHash,calculationSettingsHash:ref.calculationSettingsHash}};
}
const endpointKey=(kind:ReferenceKind,a:string,b:string)=>`${kind}|${[a,b].sort().join('|')}`;
function makeIndexes(actual:Actual[]){const ids=new Map<string,Actual[]>(),names=new Map<string,Actual[]>(),keys=new Map<string,Actual[]>(),endpoints=new Map<string,Actual[]>();for(const a of actual){for(const id of a.ids)add(ids,`${a.kind}|${id}`,a);add(names,`${a.kind}|${a.name}`,a);for(const[k,v]of Object.entries(a.keys))if(v)add(keys,`${a.kind}|${k}|${v}`,a);if(a.from&&a.to)add(endpoints,endpointKey(a.kind,a.from,a.to),a);}return{ids,names,keys,endpoints};}
function add(map:Map<string,Actual[]>,key:string,value:Actual){const a=map.get(key)||[];a.push(value);map.set(key,a);}
function compare(doc:PowerFactoryReference,result:CalculationResult,ctx?:ComparisonContext):PowerFactoryComparison {
 const compat=compatibility(doc,ctx),actual=actualRecords(result),idx=makeIndexes(actual),busAliases=new Map<string,string>(),matched:Record<ReferenceKind,number>={bus:0,line:0,transformer:0,generator:0},unmatched:MatchIssue[]=[],ambiguous:MatchIssue[]=[],used=new Set<Actual>(),matchMethods:Partial<Record<MatchMethod,number>>={},errors=new Map<string,{kind:ReferenceKind;metric:ComparisonMetric;band:VoltageBand|null;values:number[]}>(),pairs:{a:Actual;ref:PowerFactoryReferenceRecord;band:VoltageBand|null}[]=[],rows:ComparisonRow[]=[],rowByActual=new Map<Actual,ComparisonRow>();for(const b of result.buses)for(const id of [b.id,...b.terms])busAliases.set(id,b.id);
 const addErr=(kind:ReferenceKind,metric:ComparisonMetric,diff:number,band:VoltageBand|null)=>{for(const b of [null,band]){if(b===undefined)continue;const key=`${kind}|${metric}|${b??''}`,e=errors.get(key)||{kind,metric,band:b,values:[]};e.values.push(diff);errors.set(key,e);}};
 const loadingComparable=(ref:PowerFactoryReferenceRecord,a:Actual):boolean=>{if(ref.kind!=='line'&&ref.kind!=='transformer')return false;const pfFrom=ref.kind==='transformer'?num(ref.raw?.ratedCurrentHvA)??ref.ratedCurrentFromA:ref.ratedCurrentFromA,pfTo=ref.kind==='transformer'?num(ref.raw?.ratedCurrentLvA)??ref.ratedCurrentToA:ref.ratedCurrentToA,gaFrom=ref.kind==='transformer'&&a.fromIsHv===false?a.ratedToA:a.ratedFromA,gaTo=ref.kind==='transformer'&&a.fromIsHv===false?a.ratedFromA:a.ratedToA,pfDerived=num(ref.raw?.loadingCalculatedFromCurrentPercent);return pfFrom!=null&&pfFrom>0&&pfTo!=null&&pfTo>0&&gaFrom!=null&&gaTo!=null&&Math.abs(gaFrom/pfFrom-1)<=0.001&&Math.abs(gaTo/pfTo-1)<=0.001&&ref.loadingPercent!=null&&pfDerived!=null&&Math.abs(ref.loadingPercent-pfDerived)<=0.1;};
 const metricPair=(m:Metric,pf:number|undefined,ga:number|undefined,verifiedLoading=false):MetricPair=>{const hasPf=typeof pf==='number'&&Number.isFinite(pf),hasGa=typeof ga==='number'&&Number.isFinite(ga),comparable=hasPf&&hasGa&&(m!=='loadingPercent'||verifiedLoading),delta=comparable?ga!-pf!:null;return{gridAnalyzer:hasGa?ga!:null,powerFactory:hasPf?pf!:null,delta,absoluteDelta:delta===null?null:Math.abs(delta),deltaPercent:delta===null||pf==null||pf===0?null:delta/Math.abs(pf)*100,unit:unit(m),comparable,semantics:m==='loadingPercent'?verifiedLoading?'PF c:loading and GA current loading; endpoint rated currents and PF current-derived loading agree':'excluded: endpoint rated-current basis or PF c:loading semantics are not verified':'same named quantity; sign is GA minus PowerFactory'};};
 for(const ref of doc.records){const pool=(key:string)=>idx.ids.get(`${ref.kind}|${key}`)||[];let options:Actual[]=[],method:MatchMethod|undefined;
  if(ref.fid||ref.fids?.length){const idHits=[...(ref.fid?[ref.fid]:[]),...(ref.fids||[])].flatMap(pool);options=[...new Set(idHits)];if(options.length===1)method='FID';}
  if(!options.length&&ref.kind==='bus'&&ref.calculationBusFid){options=pool(ref.calculationBusFid);if(options.length)method='CALCULATION_BUS_KEY';}
  if(!options.length&&ref.calculationBusKey){options=idx.keys.get(`${ref.kind}|calculationBusKey|${ref.calculationBusKey}`)||[];if(options.length)method='CALCULATION_BUS_KEY';}
  if(!options.length&&ref.electricalBusKey){options=idx.keys.get(`${ref.kind}|electricalBusKey|${ref.electricalBusKey}`)||[];if(options.length)method='ELECTRICAL_BUS_KEY';}
  if(!options.length&&(ref.physicalTerminalFid||ref.physicalTerminalFids?.length)){options=[...new Set([...(ref.physicalTerminalFid?[ref.physicalTerminalFid]:[]),...(ref.physicalTerminalFids||[])].flatMap(pool))];if(options.length)method='PHYSICAL_TERMINAL';}
  if(!options.length){const from=ref.fromCalculationBusKey??ref.fromCalculationBusFid??ref.fromBusFid,to=ref.toCalculationBusKey??ref.toCalculationBusFid??ref.toBusFid;if(from&&to){options=idx.endpoints.get(endpointKey(ref.kind,from,to))||[];if(options.length)method='ENDPOINT_HIERARCHY';}}
  if(!options.length&&!ref.fid){options=idx.names.get(`${ref.kind}|${ref.name}`)||[];if(options.length)method='EXACT_NAME';}
  if(options.length!==1||used.has(options[0])){const reason=(options.length||used.has(options[0])?'AMBIGUOUS':'UNMATCHED') as 'AMBIGUOUS'|'UNMATCHED',issue:MatchIssue={kind:ref.kind,fid:ref.fid,name:ref.name,reason,source:'REFERENCE'};(reason==='AMBIGUOUS'?ambiguous:unmatched).push(issue);rows.push({kind:ref.kind,status:reason==='AMBIGUOUS'?'AMBIGUOUS':'UNMATCHED_REFERENCE',powerFactoryFid:ref.fid,powerFactoryName:ref.name,hierarchy:{ytm:ref.ytmName,tm:ref.substationName,voltageKv:ref.voltageLevelKv??ref.nominalKv,feeder:ref.feederName},topology:{calculationBusFid:ref.calculationBusFid,calculationBusKey:ref.calculationBusKey,electricalBusKey:ref.electricalBusKey,physicalTerminalFid:ref.physicalTerminalFid,from:ref.fromCalculationBusKey??ref.fromCalculationBusFid??ref.fromBusFid,to:ref.toCalculationBusKey??ref.toCalculationBusFid??ref.toBusFid},metrics:{}});continue;}
  const a=options[0];used.add(a);matched[ref.kind]++;if(method)matchMethods[method]=(matchMethods[method]||0)+1;const band=voltageBand(a.nominalKv),row:ComparisonRow={kind:ref.kind,status:'MATCHED',matchMethod:method,gridAnalyzerId:a.id,powerFactoryFid:ref.fid,gridAnalyzerName:a.name,powerFactoryName:ref.name,hierarchy:{ytm:ref.ytmName,tm:ref.substationName??ref.siteName,voltageKv:ref.voltageLevelKv??ref.nominalKv,feeder:ref.feederName},topology:{calculationBusFid:ref.calculationBusFid,calculationBusKey:ref.calculationBusKey,electricalBusKey:ref.electricalBusKey,physicalTerminalFid:ref.physicalTerminalFid,from:a.from,to:a.to,powerFactoryFrom:ref.fromCalculationBusKey??ref.fromCalculationBusFid??ref.fromBusFid,powerFactoryTo:ref.toCalculationBusKey??ref.toCalculationBusFid??ref.toBusFid},metrics:{}};if(ref.kind==='generator'){const connected=ref.connectedCalculationBusKey??ref.connectedBusFid,mapped=connected?busAliases.get(connected):undefined;row.generatorControl={gridAnalyzerQState:a.qState,powerFactoryControlModeRaw:ref.controlModeRaw,gridAnalyzerBusId:a.connectedBus,powerFactoryConnectedBusFid:ref.connectedBusFid,powerFactoryConnectedCalculationBusKey:ref.connectedCalculationBusKey,busMatch:!connected?'UNKNOWN':mapped&&a.connectedBus===mapped?'MATCHED':mapped?'MISMATCHED':'UNKNOWN'};}pairs.push({a,ref,band});
   if(compat.status==='COMPATIBLE'||compat.status==='EXPLORATORY_ONLY'||compat.status==='COMPARABLE_PARTIAL')for(const m of fields[ref.kind]){const conflicted=ref.conflictedMetrics?.includes(m),pair=conflicted?{gridAnalyzer:a.values[m]??null,powerFactory:null,delta:null,absoluteDelta:null,deltaPercent:null,unit:unit(m),comparable:false,semantics:'excluded: conflicting PowerFactory rows share an electrical calculation bus'} as MetricPair:metricPair(m,ref[m] as number|undefined,a.values[m],m==='loadingPercent'&&loadingComparable(ref,a));row.metrics[m]=pair;if(pair.comparable)addErr(ref.kind,m,pair.delta!,band);}
  rows.push(row);rowByActual.set(a,row);
 }
 const alignment:{islandId:string;method:'REFERENCE_BUS'|'MEDIAN';offsetDeg:number;matchedBusCount:number}[]=[];if(compat.status==='COMPATIBLE'||compat.status==='EXPLORATORY_ONLY'||compat.status==='COMPARABLE_PARTIAL'){const busPairs=pairs.filter(p=>p.a.kind==='bus'&&typeof p.ref.angleDeg==='number'&&typeof p.a.values.angleDeg==='number'),groups=new Map<string,typeof busPairs>();for(const p of busPairs){const id=p.a.islandId||'unknown',arr=groups.get(id)||[];arr.push(p);groups.set(id,arr);}for(const[id,group]of groups){const reference=group.find(p=>p.ref.isReferenceBus)||group.find(p=>p.a.ids.includes(String(result.diagnostics.referenceBusId??''))),offsets=group.map(p=>p.ref.angleDeg!-p.a.values.angleDeg!).sort((a,b)=>a-b),mid=Math.floor(offsets.length/2),offset=reference?reference.ref.angleDeg!-reference.a.values.angleDeg!:offsets.length%2?offsets[mid]:(offsets[mid-1]+offsets[mid])/2;alignment.push({islandId:id,method:reference?'REFERENCE_BUS':'MEDIAN',offsetDeg:offset,matchedBusCount:group.length});for(const p of group){const expected=p.ref.angleDeg!,observed=p.a.values.angleDeg!,delta=observed+offset-expected,row=rowByActual.get(p.a);if(row)row.metrics.alignedAngleDeg={gridAnalyzer:observed+offset,powerFactory:expected,delta,absoluteDelta:Math.abs(delta),deltaPercent:expected===0?null:delta/Math.abs(expected)*100,unit:'deg',comparable:true,semantics:`GA raw angle aligned by ${reference?'reference bus':'island median'}; sign is aligned GA minus PF`};addErr('bus','alignedAngleDeg',delta,p.band);}}}
 const pct=(v:number[])=>{const s=v.map(Math.abs).sort((a,b)=>a-b),x=(s.length-1)*.95,l=Math.floor(x),h=Math.ceil(x);return s.length?s[l]+(s[h]-s[l])*(x-l):0;},metrics:MetricError[]=[],voltageBands:(MetricError&{band:VoltageBand})[]=[];for(const e of errors.values()){const out:MetricError={kind:e.kind,metric:e.metric,count:e.values.length,mae:e.values.reduce((s,x)=>s+Math.abs(x),0)/e.values.length,maxAbsoluteError:Math.max(...e.values.map(Math.abs)),p95AbsoluteError:pct(e.values),meanBias:e.values.reduce((s,x)=>s+x,0)/e.values.length,unit:unit(e.metric as Metric),semantics:e.metric==='loadingPercent'?'PF c:loading vs GA current loading; matching endpoint ratings verified':'same named quantity'};if(e.band)voltageBands.push({...out,band:e.band});else metrics.push(out);}
 const unmatchedActual:Record<ReferenceKind,number>={bus:0,line:0,transformer:0,generator:0};let unmatchedActualTotal=0;for(const a of actual)if(!used.has(a)){unmatched.push({kind:a.kind,fid:a.id,name:a.name,reason:'UNMATCHED',source:'ACTUAL'});unmatchedActual[a.kind]++;unmatchedActualTotal++;rows.push({kind:a.kind,status:'UNMATCHED_ACTUAL',gridAnalyzerId:a.id,gridAnalyzerName:a.name,hierarchy:{voltageKv:a.nominalKv},topology:{from:a.from,to:a.to},metrics:{}});}
 const matchedTotal=Object.values(matched).reduce((s,x)=>s+x,0),angleAlignment:PowerFactoryComparison['angleAlignment']={method:alignment.length>1?'PER_ISLAND':alignment[0]?.method||'NONE',offsetDeg:alignment.length===1?alignment[0].offsetDeg:null,matchedBusCount:alignment.reduce((s,x)=>s+x.matchedBusCount,0),islands:alignment};return{compatibility:compat,matched,matchMethods,unmatchedActual,unmatched,ambiguous,summary:{matchedTotal,unmatchedReference:unmatched.filter(x=>x.source==='REFERENCE').length,ambiguousReference:ambiguous.length,unmatchedActualTotal},metrics,voltageBands,rows,referenceValueConflicts:doc.valueConflicts||[],angleAlignment,quality:compat.status==='BLOCKED'||compat.status==='BLOCKED_CALCULATION_SETTINGS_MISMATCH'?'BLOCKED':compat.status==='COMPARABLE_PARTIAL'?'COMPARABLE_PARTIAL':compat.status==='EXPLORATORY_ONLY'?'EXPLORATORY_ONLY':result.converged?'BENCHMARKED_PARTIAL':'AVAILABLE_NOT_ACCEPTED'};
}
export function comparePowerFactoryReference(reference:PowerFactoryReference|readonly PowerFactoryReferenceRecord[],result:CalculationResult,context?:ComparisonContext):PowerFactoryComparison {return compare(Array.isArray(reference)?{metadata:{},records:reference as readonly PowerFactoryReferenceRecord[] as PowerFactoryReferenceRecord[]}:reference as PowerFactoryReference,result,context);}
