import { spawn } from 'node:child_process';
import { setTimeout as delay } from 'node:timers/promises';
import { chromium } from 'playwright';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const fixture=path.join(root,'tests','fixtures','small-dgs.json');
const port=5179,url=`http://127.0.0.1:${port}/`;
const server=spawn(process.execPath,[path.join(root,'node_modules','vite','bin','vite.js'),'--host','127.0.0.1','--port',String(port),'--strictPort'],{cwd:root,stdio:'ignore',windowsHide:true});
let browser;
try{
 let ready=false;for(let attempt=0;attempt<80;attempt++){try{const response=await fetch(url);if(response.ok){ready=true;break;}}catch{}await delay(250);}
 if(!ready)throw new Error('Vite smoke server did not become ready.');
 browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:900}});page.setDefaultTimeout(20000);const errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.goto(url);const navigation=await page.locator('.ga-nav button').allTextContents();if(navigation.join('|')!=='Model Yükle|Şebeke Envanteri|İşletme Verileri|Harita|Tek Hat Şeması|Analizler|Karşılaştırma|Yardım|Ayarlar')throw Error('UI navigation contract failed');if(await page.locator('[data-view="model"]').getByRole('button',{name:'N-1 SENARYOLARI',exact:true}).count())throw Error('N-1 remains in Model');await page.locator('#modelFileInput').setInputFiles(fixture);
 await page.waitForFunction(()=>Boolean(document.querySelector('.ga-head-model')?.textContent?.trim()));
 await page.getByRole('button',{name:'Model Yükle',exact:true}).click();
 await page.getByRole('button',{name:'MODEL KALİTESİ',exact:true}).click();
 await page.getByRole('button',{name:'Kalite denetimini çalıştır'}).click();
 await page.locator('[data-view="model"] .ga-analysis-view .ga-card-grid .ga-card').first().waitFor();
 const qualityDownload=page.waitForEvent('download');await page.getByRole('button',{name:'JSON indir'}).click();
 if((await qualityDownload).suggestedFilename()!=='GridAnalyzer-model-quality.json')throw new Error('Model Quality JSON export missing.');
 await page.getByRole('button',{name:'Analizler',exact:true}).click();await page.getByRole('button',{name:'Kısıt Analizi (N-1)',exact:true}).click();await page.getByRole('button',{name:'N-1 SENARYOLARI',exact:true}).click();await page.getByText('Gelişmiş DC tarama / katalog',{exact:true}).click();
 const view=page.locator('section[data-view="analysis"] #ga-analysis-N1');
 await view.locator('table.ga-table tbody tr').first().waitFor();
 const defaultCounts=await view.evaluate(root=>{const cards=[...root.querySelectorAll('.ga-card')];const count=label=>{const card=cards.find(item=>item.querySelector('small')?.textContent?.trim()===label);return card?Number(card.querySelector('strong')?.textContent?.replace(/\D/g,'')):null;};return{screenable:count('DC taranabilir'),islanding:count('Ada ayıran'),unsupported:count('Taranamayan'),selected:count('Seçili')};});
 if(defaultCounts.selected!==defaultCounts.screenable+defaultCounts.islanding||!(defaultCounts.islanding>0)||!(defaultCounts.unsupported>0))throw new Error(`Default N-1 selection excludes islanding or includes unsupported candidates: ${JSON.stringify(defaultCounts)}`);
 await view.locator('select[aria-label="Taranabilirlik filtresi"]').selectOption('ALL');
 await view.locator('select[aria-label="Aday gerilim filtresi"]').selectOption('400');
 const candidatesBeforeSearch=await view.locator('table.ga-table tbody tr').count();
 await view.locator('input[aria-label="N-1 adaylarında ara"]').fill('L400-01');
 await view.getByRole('button',{name:'Filtredekileri seç'}).click();
 const candidatesAfterSearch=await view.locator('table.ga-table tbody tr').count();
 if(candidatesAfterSearch===0||candidatesAfterSearch>=candidatesBeforeSearch)throw new Error('N-1 candidate filtering did not narrow the catalog.');
 await view.locator('input[aria-label="N-1 adaylarında ara"]').fill('');
 await view.getByRole('button',{name:'Seçili senaryoları tara'}).click();
 await page.waitForFunction(()=>document.querySelector('footer [role="status"]')?.textContent?.startsWith('N-1 taraması ·'));
 await page.getByRole('button',{name:'N-1 SONUÇLARI',exact:true}).click();
 await view.locator('[data-n1-result-ready="true"]').waitFor();
 await view.locator('.ga-n1-complete').waitFor({state:'visible'});
 if(await view.locator('.ga-n1-complete progress').count())throw new Error('Completed N-1 state still shows a progress bar.');
 await view.getByRole('button',{name:'KISIT SENARYOLARI',exact:true}).click();
 await view.locator('select[aria-label="N-1 sonuç durumu"]').selectOption('ISLANDING');
 const selectedRow=view.locator('.ga-panel .ga-table tbody tr[data-id]').first();
 const selectedId=await selectedRow.getAttribute('data-id');
 await selectedRow.click();
 await view.locator(`[data-n1-detail-id="${selectedId}"]`).waitFor({state:'visible'});
 await view.getByRole('button',{name:'KISIT YÜKLENMELERİ',exact:true}).click();
 if(!await view.locator('.ga-n1-violation-table').isVisible())throw new Error('Kısıt Yüklenmeleri table did not render.');
 await view.getByRole('button',{name:'ADA / KAYIP',exact:true}).click();
 const islandStatuses=await view.locator('.ga-panel tr[data-island]').allTextContents();
 if(!islandStatuses.some(text=>text.includes('Referanssız ada'))||islandStatuses.some(text=>/UNREFERENCED|REFERENCED/.test(text)))throw new Error(`Ada/Kayıp Turkish reference status is missing: ${JSON.stringify(islandStatuses)}`);
 await view.getByRole('button',{name:'KRİTİK KISITLAR',exact:true}).click();
 await view.getByRole('button',{name:'KISIT SENARYOLARI',exact:true}).click();
 const n1Download=page.waitForEvent('download');await view.locator('summary[aria-label="N-1 sonuçlarını dışa aktar"]').click();await view.getByRole('button',{name:'Senaryolar CSV'}).click();
 if((await n1Download).suggestedFilename()!=='GridAnalyzer-n1-senaryolar.csv')throw new Error('N-1 CSV export missing.');
 await page.getByRole('button',{name:'Harita',exact:true}).click();
 await page.getByLabel('Benchmark harita analizi',{exact:true}).selectOption('N1');await page.getByLabel('Benchmark harita metriği',{exact:true}).selectOption('thermalRisk');
 await page.waitForFunction(()=>/N-1 termik risk/.test(document.querySelector('.ga-map-legend b')?.textContent||''));
 await page.getByLabel('Benchmark harita metriği',{exact:true}).selectOption('islands');
 await page.waitForFunction(()=>/N-1 adaları/.test(document.querySelector('.ga-map-legend b')?.textContent||''));
 await page.getByRole('button',{name:'Analizler',exact:true}).click();
 await page.getByRole('button',{name:'N-1 SONUÇLARI',exact:true}).click();
 await view.getByRole('button',{name:'KISIT SENARYOLARI',exact:true}).click();
 await view.locator(`.ga-panel .ga-table tbody tr[data-id="${selectedId}"].ga-selected`).waitFor({state:'visible'});
 await page.getByRole('button',{name:'Analizler',exact:true}).click();
 await page.getByRole('button',{name:'Yük Akışı Analizi',exact:true}).click();await page.getByRole('button',{name:/Baz Hesapla.*Tam AC/}).click();
 await page.waitForFunction(()=>document.querySelector('footer [role="status"]')?.textContent?.includes('NR yakınsadı'));
 if(await page.locator('#ga-analysis-LF input[type="file"]').count())throw Error('LF still owns reference imports');const engineHelp=page.getByLabel('Gösterilen hesap türü',{exact:true}).locator('..').locator('.ga-context-help');await engineHelp.getByRole('button').focus();await engineHelp.getByRole('button').press('Enter');if(await engineHelp.locator('details[open]').count())throw Error('Tooltip click opens a card');await engineHelp.getByRole('button').press('Escape');await page.getByRole('button',{name:'Yardım',exact:true}).click();await page.getByLabel('Yardımda ara',{exact:true}).fill('Yük akışı yöntemi');await page.locator('[data-help-entry="lf.fullAc"]').waitFor();await page.getByRole('button',{name:'Analizler',exact:true}).click();
 const downloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:'XLSX sonuç indir'}).click();const workbook=await downloadEvent;
 if(workbook.suggestedFilename()!=='GridAnalyzer_FullNR_Results.xlsx')throw new Error('XLSX result download missing.');
 await page.getByRole('button',{name:'Karşılaştırma',exact:true}).click();await page.getByText('Diğer referanslar / ControlContext',{exact:true}).click();const analysis=page.locator('section[data-view="comparison"] .ga-analysis-view');
 await analysis.locator('input[aria-label="PowerFactory referans JSON veya CSV"]').setInputFiles({name:'pf-mismatch.csv',mimeType:'text/csv',buffer:Buffer.from('sep=;\r\nkind;fid;name;metaKey;metaValue;calculationBusKey;physicalTerminalFid;voltagePu\r\nmeta;;;modelId;different-model;;;\r\nmeta;;;studyCase;different-case;;;\r\nmeta;;;studyTimeLocal;2026-10-02 13:00:00;;;\r\nbus;T1;Bus;;;T1;T1;1\r\n')});
 await analysis.getByRole('button',{name:'Karşılaştır',exact:true}).waitFor();
 await analysis.getByText('Bloklandı', {exact:true}).first().waitFor();
 if(await analysis.locator('pre').count())throw new Error('Raw diagnostics JSON remains visible.');
 const comparisonXlsx=page.waitForEvent('download');await analysis.getByRole('button',{name:'Karşılaştırma XLSX'}).click();if((await comparisonXlsx).suggestedFilename()!=='GridAnalyzer_PowerFactory_Comparison.xlsx')throw new Error('Comparison XLSX export missing.');
 const comparisonCsv=page.waitForEvent('download');await analysis.getByRole('button',{name:'Karşılaştırma CSV'}).click();if((await comparisonCsv).suggestedFilename()!=='GridAnalyzer_PowerFactory_Comparison.csv')throw new Error('Comparison CSV export missing.');
 await page.getByRole('button',{name:'Analizler',exact:true}).click();const lf=page.locator('section[data-view="analysis"]');await lf.getByRole('button',{name:'Topoloji',exact:true}).click();await lf.getByRole('button',{name:'154 kV Ayrık Bara / Yarı Ada'}).waitFor();
 await page.getByRole('button',{name:'Harita',exact:true}).click();
 await page.locator('.ga-map-advanced>summary').click();await page.locator('select[aria-label="Harita renk modu"]').selectOption('angle');
 await page.waitForFunction(()=>/açısı/i.test(document.querySelector('.ga-map-legend b')?.textContent||''));
 await page.locator('select[aria-label="Harita renk modu"]').selectOption('island');
 await page.waitForFunction(()=>/Elektrik adası/i.test(document.querySelector('.ga-map-legend b')?.textContent||'')&&/elektrik adası/i.test(document.querySelector('.ga-map-legend')?.textContent||''));
 await page.locator('#networkCanvas').waitFor();
 await page.getByRole('button',{name:'Elektriksel Sonuçlar'}).click();
 await page.locator('.ga-result-table tbody tr[data-row]').first().waitFor();
 await page.getByRole('button',{name:'Ayarlar',exact:true}).click();await page.locator('input[data-key="color220"]').fill('#112233');await page.getByRole('button',{name:'Uygula',exact:true}).click();
 await page.getByRole('button',{name:'Harita',exact:true}).click();await page.locator('#networkCanvas').waitFor();
 const mapIdentity=await page.locator('section[data-view="map"]').getAttribute('data-result-id'),mapScenario=await page.locator('section[data-view="map"]').getAttribute('data-scenario-id');await page.getByRole('button',{name:'Tek Hat Şeması',exact:true}).click();
 await page.locator('.ga-sld-svg').waitFor();if(await page.locator('section[data-view="sld"]').getAttribute('data-result-id')!==mapIdentity||await page.locator('section[data-view="sld"]').getAttribute('data-scenario-id')!==mapScenario)throw Error('SLD workspace identity differs from map');
 await page.locator('.ga-sld-results>summary').click();if(await page.locator('.ga-sld-results .ga-workspace-results').getAttribute('data-result-id')!==mapIdentity)throw Error('SLD result table has a different identity');await page.getByRole('button',{name:'Harita',exact:true}).click();await page.locator('.ga-map-advanced').evaluate(e=>{e.open=false;});
 await page.locator('.ga-scenario-drawer>summary').click();await page.getByRole('button',{name:'Dallan',exact:true}).click();await page.getByLabel('Aktif senaryo',{exact:true}).selectOption('B0');await page.getByLabel('Benchmark harita analizi',{exact:true}).selectOption('SC');await page.getByLabel('Senaryo farkının referansı',{exact:true}).selectOption('S1');await page.waitForFunction(()=>document.querySelector('.ga-scenario-workspace small')?.textContent?.includes('LF'));if(await page.getByLabel('Benchmark harita analizi',{exact:true}).inputValue()!=='LF'||await page.getByLabel('Benchmark harita kaynağı',{exact:true}).inputValue()!=='SCENARIO_DELTA')throw Error('Scenario comparison leaves another analysis overlay selected');await page.locator('.ga-scenario-drawer>summary').click();
 for(const viewport of [{width:1440,height:900},{width:390,height:844}]){await page.setViewportSize(viewport);await page.waitForTimeout(100);const geometry=await page.locator('.ga-map-wrap').evaluate(e=>{const r=e.getBoundingClientRect();return{top:r.top,bottom:r.bottom,height:r.height,overflow:document.documentElement.scrollWidth>innerWidth};});if(geometry.overflow||geometry.bottom>viewport.height+1||geometry.height<viewport.height*.5)throw Error(`Map viewport contract failed: ${JSON.stringify({viewport,geometry})}`);await page.locator('.ga-map-advanced>summary').click();await page.waitForTimeout(100);const beforeTipHeight=await page.locator('.ga-map-wrap').evaluate(e=>e.getBoundingClientRect().height);const tip=page.locator('section[data-view="map"] input[data-help-id="map.voltage.400"]').locator('..').locator('..').locator('.ga-context-help button');await tip.hover();await tip.click();const box=await tip.locator('..').locator('[role="tooltip"]').boundingBox();if(!box||box.x<0||box.y<0||box.x+box.width>viewport.width+1||box.y+box.height>viewport.height+1)throw Error('Tooltip exceeds viewport');if(await page.locator('.ga-map-wrap').evaluate(e=>e.getBoundingClientRect().height)!==beforeTipHeight)throw Error('Tooltip changes map height');await tip.press('Escape');await page.locator('.ga-map-advanced>summary').click();console.log(`Map viewport ${viewport.width}x${viewport.height}: ${JSON.stringify(geometry)}`);}
 if(errors.length)throw Error(`Browser JS errors: ${errors.join('; ')}`);
 console.log('Chromium smoke passed: load → quality audit/JSON → N-1 catalog/filter/selection/progress/result/CSV → Full AC/XLSX → PF mismatch comparison/XLSX/CSV → structured topology → map angle/island → settings → Lightning results → SLD.');
}finally{
 await browser?.close();server.kill('SIGTERM');
}
