import {mkdir,readFile} from 'node:fs/promises';
import { spawn } from 'node:child_process';
import { setTimeout as delay } from 'node:timers/promises';
import { chromium } from 'playwright';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const fixture=path.join(root,'tests','fixtures','small-dgs.json');
// Public synthetic geometry only: the electrical fixture is unchanged. Original
// intra-yard routes are sub-pixel at national zoom and cannot evidence arrows.
const visualRaw=JSON.parse(await readFile(fixture,'utf8')),routeIndex=visualRaw.ElmLne.Attributes.indexOf('GPScoords:MATRIX');
visualRaw.Matrix.Values=[];
visualRaw.ElmLne.Values.forEach((line,i)=>{const is400=line[0].startsWith('L400'),lat=is400?39.9:39.8,lon=is400?32.8:32.7,id='Synthetic_route_'+i;line[routeIndex]=id;[[lat,lon],[lat+(i%6-2.5)*.35,lon+(is400?2.4:-2.4)],[lat,lon]].forEach((point,row)=>point.forEach((value,column)=>visualRaw.Matrix.Values.push([id,row,column,value])));});
// An explicitly open public coupler adds a split symbol without joining terminals
// or changing the electrical fixture's numerical branch inputs.
for(const [id,bus] of [['UI_SPLIT_A','T154-PV'],['UI_SPLIT_B','T154-2']])visualRaw.StaCubic.Values.push(visualRaw.StaCubic.Attributes.map(k=>({FID:id,loc_name:id,fold_id:bus,obj_id:'UI_SPLIT'}[k]??'')));
visualRaw.ElmCoup.Values.push(visualRaw.ElmCoup.Attributes.map(k=>({FID:'UI_SPLIT',loc_name:'Public synthetic open 154 kV coupler',fold_id:'B154',on_off:0,aUsage:0,bus1:'UI_SPLIT_A',bus2:'UI_SPLIT_B',outserv:0}[k]??'')));
const port=5179,url=`http://127.0.0.1:${port}/`;
const server=spawn(process.execPath,[path.join(root,'node_modules','vite','bin','vite.js'),'--host','127.0.0.1','--port',String(port),'--strictPort'],{cwd:root,stdio:'ignore',windowsHide:true});
let browser;
try{
 let ready=false;for(let attempt=0;attempt<80;attempt++){try{const response=await fetch(url);if(response.ok){ready=true;break;}}catch{}await delay(250);}
 if(!ready)throw new Error('Vite smoke server did not become ready.');
 browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:900}});page.setDefaultTimeout(20000);const errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.addInitScript(()=>{const Native=Worker;window.smokeWork=[];window.Worker=class extends Native{postMessage(m,...rest){if(['RUN_AC','RUN_N1_SCREEN','RUN_N1_AC_VALIDATE','RUN_SC_3PH'].includes(m.type))window.smokeWork.push(m.type);return super.postMessage(m,...rest);}};const nativeRaf=requestAnimationFrame,nativeCancel=cancelAnimationFrame,pending=new Set();window.smokeRaf={pending,maximum:0,frames:0};window.requestAnimationFrame=cb=>{let id;id=nativeRaf(t=>{pending.delete(id);window.smokeRaf.frames++;cb(t);});pending.add(id);window.smokeRaf.maximum=Math.max(window.smokeRaf.maximum,pending.size);return id;};window.cancelAnimationFrame=id=>{pending.delete(id);nativeCancel(id);};});
 await page.goto(url);const navigation=await page.locator('.ga-nav button').allTextContents();if(navigation.join('|')!=='Model Yükle|Şebeke Envanteri|İşletme Verileri|Harita|Tek Hat Şeması|Analizler|Karşılaştırma|Yardım|Ayarlar')throw Error('UI navigation contract failed');if(await page.locator('[data-view="model"]').getByRole('button',{name:'N-1 SENARYOLARI',exact:true}).count())throw Error('N-1 remains in Model');await page.locator('#modelFileInput').setInputFiles({name:'synthetic-map-visual-dgs.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(visualRaw))});
 await page.waitForFunction(()=>Boolean(document.querySelector('.ga-head-model')?.textContent?.trim()));
 await page.getByRole('button',{name:'Model Yükle',exact:true}).click();
 await page.getByRole('button',{name:'MODEL KALİTESİ',exact:true}).click();
 await page.getByRole('button',{name:'Kalite denetimini çalıştır'}).click();
 await page.locator('[data-view="model"] .ga-analysis-view .ga-card-grid .ga-card').first().waitFor();
 const qualityDownload=page.waitForEvent('download');await page.getByRole('button',{name:'JSON indir'}).click();
 if((await qualityDownload).suggestedFilename()!=='GridAnalyzer-model-quality.json')throw new Error('Model Quality JSON export missing.');
 await page.getByRole('button',{name:'Analizler',exact:true}).click();await page.getByRole('button',{name:'Kısıt Analizi (N-1)',exact:true}).click();await page.getByRole('button',{name:'N-1 SENARYOLARI',exact:true}).click();await page.getByText('Gelişmiş DC tarama / katalog',{exact:true}).click();
 const view=page.locator('section[data-view="analysis"] #ga-analysis-N1');
 await view.locator('table.ga-table tbody tr').first().waitFor();
 const defaultCounts=await view.evaluate(root=>{const cards=[...root.querySelectorAll('.ga-card')];const count=label=>{const card=cards.find(item=>item.querySelector('small')?.textContent?.trim()===label);return card?Number(card.querySelector('strong')?.textContent?.replace(/\D/g,'')):null;};return{screenable:count('DC taranabilir'),islanding:count('Ada ayıran'),unsupported:count('Taranamayan'),selected:count('Seçili')};});
 if(defaultCounts.selected!==defaultCounts.screenable+defaultCounts.islanding||!(defaultCounts.islanding>0)||!(defaultCounts.unsupported>0))throw new Error(`Default N-1 selection excludes islanding or includes unsupported candidates: ${JSON.stringify(defaultCounts)}`);
 await view.locator('select[aria-label="Taranabilirlik filtresi"]').selectOption('ALL');
 await view.locator('select[aria-label="Aday gerilim filtresi"]').selectOption('400');
 const candidatesBeforeSearch=await view.locator('table.ga-table tbody tr').count();
 await view.locator('input[aria-label="N-1 adaylarında ara"]').fill('L400-01');
 await view.getByRole('button',{name:'Filtredekileri seç'}).click();
 const candidatesAfterSearch=await view.locator('table.ga-table tbody tr').count();
 if(candidatesAfterSearch===0||candidatesAfterSearch>=candidatesBeforeSearch)throw new Error('N-1 candidate filtering did not narrow the catalog.');
 await view.locator('input[aria-label="N-1 adaylarında ara"]').fill('');
 await view.getByRole('button',{name:'Seçili senaryoları tara'}).click();
 await page.waitForFunction(()=>document.querySelector('footer [role="status"]')?.textContent?.startsWith('N-1 taraması ·'));
 await page.getByRole('button',{name:'N-1 SONUÇLARI',exact:true}).click();
 await view.locator('[data-n1-result-ready="true"]').waitFor();
 await view.locator('.ga-n1-complete').waitFor({state:'visible'});
 if(await view.locator('.ga-n1-complete progress').count())throw new Error('Completed N-1 state still shows a progress bar.');
 await view.getByRole('button',{name:'KISIT SENARYOLARI',exact:true}).click();
 await view.locator('select[aria-label="N-1 sonuç durumu"]').selectOption('ISLANDING');
 const selectedRow=view.locator('.ga-panel .ga-table tbody tr[data-id]').first();
 const selectedId=await selectedRow.getAttribute('data-id');
 await selectedRow.click();
 await view.locator(`[data-n1-detail-id="${selectedId}"]`).waitFor({state:'visible'});
 await view.getByRole('button',{name:'KISIT YÜKLENMELERİ',exact:true}).click();
 if(!await view.locator('.ga-n1-violation-table').isVisible())throw new Error('Kısıt Yüklenmeleri table did not render.');
 await view.getByRole('button',{name:'ADA / KAYIP',exact:true}).click();
 const islandStatuses=await view.locator('.ga-panel tr[data-island]').allTextContents();
 if(!islandStatuses.some(text=>text.includes('Referanssız ada'))||islandStatuses.some(text=>/UNREFERENCED|REFERENCED/.test(text)))throw new Error(`Ada/Kayıp Turkish reference status is missing: ${JSON.stringify(islandStatuses)}`);
 await view.getByRole('button',{name:'KRİTİK KISITLAR',exact:true}).click();
 await view.getByRole('button',{name:'KISIT SENARYOLARI',exact:true}).click();
 const n1Download=page.waitForEvent('download');await view.locator('summary[aria-label="N-1 sonuçlarını dışa aktar"]').click();await view.getByRole('button',{name:'Senaryolar CSV'}).click();
 if((await n1Download).suggestedFilename()!=='GridAnalyzer-n1-senaryolar.csv')throw new Error('N-1 CSV export missing.');
 await page.getByRole('button',{name:'Harita',exact:true}).click();
 await page.getByLabel('Benchmark harita analizi',{exact:true}).selectOption('N1');await page.locator('.ga-map-options>summary').click();await page.getByLabel('N-1 topoloji görünümü',{exact:true}).selectOption('n1-risk');
 await page.waitForFunction(()=>/N-1 termik risk/.test(document.querySelector('.ga-map-legend b')?.textContent||''));
 await page.getByLabel('N-1 topoloji görünümü',{exact:true}).selectOption('n1-island');await page.locator('.ga-map-options>summary').click();
 await page.waitForFunction(()=>/N-1 adaları/.test(document.querySelector('.ga-map-legend b')?.textContent||''));
 await page.getByRole('button',{name:'Analizler',exact:true}).click();
 await page.getByRole('button',{name:'N-1 SONUÇLARI',exact:true}).click();
 await view.getByRole('button',{name:'KISIT SENARYOLARI',exact:true}).click();
 await view.locator(`.ga-panel .ga-table tbody tr[data-id="${selectedId}"].ga-selected`).waitFor({state:'visible'});
 await page.getByRole('button',{name:'Analizler',exact:true}).click();
 await page.getByRole('button',{name:'Yük Akışı Analizi',exact:true}).click();await page.getByRole('button',{name:/Baz Hesapla.*Tam AC/}).click();
 await page.waitForFunction(()=>document.querySelector('footer [role="status"]')?.textContent?.includes('NR yakınsadı'));
 if(await page.locator('#ga-analysis-LF input[type="file"]').count())throw Error('LF still owns reference imports');await page.getByRole('button',{name:'Harita',exact:true}).click();const engineHelp=page.locator('#mapArea');await engineHelp.focus();await page.waitForTimeout(700);if(await page.locator('#ga-label-help').isVisible())throw Error('Mouse control focus opens label help');await page.keyboard.press('Tab');const helpLabel=page.locator('section[data-view=map] [data-help-label=YTM]');await helpLabel.focus();await page.locator('#ga-label-help').waitFor({state:'visible'});await helpLabel.press('Escape');if(await page.locator('#ga-label-help').isVisible())throw Error('Escape did not hide label help');if(await page.locator('.ga-context-help,.ga-help-field').count())throw Error('Decorative help icon/wrapper remains');await page.getByRole('button',{name:'Yardım',exact:true}).click();await page.getByLabel('Yardımda ara',{exact:true}).fill('Yük akışı yöntemi');await page.locator('[data-help-entry="lf.fullAc"]').waitFor();await page.getByRole('button',{name:'Analizler',exact:true}).click();
 const downloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:'XLSX sonuç indir'}).click();const workbook=await downloadEvent;
 if(workbook.suggestedFilename()!=='GridAnalyzer_FullNR_Results.xlsx')throw new Error('XLSX result download missing.');
 await page.getByRole('button',{name:'Karşılaştırma',exact:true}).click();await page.getByText('Diğer referanslar / ControlContext',{exact:true}).click();const analysis=page.locator('section[data-view="comparison"] .ga-analysis-view');
 await analysis.locator('input[aria-label="PowerFactory referans JSON veya CSV"]').setInputFiles({name:'pf-mismatch.csv',mimeType:'text/csv',buffer:Buffer.from('sep=;\r\nkind;fid;name;metaKey;metaValue;calculationBusKey;physicalTerminalFid;voltagePu\r\nmeta;;;modelId;different-model;;;\r\nmeta;;;studyCase;different-case;;;\r\nmeta;;;studyTimeLocal;2026-10-02 13:00:00;;;\r\nbus;T1;Bus;;;T1;T1;1\r\n')});
 await analysis.getByRole('button',{name:'Karşılaştır',exact:true}).waitFor();
 await analysis.getByText('Bloklandı', {exact:true}).first().waitFor();
 if(await analysis.locator('pre').count())throw new Error('Raw diagnostics JSON remains visible.');
 const comparisonXlsx=page.waitForEvent('download');await analysis.getByRole('button',{name:'Karşılaştırma XLSX'}).click();if((await comparisonXlsx).suggestedFilename()!=='GridAnalyzer_PowerFactory_Comparison.xlsx')throw new Error('Comparison XLSX export missing.');
 const comparisonCsv=page.waitForEvent('download');await analysis.getByRole('button',{name:'Karşılaştırma CSV'}).click();if((await comparisonCsv).suggestedFilename()!=='GridAnalyzer_PowerFactory_Comparison.csv')throw new Error('Comparison CSV export missing.');
 await page.getByRole('button',{name:'Analizler',exact:true}).click();const lf=page.locator('section[data-view="analysis"]');await lf.getByRole('button',{name:'Topoloji',exact:true}).click();await lf.getByRole('button',{name:'154 kV Ayrık Bara / Yarı Ada'}).waitFor();
 await page.getByRole('button',{name:'Harita',exact:true}).click();
 const map=page.locator('section[data-view="map"]'),analysisSelect=page.getByLabel('Benchmark harita analizi',{exact:true}),metricSelect=page.getByLabel('Benchmark harita metriği',{exact:true});
 await analysisSelect.selectOption('');await metricSelect.selectOption('angle');
 await page.waitForFunction(()=>/açısı/i.test(document.querySelector('.ga-map-legend b')?.textContent||''));
 await metricSelect.selectOption('island');await page.waitForFunction(()=>/Elektrik adası/i.test(document.querySelector('.ga-map-legend b')?.textContent||''));
 const workBefore=await page.evaluate(()=>window.smokeWork.length);
 await analysisSelect.selectOption('LF');await metricSelect.selectOption('pFromMw');await map.locator('input[data-help-id="map.flow"]').check();
 await page.waitForFunction(()=>document.querySelector('.ga-flow-canvas')?.dataset.flowMetric==='p');
 const pixels=()=>page.locator('.ga-flow-canvas').evaluate(c=>{const data=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let count=0,hash=0;for(let i=3;i<data.length;i+=4)if(data[i]){count++;hash=(hash+i)>>>0;}return{count,hash};});
 const p1=await pixels();await page.waitForTimeout(160);const p2=await pixels();if(!p1.count||!p2.count||p1.hash===p2.hash)throw Error('Actual P flow canvas has no moving arrows: '+JSON.stringify({p1,p2,raf:await page.evaluate(()=>({frames:window.smokeRaf.frames,pending:window.smokeRaf.pending.size})),legend:await map.locator('.ga-map-legend').textContent()}));
 const lineColors=()=>page.locator('#networkCanvas').evaluate(c=>{const d=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let red=0,blue=0;for(let i=0;i<d.length;i+=4){if(d[i]>d[i+1]*1.4&&d[i]>d[i+2]*1.4)red++;if(d[i+2]>d[i]*1.4&&d[i+2]>d[i+1]*1.15)blue++;}return{red,blue};});
 const pColors=await lineColors();await metricSelect.selectOption('voltageKv');const vColors=await lineColors();if(!pColors.red||!pColors.blue||vColors.red<pColors.red*.8||vColors.blue<pColors.blue*.8)throw Error('Bus metric erased nominal line voltage colors');
 await page.getByLabel('Haritada hat ara',{exact:true}).fill('L400-01');await map.getByRole('button',{name:'Bul',exact:true}).click();
 await metricSelect.selectOption('qFromMvar');await page.waitForFunction(()=>document.querySelector('.ga-flow-canvas')?.dataset.flowMetric==='q');await page.waitForTimeout(100);if(!(await pixels()).count)throw Error('Actual Q endpoint arrows missing');
 const voltageMenu=map.locator('.ga-voltage-menu');await voltageMenu.locator('summary').click();await voltageMenu.getByRole('button',{name:'Temizle',exact:true}).click();await map.locator('.ga-map-empty').waitFor({state:'visible'});
 await voltageMenu.getByRole('button',{name:'Tümünü seç',exact:true}).click();if(await voltageMenu.locator('input:checked').count()!==5)throw Error('Voltage menu lost one of five groups');
 await voltageMenu.locator('input[data-help-id="map.voltage.400"]').uncheck();await voltageMenu.locator('input[data-help-id="map.voltage.220"]').uncheck();if(!(await voltageMenu.locator('summary').textContent()).includes('3/5'))throw Error('Voltage menu summary is stale');await voltageMenu.getByRole('button',{name:'Tümünü seç',exact:true}).click();await voltageMenu.locator('summary').click();
 await map.locator('.ga-map-line-menu>summary').click();await page.getByLabel('Hat yerleşimi',{exact:true}).selectOption('separated');await map.locator('.ga-map-line-menu>summary').click();await map.locator('.ga-map-options>summary').click();await page.getByLabel('Harita kapasite sınırı',{exact:true}).selectOption('summer');await page.getByLabel('Harita kapasite sınırı',{exact:true}).selectOption('winter');await map.getByLabel('Sade güzergâh',{exact:true}).check();await map.getByLabel('Sade güzergâh',{exact:true}).uncheck();await map.locator('.ga-map-options>summary').click();
 await map.getByLabel('TM',{exact:true}).uncheck();await map.getByLabel('TM',{exact:true}).check();await map.getByLabel('Etiketler',{exact:true}).check();await map.getByLabel('Etiketler',{exact:true}).uncheck();await map.getByRole('button',{name:'Sığdır',exact:true}).click();
 const ytm=map.getByLabel('YTM filtresi',{exact:true}),firstArea=await ytm.locator('option').nth(1).getAttribute('value');await ytm.selectOption(firstArea);await ytm.selectOption('');
 await map.getByRole('button',{name:'Tam ekran',exact:true}).click();await page.waitForFunction(()=>!!document.fullscreenElement);await map.getByRole('button',{name:'Çık',exact:true}).click();await page.waitForFunction(()=>!document.fullscreenElement);
 await metricSelect.selectOption('pFromMw');
 await map.getByRole('button',{name:'Elektriksel Sonuçlar',exact:true}).click();await map.locator('.ga-result-table tbody tr[data-row]').first().waitFor();
 const mapIdentity=await map.getAttribute('data-result-id'),mapScenario=await map.getAttribute('data-scenario-id'),mapHeight=await map.locator('.ga-map-wrap').evaluate(e=>e.getBoundingClientRect().height);
 if((await map.locator('.ga-lightning').boundingBox()).width>640.1)throw Error('Lightning panel exceeds 640px');
 await map.getByRole('button',{name:'Sonuç panelini kapat',exact:true}).click();await map.getByRole('button',{name:'Elektriksel Sonuçlar',exact:true}).click();await page.keyboard.press('Escape');if(await map.locator('.ga-lightning').isVisible())throw Error('Escape does not close Lightning');
 await map.getByRole('button',{name:'Elektriksel Sonuçlar',exact:true}).click();await map.getByRole('button',{name:'Elektriksel Sonuçlar',exact:true}).click();if(await map.locator('.ga-lightning').isVisible())throw Error('Lightning toggle does not close');
 await map.getByRole('button',{name:'Elektriksel Sonuçlar',exact:true}).click();await map.locator('#networkCanvas').click({position:{x:20,y:180}});if(await map.locator('.ga-lightning').isVisible())throw Error('Outside map click does not close Lightning');
 if(await map.locator('.ga-map-wrap').evaluate(e=>e.getBoundingClientRect().height)!==mapHeight||await map.getAttribute('data-result-id')!==mapIdentity)throw Error('Panel changes map height/result identity');
 await page.getByRole('button',{name:'Tek Hat Şeması',exact:true}).click();await page.locator('.ga-sld-svg').waitFor();if(await page.locator('section[data-view="sld"]').getAttribute('data-result-id')!==mapIdentity||await page.locator('section[data-view="sld"]').getAttribute('data-scenario-id')!==mapScenario)throw Error('SLD workspace identity differs from map');
 await page.locator('.ga-sld-results>summary').click();await page.waitForFunction(id=>document.querySelector('.ga-sld-results .ga-workspace-results')?.getAttribute('data-result-id')===id,mapIdentity);await page.getByRole('button',{name:'Harita',exact:true}).click();
 if(await map.locator('.ga-lightning').isVisible())throw Error('Lightning stayed open after switching view');
 await map.getByRole('button',{name:'Senaryoları aç',exact:true}).click();const scenarios=map.locator('.ga-scenario-embedded');await scenarios.getByRole('button',{name:'Dallan',exact:true}).click();await scenarios.getByLabel('Aktif senaryo',{exact:true}).selectOption('B0');
 await map.getByRole('button',{name:'Sonuç panelini kapat',exact:true}).click();await analysisSelect.selectOption('SC');await map.getByRole('button',{name:'Senaryoları aç',exact:true}).click();await scenarios.getByLabel('Senaryo farkının referansı',{exact:true}).selectOption('S1');
 if(await analysisSelect.inputValue()!=='LF'||await page.getByLabel('Benchmark harita kaynağı',{exact:true}).inputValue()!=='SCENARIO_DELTA')throw Error('Scenario comparison leaves another analysis overlay selected');
 if(await page.locator('.ga-scenario-drawer[open]').count())throw Error('A second fixed scenario popup remains on map');
 await map.getByRole('button',{name:'Sonuç panelini kapat',exact:true}).click();await analysisSelect.selectOption('LF');await metricSelect.selectOption('pFromMw');
 await metricSelect.selectOption('voltageKv');await map.getByLabel('Haritada hat ara',{exact:true}).fill('L400-01');await map.getByRole('button',{name:'Bul',exact:true}).click();
 if(Number(await map.locator('#networkCanvas').getAttribute('data-split-markers'))<1)throw Error('Split buses disappeared under a benchmark overlay');
 const canvasBox=await map.locator('#networkCanvas').boundingBox();await page.mouse.move(canvasBox.x+canvasBox.width/2-8,canvasBox.y+canvasBox.height/2);await map.locator('.ga-map-tooltip').waitFor({state:'visible'});const equipmentBox=await map.locator('.ga-map-tooltip').boundingBox(),equipmentText=await map.locator('.ga-map-tooltip').textContent();if(equipmentBox.width<350||equipmentBox.width>410||equipmentBox.height>250||/modelHash|scenarioHash|"terms"|\(pu\)/.test(equipmentText)||!equipmentText.includes('U (kV)'))throw Error('Engineering equipment card contract failed');await page.mouse.move(0,0);await metricSelect.selectOption('pFromMw');await map.getByRole('button',{name:'Sığdır',exact:true}).click();
 await mkdir('docs/screenshots/map-desktop-20261011',{recursive:true});
 for(const viewport of [{width:1920,height:1080},{width:1600,height:900},{width:1440,height:900},{width:1366,height:768}]){
   await page.setViewportSize(viewport);await page.waitForTimeout(100);
   const geometry=await map.evaluate(e=>{const rows=[...e.querySelectorAll('.ga-map-toolbar-row')].map(row=>{const r=row.getBoundingClientRect();return{top:r.top,height:r.height,overflow:row.scrollWidth>row.clientWidth+1};}),r=e.querySelector('.ga-map-wrap').getBoundingClientRect();return{rows,top:r.top,bottom:r.bottom,height:r.height,overflow:document.documentElement.scrollWidth>innerWidth};});
   if(geometry.rows.length!==2||geometry.rows.some(r=>r.height>35||r.overflow)||geometry.overflow||geometry.bottom>viewport.height+1||geometry.height<viewport.height*.5)throw Error('Two physical desktop rows contract failed: '+JSON.stringify({viewport,geometry}));
   for(const family of ['N1','SC']){await analysisSelect.selectOption(family);if(family==='N1'){const recorded=await map.getByLabel('Benchmark harita kesintisi',{exact:true}).locator('option').evaluateAll(options=>options.find(o=>/SCREENED|CAPACITY_UNAVAILABLE/.test(o.textContent))?.value);if(!recorded)throw Error('No recorded DC case in desktop fixture');await map.getByLabel('Benchmark harita kesintisi',{exact:true}).selectOption(recorded);}await map.getByRole('button',{name:'Elektriksel Sonuçlar',exact:true}).click();await map.locator('.ga-lightning').getByRole('button',{name:family==='N1'?'Kısıt (N-1)':'Kısa Devre',exact:true}).click();const shared=map.locator('.ga-lightning .ga-workspace-results');if(await shared.getAttribute('data-case-id')!==await map.locator('.ga-workspace-results').first().getAttribute('data-case-id'))throw Error('N1 case desynchronized');if(family==='N1'&&(await shared.getAttribute('data-method')!=='GA_DC_SCREEN'||!(await shared.textContent()).includes('DC tarama')))throw Error('Recorded DC method/status missing');if(family==='SC'&&!(await map.locator('.ga-map-status').textContent()).includes('SC'))throw Error('SC status borrowed prior LF');const overflow=await map.locator('.ga-map-toolbar-row').evaluateAll(rows=>rows.some(r=>r.scrollWidth>r.clientWidth+1||r.getBoundingClientRect().height>35));if(overflow)throw Error('Case/fault row overflows desktop '+viewport.width);await map.getByRole('button',{name:'Sonuç panelini kapat',exact:true}).click();}await analysisSelect.selectOption('LF');await metricSelect.selectOption('pFromMw');
   const footer=await map.locator('.ga-map-status').boundingBox();if(!footer||Math.abs(footer.height-26)>1||await page.locator('.ga-footer').isVisible())throw Error('Map single 26px status contract failed');
   await voltageMenu.locator('summary').click();const info=voltageMenu.locator('input[data-help-id="map.voltage.400"]'),label=info.locator('..').locator('[data-help-label]').first(),tip=page.locator('#ga-label-help');await info.hover();await page.waitForTimeout(700);if(await tip.isVisible())throw Error('Checkbox surface opens help');await label.hover();await page.waitForTimeout(300);if(await tip.isVisible())throw Error('Help opened before intentional hover delay');await tip.waitFor({state:'visible'});const box=await tip.boundingBox();if(!box||box.x<0||box.y<0||box.x+box.width>viewport.width+1||box.y+box.height>viewport.height+1||!(await tip.textContent()).includes('400 kV'))throw Error('Label tooltip exceeds viewport or wrong help');
   if(await map.locator('.ga-map-wrap').evaluate(e=>e.getBoundingClientRect().height)!==geometry.height)throw Error('Tooltip changes map height');await page.keyboard.press('Escape');if(await tip.isVisible())throw Error('Tooltip stays visible after Escape');await page.mouse.move(0,0);await voltageMenu.locator('summary').click();
   await map.getByRole('button',{name:'Elektriksel Sonuçlar',exact:true}).click();await map.locator('.ga-lightning').getByRole('button',{name:'Yük Akışı',exact:true}).click();const panelBox=await map.locator('.ga-lightning').boundingBox(),tabs=await map.locator('.ga-lightning-tabs').boundingBox();if(panelBox.width>640.1||Math.abs(tabs.height-36)>1||await map.locator('.ga-lightning-body>.ga-tabs-small').count()!==1)throw Error('Compact panel hierarchy contract failed');
   if(viewport.width===1366||viewport.width===1920){await page.mouse.move(0,0);await page.screenshot({path:'docs/screenshots/map-desktop-20261011/'+viewport.width+'.png'});}
   await map.getByRole('button',{name:'Sonuç panelini kapat',exact:true}).click();
    console.log('Map desktop '+viewport.width+'x'+viewport.height+': '+JSON.stringify(geometry));
 }
 await map.getByRole('button',{name:'Elektriksel Sonuçlar',exact:true}).click();await map.locator('.ga-lightning').getByRole('button',{name:'Yük Akışı',exact:true}).click();const panelExport=page.waitForEvent('download');await map.getByRole('button',{name:'Elektriksel sonuçları XLSX indir',exact:true}).click();if((await panelExport).suggestedFilename()!=='GridAnalyzer_FullNR_Results.xlsx')throw Error('Lightning XLSX does not export the existing LF');await page.mouse.move(0,0);await page.screenshot({path:'local-benchmark-results/desktop-map-results-640.png'});await map.locator('.ga-lightning').getByRole('button',{name:'Senaryolar',exact:true}).click();await scenarios.locator('.ga-scenario-log>summary').click();await page.mouse.move(0,0);await page.screenshot({path:'local-benchmark-results/desktop-map-scenarios-640.png'});await map.getByRole('button',{name:'Sonuç panelini kapat',exact:true}).click();
 if(await page.evaluate(()=>window.smokeWork.length)!==workBefore)throw Error('Map filters, scenario/view selection or panel started a new computation');
 if(await page.evaluate(()=>window.smokeRaf.pending.size)>1)throw Error('More than one map RAF scheduled');
 await page.getByRole('button',{name:'Ayarlar',exact:true}).click();await page.waitForTimeout(100);if(await page.evaluate(()=>window.smokeRaf.pending.size)!==0)throw Error('Map RAF kept running off-tab');
 for(const label of ['Model Yükle','Şebeke Envanteri','İşletme Verileri','Analizler','Karşılaştırma','Yardım','Ayarlar']){
   await page.locator('.ga-nav').getByRole('button',{name:label,exact:true}).click();
   if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Desktop UI overflow: '+label);
   if(await page.locator('.ga-context-help,.ga-help-field').count()||await page.getByRole('button',{name:/^Bilgi:/}).count())throw Error('Decorative information buttons remain: '+label);
   if(label==='Analizler'||label==='Ayarlar'){await page.mouse.move(0,0);await page.screenshot({path:'local-benchmark-results/desktop-map-'+(label==='Analizler'?'analysis':'settings')+'.png'});}
 }
 if(errors.length)throw Error(`Browser JS errors: ${errors.join('; ')}`);
 console.log('Chromium smoke passed: load → quality audit/JSON → N-1 catalog/filter/selection/progress/result/CSV → Full AC/XLSX → PF mismatch comparison/XLSX/CSV → structured topology → map angle/island → settings → Lightning results → SLD.');
}finally{
 await browser?.close();server.kill('SIGTERM');
}
