import test from 'node:test';import assert from 'node:assert/strict';
import type {AppContext} from '../../src/app/contracts';import type {CalculationResult} from '../../src/domain/results/types';
import {acNetwork} from '../helpers/ac-network';import {ScenarioStore} from '../../src/domain/scenario/overlay';import {ResultStore} from '../../src/domain/results/store';import {AnalysisSettingsStore} from '../../src/domain/calculation/analysis-settings';import {identity} from '../../src/domain/calculation/identity';import {initialResultView} from '../../src/domain/results/workspace';
import {defaultSettings,SettingsStore} from '../../src/persistence/settings';import {formatEngineering} from '../../src/ui/components/engineering-format';
import {mapLoadingValues} from '../../src/map/loading-presentation';import {setCapacitySeason} from '../../src/domain/model/capacity';import {engineeringLoadingColor} from '../../src/map/result-style';import {splitTopologyVisible,mapTopologyPresentation} from '../../src/map/topology-presentation';import {endpointStationLabel,verifiedPowerDirection,equipmentCard} from '../../src/map/equipment-tooltip';import {mapPresentationGate,buildMapPresentationData} from '../../src/map/layer-policy';
function fixture(){
  const base=acNetwork(),network={...base,modelHash:'synthetic-map-cards',sites:[{...base.buses[0],id:'S',sourceId:'S',sourceClass:'ElmSite',name:'Gerçek uç TM',lat:39,lon:32,voltages:[154],areaId:'A',areaName:'A'}],buses:base.buses.map((b,i)=>({...b,name:i===0?'B-1':i===1?'B-2':'Terminal',vnKv:154,siteIds:['S']})),lines:base.lines.map(l=>({...l,vnKv:154,siteIds:['S']})),switches:[{...base.buses[0],id:'C',sourceId:'C',sourceClass:'ElmCoup',from:'B0',to:'B1',siteIds:['S'],closed:false}]},scenario=new ScenarioStore(network.modelHash),analysisSettings=new AnalysisSettingsStore(),resultStore=new ResultStore(),id=identity(network.modelHash,scenario.current,'powerFlow',{analysisSettings:analysisSettings.value});
  const result={identity:id,converged:true,buses:network.buses.map((b,i)=>({id:'E'+i,name:'Bar '+i,terms:[b.id],siteIds:['S'],vnKv:154,vmPu:1,angleRad:0,islandId:'island-1'})),branches:network.lines.map(l=>({...l,pf:10,pt:-9,qf:-2,qt:3,ifA:50,itA:40,loading:null,pLoss:1,qLoss:1})),diagnostics:{islands:[{islandId:'island-1',referenceSource:'SLACK',status:'CONVERGED'}]},warnings:[],quality:{},generators:[]} as unknown as CalculationResult;resultStore.selectScenario('B0');resultStore.expect('base',id);resultStore.accept('base',result);
  const ctx={network,scenario,analysisSettings,resultStore,settings:{value:defaultSettings()},resultView:initialResultView(),benchmarkMap:{analysis:'LF',source:'GA',metric:'pFromMw',table:'GA_Reference_Raw'},benchmark:null,n1AcResults:[],n1Result:null,hybridResult:null,scResult:null,filters:{voltages:new Set(['154'])}} as unknown as AppContext;return {ctx,network,result};
}
test('split markers require explicit topology; open coupler is distinct from alternate-path component and scenario close removes it',()=>{
  const {ctx,network}=fixture(),s=ctx.benchmarkMap!;for(const metric of ['voltageKv','angleDeg','pFromMw','qFromMvar','pHvMw','qHvMvar','loadingPercent'])assert.equal(splitTopologyVisible({...s,metric},'island'),false);assert.equal(splitTopologyVisible({...s,metric:'island'},'nominal'),true);assert.equal(splitTopologyVisible({...s,analysis:'SC'},'island'),false);assert.equal(splitTopologyVisible(null,'n1-island'),true);
  const open=mapTopologyPresentation(ctx)!;assert.equal(open.data.splitStations[0].topologyRelation,'SAME_COMPONENT_VIA_ALTERNATE_PATH');ctx.network={...network,lines:network.lines.filter(l=>l.id==='L1')};assert.equal(mapTopologyPresentation(ctx)!.data.splitStations[0].topologyRelation,'SEPARATE_COMPONENTS');ctx.scenario.setStatus('switchState','C',true,false);assert.equal(mapTopologyPresentation(ctx)!.data.splitStations.length,0);assert.equal(mapPresentationGate(ctx,{...s,metric:'island'}).enabled,true);
});
test('loading uses validated current/season and transformer rated MVA; unknown and operational candidates never become zero',()=>{
  const {network,result,ctx}=fixture(),mva=(ka:number)=>Math.sqrt(3)*154*ka;network.lines[0]={...network.lines[0],capacity:{quality:'DGS_MAIN_TYPE',typeId:'T',typeName:'T',nominalCurrentKA:.1,nominalMVA:mva(.1),limitingSectionId:null,sections:[],seasonalReference:{matched:true,summerMVA:mva(.2),winterMVA:mva(.3),operationalCandidateMVA:999} as never}};
  const nominal=mapLoadingValues(network,result);assert.equal(nominal.get('ElmLne:L0')?.maximum,50);assert.equal(nominal.get('ElmLne:L0')?.from,50);assert.equal(nominal.get('ElmLne:L0')?.to,40);assert.equal(nominal.get('ElmLne:L1')?.maximum,null);
  setCapacitySeason(network.modelHash,'summer');assert.equal(mapLoadingValues(network,result).get('ElmLne:L0')?.maximum,25);for(const source of ['DELTA','EXPLORATORY_DELTA'] as const){const gate=mapPresentationGate(ctx,{...ctx.benchmarkMap!,metric:'loadingPercent',source});assert.equal(gate.enabled,false);assert.match(gate.reason,/LOADING_DENOMINATOR_UNVERIFIED/);}setCapacitySeason(network.modelHash,'operational');assert.equal(mapLoadingValues(network,result).get('ElmLne:L0')?.maximum,null);setCapacitySeason(network.modelHash,'nominal');
  const t={...network.lines[0],id:'T',sourceId:'T',sourceClass:'ElmTr2',ratingMva:100,lvKv:33,tap:1,rPu:0,xPu:.1,phase:0,gPu:0,bPu:0};ctx.network={...network,transformers:[t] as never};const r={...result,branches:[...result.branches,{...result.branches[0],id:'T',sourceClass:'ElmTr2',pf:30,qf:40,pt:-30,qt:-40}]};assert.equal(mapLoadingValues(ctx.network!,r).get('ElmTr2:T')?.maximum,50);
  const zero={...result,branches:result.branches.map(b=>({...b,ifA:0,itA:0}))};assert.equal(mapLoadingValues(network,zero).get('ElmLne:L0')?.maximum,0);assert.equal(engineeringLoadingColor(null,defaultSettings()),defaultSettings().colorNoResult);assert.equal(engineeringLoadingColor(101,defaultSettings()),defaultSettings().loadingColor6);assert.equal(engineeringLoadingColor(100,defaultSettings()),defaultSettings().loadingColor5);assert.equal(engineeringLoadingColor(25,defaultSettings()),defaultSettings().loadingColor0);assert.equal(engineeringLoadingColor(25.1,defaultSettings()),defaultSettings().loadingColor1);assert.notEqual(engineeringLoadingColor(0,defaultSettings()),defaultSettings().colorNoResult);
});
test('endpoint names come from physical terminal/site identity; canonical P/Q signs and display precision do not mutate results',()=>{
  const {ctx,network,result}=fixture(),before=JSON.stringify(result),card=equipmentCard(ctx,network.lines[0]);assert.ok(card.rows[0][0].includes('Gerçek uç TM'));assert.deepEqual(card.headers,['TM / Uç','P (MW)','Q (MVAr)','Yük (%)','U (kV)','Açı (°)']);assert.equal(card.rows[0][1],'+10,0');assert.equal(card.rows[0][2],'-2,0');assert.ok(card.note.includes('A → B'));
  assert.match(card.rows[0][0],/^A · /);assert.match(card.rows[1][0],/^B · /);assert.equal(verifiedPowerDirection(10,-9),'FROM_TO');assert.equal(verifiedPowerDirection(-10,9),'TO_FROM');assert.equal(verifiedPowerDirection(0,0),'UNKNOWN');assert.equal(verifiedPowerDirection(10,9),'UNKNOWN');assert.equal(verifiedPowerDirection(null,9),'UNKNOWN');
  ctx.settings.value.precision=2;assert.equal(equipmentCard(ctx,network.lines[0]).rows[0][1],'+10,00');assert.equal(JSON.stringify(result),before);ctx.network={...network,buses:network.buses.map(b=>({...b,siteIds:['MISSING','S']}))};assert.equal(endpointStationLabel(ctx,'B0','A').status,'TM_BELIRSIZ');
  result.diagnostics.islands=[];assert.equal(buildMapPresentationData(ctx,{...ctx.benchmarkMap!,metric:'angleDeg'}).sites.get('S')?.value,null);
});
test('engineering formatting preserves zero/null, tr-TR, negative-zero and 0–8 precision; fresh/reset 1 preserves persisted 2',()=>{
  for(const v of [null,undefined,NaN,Infinity])assert.equal(formatEngineering(v),'—');assert.equal(formatEngineering(0),'0,0');assert.equal(formatEngineering(-0.00001),'0,0');assert.equal(formatEngineering(1234.5),'1.234,5');assert.equal(formatEngineering(1.23456789,8),'1,23456789');assert.equal(formatEngineering(0,0,{signed:true}),'0');
  const descriptor=Object.getOwnPropertyDescriptor(globalThis,'localStorage');let saved='';Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:()=>saved,setItem:(_k:string,v:string)=>saved=v}});try{const fresh=new SettingsStore();assert.equal(fresh.value.precision,1);fresh.update({precision:2});assert.equal(new SettingsStore().value.precision,2);fresh.reset();assert.equal(fresh.value.precision,1);}finally{if(descriptor)Object.defineProperty(globalThis,'localStorage',descriptor);else Reflect.deleteProperty(globalThis,'localStorage');}
});
