import {test} from 'node:test';
import assert from 'node:assert/strict';
import {buildScorecard,compareScorecardVersions,TOLERANCE_VERSION,type ScorecardEvidence} from '../../src/domain/benchmark/scorecard';
import type {BenchmarkMetricRow} from '../../src/domain/benchmark/comparison';
import {scorecardEvidence} from '../../src/features/comparison/scorecard-view';
import {syntheticBenchmark} from '../helpers/benchmark';
import {loadBenchmark} from '../../src/importers/powerfactory-benchmark';
import {acNetwork} from '../helpers/ac-network';
import {ScenarioStore} from '../../src/domain/scenario/overlay';
import {defaultAnalysisSettings} from '../../src/domain/calculation/analysis-settings';
import type {AppContext} from '../../src/app/contracts';
function row(pf:number|null,ga:number|null,changes:Partial<BenchmarkMetricRow>={}):BenchmarkMetricRow{return {analysis:'LF',table:'GA_Reference_Raw',sourceClass:'ElmLne',fid:'L',name:'line',caseId:'',side:'FROM',metric:'pFromMw',pf:{value:pf,unit:'MW',rawText:pf===null?'':String(pf),availability:pf===null?'NOT_RECORDED':pf===0?'RECORDED_NUMERIC_ZERO':'RECORDED',qualityFlags:[],source:{fileSha256:'reference-hash',analysis:'LF',sheet:'GA_Reference_Raw',row:2,column:'P'}},ga,delta:null,diagnosticDelta:ga===null||pf===null?null:ga-pf,identityMatched:true,absoluteDelta:null,deltaPercent:null,status:'EXPLORATORY_ONLY',reason:'',method:'TANISAL',ytm:'',tm:'',nominalKv:400,kind:'line',...changes};}
test('Tolerance agreement uses matched pairs while coverage includes unmatched PF rows',()=>{const r=buildScorecard([row(100,101),row(100,104),row(100,null)])[0];assert.equal(r.matched,2);assert.equal(r.eligible,3);assert.equal(r.coverage,200/3);assert.equal(r.agreement,50);assert.equal(r.mae,2.5);assert.equal(r.p95,4);assert.equal(r.maximum,4);assert.equal(r.unmatched,1);});
test('Absolute plus relative tolerance remains well-defined for zero and negative PF flows',()=>{const r=buildScorecard([row(0,.5),row(-100,-102),row(null,0)])[0];assert.equal(r.matched,2);assert.equal(r.within,2);assert.equal(r.agreement,100);const missing=buildScorecard([row(null,0)])[0];assert.equal(missing.agreement,null);assert.equal(missing.coverage,null);assert.equal(missing.eligible,0);assert.equal(missing.excludedPF,1);});
test('Wrong identity, unverified SC/N1 and low voltage never invent comparison percentages',()=>{const rows=buildScorecard([row(1,1,{identityMatched:false}),row(1,1,{analysis:'SC',metric:'ikssKa'}),row(1,1,{analysis:'N1',metric:'postPmw'}),row(1,1,{nominalKv:36})]);assert.equal(rows.length,3);for(const r of rows){assert.equal(r.agreement,null);assert.equal(r.mae,null);assert.equal(r.matched,0);}const absent=buildScorecard([],true).find(r=>r.kv===220);assert.equal(absent?.eligible,0);assert.equal(absent?.agreement,null);assert.equal(absent?.coverage,null);});
test('Scorecard version trends require distinct SHAs and identical evidence',()=>{const base:ScorecardEvidence={gitSha:'a'.repeat(40),modelHash:'m',studyCase:'s',referenceHash:'r',settingsHash:'o',controlContextHash:null,toleranceVersion:TOLERANCE_VERSION,rows:buildScorecard([row(100,101)]),createdAt:'now'},next={...base,gitSha:'b'.repeat(40),rows:buildScorecard([row(100,104)])};assert.equal(compareScorecardVersions(base,next).changes[0].agreementChange,-100);assert.equal(compareScorecardVersions(base,{...next,referenceHash:'other'}).status,'EVIDENCE_MISMATCH:referenceHash');assert.equal(compareScorecardVersions(base,base).status,'NO_DISTINCT_VERSION');});
test('Voltage, equipment and metric strata retain separate denominators and units',()=>{const r=buildScorecard([row(1,1),row(1,1,{nominalKv:154}),row(1,1,{kind:'transformer',metric:'pHvMw',sourceClass:'ElmTr2'}),row(1,1,{metric:'qFromMvar',pf:{...row(1,1).pf,unit:'Mvar'}})]);assert.equal(r.length,4);assert.ok(r.every(r=>r.eligible===1));assert.equal(r.find(r=>r.metric==='qFromMvar')?.unit,'Mvar');});
test('The production scorecard accepts a large reference corpus without argument-stack overflow',async()=>{const b=await loadBenchmark(syntheticBenchmark(undefined,undefined,{LF:{GA_Reference_Raw:[{kind:'line',fid:'LARGE-LINE',sourceClass:'ElmLne',nominalKv:400,pFromMw:0,qFromMvar:0,pToMw:0,qToMvar:0,resultAvailable:1}]}})),table=b.groups.LF.tables.GA_Reference_Raw;table.rows=Array.from({length:12000},()=>table.rows[0]);table.rowNumbers=Array.from({length:12000},(_,i)=>i+2);const ctx={network:{...acNetwork(),studyCase:'other'},benchmark:b,resultStore:{get:()=>null},scenario:new ScenarioStore(),analysisSettings:{value:defaultAnalysisSettings()},powerFactoryControlContextHash:null,powerFactoryControlContextNumericFile:null} as unknown as AppContext;const r=scorecardEvidence(ctx);assert.equal(r.rows.find(r=>r.metric==='pFromMw')?.eligible,12000);assert.ok(r.rows.every(r=>r.agreement===null));});
