import test from 'node:test';
import assert from 'node:assert/strict';
import {unzipSync,zipSync,strToU8,strFromU8} from 'fflate';
import {syntheticBenchmarkPair} from '../helpers/benchmark-model';
import {loadBenchmark,loadBenchmarkReferences} from '../../src/importers/powerfactory-benchmark';
import {loadBenchmarkModel} from '../../src/importers/powerfactory-benchmark/model';
import {hasReference,mergeReferenceSlots} from '../../src/domain/benchmark/reference-slots';
import {preflightBenchmark} from '../../src/domain/benchmark/comparison';
import {helpEntry,helpForField,helpRegistry} from '../../src/help/registry';
import type {BenchmarkAnalysis} from '../../src/domain/benchmark/types';
async function single(file:File,analysis:BenchmarkAnalysis){const files=unzipSync(new Uint8Array(await file.arrayBuffer()));return new File([zipSync(Object.fromEntries(Object.entries(files).filter(([name])=>name.startsWith(analysis+'.'))))],analysis+'.zip');}
test('strict combined API retains nine-file contract; attachment API accepts all three separate families',async()=>{const pair=syntheticBenchmarkPair();assert.deepEqual((await loadBenchmark(pair.benchmark)).availableAnalyses,['LF','N1','SC']);for(const a of ['LF','N1','SC'] as const){const file=await single(pair.benchmark,a);await assert.rejects(loadBenchmark(file),/SOURCE_SCHEMA_MISMATCH/);const p=await loadBenchmarkReferences(file);assert.deepEqual(p.availableAnalyses,[a]);assert.ok(hasReference(p,a));}});
test('independent attachments preserve other slots, source archives and active canonical data',async()=>{const pair=syntheticBenchmarkPair(true),{network}=await loadBenchmarkModel(pair.model),before=JSON.stringify(network);let p=null;for(const a of ['SC','N1','LF'] as const)p=mergeReferenceSlots(p,await loadBenchmarkReferences(await single(pair.benchmark,a)),network);assert.deepEqual(p!.availableAnalyses,['LF','N1','SC']);const old=p!.groups.N1;p=mergeReferenceSlots(p,await loadBenchmarkReferences(await single(pair.benchmark,'SC')),network);assert.equal(p.groups.N1,old);assert.equal(JSON.stringify(network),before);assert.equal(Object.keys(p.sourceArchives!).length,3);});
test('different active StudyCase is rejected before slot mutation',async()=>{const pair=syntheticBenchmarkPair(true),{network}=await loadBenchmarkModel(pair.model),p=await loadBenchmarkReferences(await single(pair.benchmark,'SC'));assert.throws(()=>mergeReferenceSlots(null,p,{...network,studyCase:'SN4'}),/active model StudyCase/);assert.deepEqual(p.availableAnalyses,['SC']);});
test('mixed exporter model/scenario/topology identities reject atomically and preserve previous slot',async()=>{const pair=syntheticBenchmarkPair(true),{network}=await loadBenchmarkModel(pair.model),old=await loadBenchmarkReferences(await single(pair.benchmark,'LF')),n1=await loadBenchmarkReferences(await single(pair.benchmark,'N1'));for(const field of ['modelHash','scenarioHash','topologyHash','studyTime','project','pfVersion']){const changed=structuredClone(n1);changed.groups.N1.identity[field]='OTHER';assert.throws(()=>mergeReferenceSlots(old,changed,network),/reference slot/);assert.deepEqual(old.availableAnalyses,['LF']);}});
test('single-analysis workbook SHA and exporter manifest gates remain mandatory',async()=>{const pair=syntheticBenchmarkPair();const files=unzipSync(new Uint8Array(await (await single(pair.benchmark,'N1')).arrayBuffer()));const raw=JSON.parse(strFromU8(files['N1.json']));raw.workbook.sha256='0'.repeat(64);files['N1.json']=strToU8(JSON.stringify(raw));await assert.rejects(loadBenchmarkReferences(new File([zipSync(files)],'bad.zip')),/WORKBOOK_HASH_MISMATCH/);raw.workbook=JSON.parse(strFromU8(unzipSync(new Uint8Array(await (await single(pair.benchmark,'N1')).arrayBuffer()))['N1.json'])).workbook;raw.identity.addonVersion='OTHER';files['N1.json']=strToU8(JSON.stringify(raw));await assert.rejects(loadBenchmarkReferences(new File([zipSync(files)],'bad.zip')),/BENCHMARK_IDENTITY_MISMATCH/);});
test('partial N1/SC package cannot synthesize an LF reference or certified difference',async()=>{const pair=syntheticBenchmarkPair(true),{network}=await loadBenchmarkModel(pair.model),p=await loadBenchmarkReferences(await single(pair.benchmark,'SC'));assert.equal(hasReference(p,'LF'),false);assert.equal(p.groups.LF.tables.GA_Reference_Raw.rows.length,0);const gate=preflightBenchmark(p,network,null);assert.equal(gate.status,'NOT_COMPARABLE');assert.deepEqual(gate.reasons,['LF_REFERENCE_NOT_LOADED']);assert.equal(gate.comparison,null);});
test('native fault/outage membership is required even when StudyCase matches',async()=>{const pair=syntheticBenchmarkPair(true),{network}=await loadBenchmarkModel(pair.model),p=await loadBenchmarkReferences(await single(pair.benchmark,'SC')),table=p.groups.SC.tables.SC_BusResults_Raw;table.rows[0][table.headers.indexOf('physicalTerminalFid')]='OTHER';assert.throws(()=>mergeReferenceSlots(null,p,network),/native fault FID/);});
test('one typed registry supplies parameter help with scientific caveats',()=>{assert.equal(new Set(helpRegistry.map(e=>e.id)).size,helpRegistry.length);for(const e of helpRegistry){for(const key of ['id','title','shortText','fullText','section','relatedScreen','relatedField'] as const)assert.ok(e[key]);assert.ok(e.tags.length);}assert.equal(helpForField('Hibrit kontrol profili','analysis:N1'),helpEntry('n1.studyProfile'));assert.equal(helpForField('SC açık NETWORK_APPROXIMATION','analysis:SC'),helpEntry('sc.networkApproximation'));assert.match(helpEntry('compare.methodGate')!.shortText,/null/);assert.match(helpEntry('sc.faultMode')!.fullText,/Ip\/Ib\/Ith null/);});
