import type { AppContext, Feature } from '../../app/contracts';
import { element, button, escapeHtml as h, format as f, csvDocument, downloadText } from '../../ui/components/dom';
import type { ModelQualityFinding } from '../../domain/model-quality';
import type { N1ScreenCandidate, N1ScreenOptions, N1ScreenResult } from '../../domain/n1';
import { n1OptionsIdentity } from '../../domain/n1';
import type { CapacitySeason } from '../../domain/model/capacity';
import { scenarioSignature } from '../../domain/scenario/overlay';

const categories=['TOPOLOGY','ELECTRICAL_DATA','CAPACITY','CONTROLLER','REDUCED_MODEL','PROVENANCE'];
const severities=['BLOCKER','ERROR','WARNING','INFO'];
export function createQualityN1View(ctx:AppContext):Feature{
  const root=element('section','ga-analysis-view'),heading=element('h2','','Kalite & N-1'),tabs=element('div','ga-tabs-small'),content=element('div','ga-panel'),qualityTab=button('MODEL KALİTESİ',()=>{active='quality';render();}),n1Tab=button('N-1 TARAMA',()=>{active='n1';render();});
  let active='quality',selectedFinding:string|null=null,selectedCandidate:string|null=null,qualityPage=0,n1Page=0;
  const qualityControls=element('div','ga-analysis-controls'),runQuality=button('Kalite denetimini çalıştır',()=>void ctx.runModelQuality()),qualitySearch=element('input'),category=element('select'),severity=element('select'),voltage=element('select');
  const qualityCsvButton=button('CSV indir',exportQualityCsv),qualityJsonButton=button('JSON indir',exportQualityJson),n1CsvButton=button('CSV indir',exportN1Csv),n1JsonButton=button('JSON indir',exportN1Json);
  qualitySearch.type='search';qualitySearch.placeholder='Bulgu veya ekipman ara';qualitySearch.setAttribute('aria-label','Model kalitesi bulgularında ara');qualitySearch.oninput=()=>{qualityPage=0;render();};
  category.innerHTML='<option value="">Tüm kategoriler</option>'+categories.map(x=>`<option value="${x}">${x}</option>`).join('');category.setAttribute('aria-label','Bulgu kategorisi');category.onchange=()=>{qualityPage=0;render();};
  severity.innerHTML='<option value="">Tüm önem düzeyleri</option>'+severities.map(x=>`<option value="${x}">${x}</option>`).join('');severity.setAttribute('aria-label','Bulgu önem düzeyi');severity.onchange=()=>{qualityPage=0;render();};
  voltage.innerHTML='<option value="">Tüm gerilimler</option><option value="66">66 kV ve üstü</option><option value="154">154 kV ve üstü</option><option value="220">220 kV ve üstü</option><option value="400">400 kV ve üstü</option>';voltage.setAttribute('aria-label','Bulgu gerilim filtresi');voltage.onchange=()=>{qualityPage=0;render();};
  qualityControls.append(runQuality,qualityCsvButton,qualityJsonButton);
  const qualityFilters=element('div','ga-toolbar');qualityFilters.append(category,severity,voltage,qualitySearch);
  const qualityStatus=element('p','ga-notice'),n1Warning=element('p','ga-notice','DC PTDF/LODF screening · AC doğrulaması değildir.'),n1Controls=element('div','ga-analysis-controls'),lineCheck=element('input'),trafoCheck=element('input'),minVoltage=element('select'),season=element('select');
  const lineLabel=element('label','','Hatlar'),trafoLabel=element('label','','Trafolar'),startN1=button('N-1 Taramayı Başlat',()=>void ctx.runN1Screen(readOptions())),cancelN1=button('İptal',()=>ctx.cancel());
  lineCheck.type='checkbox';lineCheck.checked=true;lineLabel.prepend(lineCheck);trafoCheck.type='checkbox';trafoCheck.checked=true;trafoLabel.prepend(trafoCheck);
  minVoltage.innerHTML='<option value="66">En az 66 kV</option><option value="100">En az 100 kV</option><option value="154">En az 154 kV</option><option value="220">En az 220 kV</option><option value="300">En az 300 kV</option>';minVoltage.setAttribute('aria-label','N-1 en düşük gerilim');
  season.innerHTML='<option value="nominal">Nominal kapasite</option><option value="summer">Yaz kapasitesi</option><option value="winter">Kış kapasitesi</option><option value="operational">İşletme kapasitesi</option>';season.setAttribute('aria-label','Kapasite mevsimi');
  n1Controls.append(lineLabel,trafoLabel,minVoltage,season,startN1,cancelN1,n1CsvButton,n1JsonButton);
  for(const control of [lineCheck,trafoCheck,minVoltage,season])control.addEventListener('change',()=>render());
  tabs.append(qualityTab,n1Tab);root.append(heading,tabs,qualityControls,qualityFilters,n1Warning,n1Controls,content);

  function readOptions():N1ScreenOptions{return{candidateTypes:[...(lineCheck.checked?['ElmLne' as const]:[]),...(trafoCheck.checked?['ElmTr2' as const]:[])],minVoltageKv:Number(minVoltage.value),capacitySeason:season.value as CapacitySeason};}
  function voltageFor(finding:ModelQualityFinding):number|null{
    const n=ctx.network;if(!n||!finding.entityId)return typeof finding.originalValue==='number'&&finding.field?.toLowerCase().includes('vn')?finding.originalValue:null;
    const id=finding.entityId;
    const bus=n.buses.find(x=>x.id===id);if(bus)return bus.vnKv;
    const line=n.lines.find(x=>x.id===id);if(line)return line.fastParameters?.vnKv??line.vnKv;
    const transformer=n.transformers.find(x=>x.id===id);if(transformer)return Math.max(transformer.vnKv,transformer.lvKv);
    const gen=n.generators.find(x=>x.id===id);if(gen)return n.buses.find(x=>x.id===gen.bus)?.vnKv??null;
    return null;
  }
  function filteredFindings():ModelQualityFinding[]{
    const findings=ctx.modelQualityResult?.findings||[],q=qualitySearch.value.toLocaleLowerCase('tr-TR'),min=Number(voltage.value)||0;
    return findings.filter(x=>(!category.value||x.category===category.value)&&(!severity.value||x.severity===severity.value)&&(!min||(voltageFor(x)??0)>=min)&&(!q||`${x.code} ${x.entityName||''} ${x.entityId||''} ${x.field||''} ${x.message} ${x.calculationImpact}`.toLocaleLowerCase('tr-TR').includes(q)));
  }
  function selectedQualityDetail():HTMLElement{
    const finding=ctx.modelQualityResult?.findings.find(x=>x.id===selectedFinding);if(!finding)return element('p','ga-muted','Bir bulgu seçin.');
    const box=element('div','ga-panel');box.innerHTML=`<h3>${h(finding.code)} · ${h(finding.severity)}</h3><p><strong>Sınıf / FID:</strong> ${h(finding.entityClass||'—')} / ${h(finding.entityId||'—')} · ${h(finding.entityName||'')}</p><p><strong>Kaynak alanı / değer / birim:</strong> ${h(finding.field||'—')} · ${h(JSON.stringify(finding.originalValue))} → ${h(JSON.stringify(finding.normalizedValue))} ${h(finding.unit||'')}</p><p><strong>Mesaj:</strong> ${h(finding.message)}</p><p><strong>Hesaplama etkisi:</strong> ${h(finding.calculationImpact)}</p><p><strong>Kaynak referansları:</strong> ${h(JSON.stringify(finding.sourceRefs))}</p>`;
    const actions=element('div','ga-row-actions');if(finding.entityId&&finding.entityClass){actions.append(button('Haritada göster',()=>ctx.select(finding.entityId!,finding.entityClass!,'map')),button('Envanter',()=>ctx.select(finding.entityId!,finding.entityClass!,'inventory')),button('Tek Hat',()=>ctx.select(finding.entityId!,finding.entityClass!,'sld')));}box.append(actions);return box;
  }
  function renderQuality(){
    const result=ctx.modelQualityResult,n=ctx.network;qualityControls.hidden=false;qualityFilters.hidden=false;qualityStatus.hidden=false;n1Warning.hidden=true;n1Controls.hidden=true;
    runQuality.disabled=ctx.busy||!n;qualityStatus.textContent=!n?'Önce bir model yükleyin.':!result?'Modeli değiştirmeden yüksek değerli kalite kontrollerini çalıştırın.':result.modelHash!==n.modelHash||ctx.modelQualityScenarioHash!==scenarioSignature(ctx.scenario.current)?'Model veya senaryo değişti; kalite bulguları eski kimliğe ait.':`${result.summary.total} bulgu · ${result.modelHash.slice(0,12)}`;
    content.replaceChildren(qualityStatus);
    if(result&&n&&result.modelHash===n.modelHash&&ctx.modelQualityScenarioHash===scenarioSignature(ctx.scenario.current)){const cards=element('div','ga-card-grid');for(const level of severities){const card=element('div','ga-card');card.innerHTML=`<small>${level}</small><strong>${result.summary.counts[level as keyof typeof result.summary.counts]}</strong>`;cards.append(card);}content.append(cards);
      const visible=filteredFindings();qualityPage=Math.min(qualityPage,Math.max(0,Math.ceil(visible.length/20)-1));const pageRows=visible.slice(qualityPage*20,qualityPage*20+20),wrap=element('div','ga-table-wrap'),table=element('table','ga-table');table.innerHTML=`<thead><tr><th>Önem</th><th>Kod</th><th>Ekipman</th><th>Alan</th><th>Bulgu</th><th>Hesaplama etkisi</th></tr></thead><tbody>${pageRows.map(x=>`<tr data-id="${h(x.id)}" class="${x.id===selectedFinding?'ga-selected':''}"><td>${h(x.severity)}</td><td>${h(x.code)}</td><td>${h(x.entityName||x.entityId||x.entityClass||'—')}<small>${h(x.entityClass||'')} ${h(x.entityId||'')}</small></td><td>${h(x.field||'—')}</td><td>${h(x.message)}</td><td>${h(x.calculationImpact)}</td></tr>`).join('')}</tbody>`;
      table.querySelectorAll<HTMLTableRowElement>('tbody tr').forEach(row=>row.onclick=()=>{selectedFinding=row.dataset.id||null;render();});wrap.append(table);content.append(wrap,pager(visible.length,qualityPage,p=>{qualityPage=p;render();}),selectedQualityDetail());
    }
  }
  function selectedN1Detail(candidate:N1ScreenCandidate|undefined):HTMLElement{
    if(!candidate)return element('p','ga-muted','Bir aday seçin.');const box=element('div','ga-panel');box.innerHTML=`<h3>${h(candidate.name)} · ${h(candidate.status)}</h3><p><strong>FID / sınıf:</strong> ${h(candidate.equipmentId)} / ${h(candidate.sourceClass)} · ${f(candidate.vnKv)} kV</p><p><strong>Temel akış:</strong> ${f(candidate.baseFlowMw)} MW · <strong>En yüksek tahmini yüklenme:</strong> ${f(candidate.maxEstimatedLoadingPct)}% · <strong>Tahmini aşırı yük sayısı:</strong> ${candidate.estimatedOverloadCount} · <strong>En yüksek |ΔP|:</strong> ${f(candidate.maxDeltaPMw)} MW</p><p><strong>Rating kapsamı:</strong> ${candidate.ratingCoverage.ratedBranches}/${candidate.ratingCoverage.totalBranches} dal (${f(candidate.ratingCoverage.percent)}%) · ${h(candidate.exclusionReason||'')}</p><h4>En çok etkilenen dallar · P-only DC screening estimate</h4>`;
    const impactWrap=element('div','ga-table-wrap'),table=element('table','ga-table');table.innerHTML=`<thead><tr><th>Ekipman</th><th>Uçlar</th><th>Baz MW</th><th>Son MW</th><th>ΔP MW</th><th>Tahmini yüklenme</th></tr></thead><tbody>${candidate.topImpacts.map(x=>`<tr><td>${h(x.equipmentId)}<small>${h(x.sourceClass)}</small></td><td>${h(x.from)} → ${h(x.to)}</td><td>${f(x.baseFlowMw)}</td><td>${f(x.postFlowMw)}</td><td>${f(x.deltaPMw)}</td><td>${x.estimatedLoadingPct==null?'KAPASİTE YOK':f(x.estimatedLoadingPct)+'%'}</td></tr>`).join('')}</tbody>`;impactWrap.append(table);box.append(impactWrap);
    box.append(element('p','ga-notice','DC aktif güç tahminidir; AC doğrulaması yapılmadı.'));const actions=element('div','ga-row-actions');actions.append(button('Haritada göster',()=>ctx.select(candidate.equipmentId,candidate.sourceClass,'map')),button('Tek Hat',()=>ctx.select(candidate.equipmentId,candidate.sourceClass,'sld')));box.append(actions);return box;
  }
  function renderN1(){
    const n=ctx.network,result=ctx.n1Result,options=readOptions();qualityControls.hidden=true;qualityFilters.hidden=true;qualityStatus.hidden=true;n1Warning.hidden=false;n1Controls.hidden=false;
    startN1.disabled=ctx.busy||!n||options.candidateTypes?.length===0;cancelN1.disabled=!ctx.busy;
    const current=n? n1OptionsIdentity(n,ctx.scenario.current,options):null,stale=!!result&&(!current||result.identity.modelHash!==current.modelHash||result.identity.scenarioHash!==current.scenarioHash||result.identity.optionsHash!==current.optionsHash||result.identity.engineVersion!==current.engineVersion);
    content.replaceChildren();if(!n){content.append(element('p','ga-notice','Önce bir model yükleyin.'));return;}
    if(stale)content.append(element('p','ga-notice ga-notice-error','N-1 sonucu eski model, senaryo veya filtre kimliğine ait. Yeni tarama başlatın.'));
    if(!result||stale)return;
    const summary=element('div','ga-card-grid');for(const [label,value]of [['Adaylar',result.candidateCount],['Taranan',result.screenedCount],['Islanding',result.islandingCount],['Ekran ihlali',result.candidates.filter(x=>x.status==='SCREENED_VIOLATION').length],['Rating yok',result.unratedCount],['Desteklenmeyen',result.unsupportedCount],['Süre s',(result.elapsedMs/1000).toFixed(2)]]){const card=element('div','ga-card');card.innerHTML=`<small>${h(label)}</small><strong>${h(value)}</strong>`;summary.append(card);}content.append(summary);
    const rows=result.candidates;n1Page=Math.min(n1Page,Math.max(0,Math.ceil(rows.length/20)-1));const pageRows=rows.slice(n1Page*20,n1Page*20+20),tableWrap=element('div','ga-table-wrap'),table=element('table','ga-table');table.innerHTML=`<thead><tr><th>Öncelik</th><th>Outage</th><th>Sınıf</th><th>kV</th><th>Durum</th><th>En yüksek tahmini yüklenme</th><th>Aşırı yük sayısı</th><th>Max ΔP</th></tr></thead><tbody>${pageRows.map((x,i)=>`<tr data-id="${h(x.candidateId)}" class="${x.candidateId===selectedCandidate?'ga-selected':''}"><td>${n1Page*20+i+1}</td><td>${h(x.name)}<small>${h(x.equipmentId)}</small></td><td>${h(x.sourceClass)}</td><td>${f(x.vnKv)}</td><td>${h(x.status)}</td><td>${x.maxEstimatedLoadingPct==null?'—':f(x.maxEstimatedLoadingPct)+'% · P-only DC'}</td><td>${x.estimatedOverloadCount}</td><td>${f(x.maxDeltaPMw)} MW</td></tr>`).join('')}</tbody>`;table.querySelectorAll<HTMLTableRowElement>('tbody tr').forEach(row=>row.onclick=()=>{selectedCandidate=row.dataset.id||null;render();});tableWrap.append(table);content.append(tableWrap,pager(rows.length,n1Page,p=>{n1Page=p;render();}),selectedN1Detail(rows.find(x=>x.candidateId===selectedCandidate)));
  }
  function isQualityCurrent(){return !!ctx.network&&!!ctx.modelQualityResult&&ctx.modelQualityResult.modelHash===ctx.network.modelHash&&ctx.modelQualityScenarioHash===scenarioSignature(ctx.scenario.current);}
  function isN1Current(){if(!ctx.network||!ctx.n1Result)return false;const current=n1OptionsIdentity(ctx.network,ctx.scenario.current,readOptions()),saved=ctx.n1Result.identity;return current.modelHash===saved.modelHash&&current.scenarioHash===saved.scenarioHash&&current.optionsHash===saved.optionsHash&&current.engineVersion===saved.engineVersion;}
  function exportQualityJson(){if(isQualityCurrent())downloadText(JSON.stringify(ctx.modelQualityResult,null,2),'GridAnalyzer-model-quality.json','application/json;charset=utf-8');}
  function exportQualityCsv(){const result=isQualityCurrent()?ctx.modelQualityResult:null;if(!result)return;downloadText(csvDocument([['id','code','severity','category','entityClass','entityId','entityName','field','originalValue','normalizedValue','unit','message','calculationImpact','sourceRefs'],...result.findings.map(x=>[x.id,x.code,x.severity,x.category,x.entityClass,x.entityId,x.entityName,x.field,JSON.stringify(x.originalValue),JSON.stringify(x.normalizedValue),x.unit,x.message,x.calculationImpact,JSON.stringify(x.sourceRefs)])]),'GridAnalyzer-model-quality.csv','text/csv;charset=utf-8');}
  function exportN1Json(){if(isN1Current())downloadText(JSON.stringify(ctx.n1Result,null,2),'GridAnalyzer-n1-screening.json','application/json;charset=utf-8');}
  function exportN1Csv(){const result=isN1Current()?ctx.n1Result:null;if(!result)return;downloadText(csvDocument([['candidateId','equipmentId','sourceClass','name','vnKv','from','to','status','islanding','baseFlowMw','maxEstimatedLoadingPct','estimatedOverloadCount','maxDeltaPMw','ratedBranches','totalBranches','ratingCoveragePct','exclusionReason'],...result.candidates.map(x=>[x.candidateId,x.equipmentId,x.sourceClass,x.name,x.vnKv,x.from,x.to,x.status,x.islanding,x.baseFlowMw,x.maxEstimatedLoadingPct,x.estimatedOverloadCount,x.maxDeltaPMw,x.ratingCoverage.ratedBranches,x.ratingCoverage.totalBranches,x.ratingCoverage.percent,x.exclusionReason])]),'GridAnalyzer-n1-summary.csv','text/csv;charset=utf-8');}
  function pager(total:number,page:number,setPage:(page:number)=>void):HTMLElement{const pages=Math.ceil(total/20),bar=element('div','ga-pager');bar.append(button('Önceki',()=>setPage(Math.max(0,page-1))),element('span','',`${total.toLocaleString('tr-TR')} kayıt · ${pages?page+1:0}/${pages}`),button('Sonraki',()=>setPage(Math.min(Math.max(0,pages-1),page+1))));(bar.firstElementChild as HTMLButtonElement).disabled=page<=0;(bar.lastElementChild as HTMLButtonElement).disabled=page>=pages-1;return bar;}
  function render(){qualityTab.setAttribute('aria-pressed',String(active==='quality'));n1Tab.setAttribute('aria-pressed',String(active==='n1'));content.replaceChildren();qualityCsvButton.disabled=qualityJsonButton.disabled=!isQualityCurrent();n1CsvButton.disabled=n1JsonButton.disabled=!isN1Current();if(active==='quality')renderQuality();else renderN1();}
  return{element:root,render};
}
