import type { AppContext, Feature } from '../../app/contracts';
import { element, button, escapeHtml as h, format as f, csvDocument, downloadText } from '../../ui/components/dom';
import type { ModelQualityFinding } from '../../domain/model-quality';
import type { N1Progress, N1ScreenOptions, N1SourceClass } from '../../domain/n1';
import { n1OptionsIdentity } from '../../domain/n1';
import { filterN1CatalogCandidates, type N1CatalogCandidate, type N1CatalogScreenability } from '../../domain/n1/catalog';
import type { CapacitySeason } from '../../domain/model/capacity';
import { calculationScenario, scenarioSignature } from '../../domain/scenario/overlay';
import { categoryLabels, qualityPresentation, severityLabels, severityOrder } from './presentation';
import { compareQuality, sortN1, type SortDirection } from './sorting';
import { createN1ResultsView } from './results-view';

type Scope='base'|'scenario';
const categories=['TOPOLOGY','ELECTRICAL_DATA','CAPACITY','CONTROLLER','REDUCED_MODEL','PROVENANCE'] as const;
const bands=['all','400','220','154','66'] as const;
type VoltageBandFilter=typeof bands[number];
const bandRange=(value:VoltageBandFilter):{minVoltageKv?:number;maxVoltageKv?:number}=>value==='400'?{minVoltageKv:300}:value==='220'?{minVoltageKv:180,maxVoltageKv:299.999}:value==='154'?{minVoltageKv:100,maxVoltageKv:179.999}:value==='66'?{minVoltageKv:66,maxVoltageKv:99.999}:{};
const progressLabels:Record<N1Progress['stage'],string>={N1_TOPOLOGY:'Topoloji sınıflandırması',N1_FACTOR:'DC matrisi hazırlığı',N1_SCREEN:'PTDF/LODF taraması',N1_RESULT:'Sonuçlar hazırlanıyor'};

function isDefaultN1Candidate(candidate:N1CatalogCandidate):boolean{return candidate.topology==='ISLANDING'||(candidate.topology==='NON_ISLANDING'&&candidate.screenable);}
export function defaultN1CandidateIds(candidates:readonly N1CatalogCandidate[]):string[]{return candidates.filter(isDefaultN1Candidate).map(candidate=>candidate.candidateId).sort((a,b)=>a.localeCompare(b));}

export function createQualityN1View(ctx:AppContext):Feature{
  const root=element('section','ga-analysis-view'),heading=element('h2','','Kalite & N-1'),scopeRow=element('div','ga-toolbar'),scopeLabel=element('label','','Analiz kapsamı'),scopeSelect=element('select'),scenarioCount=element('span','ga-muted'),tabs=element('div','ga-tabs-small'),content=element('div','ga-panel');
  let scope:Scope='scenario',active:'quality'|'scenarios'|'results'='quality',selectedFinding:string|null=null;
  let qualityPage=0,candidatePage=0,qualityGroup='',qualitySort='severity',qualityDirection:SortDirection='asc',candidateSort='name',candidateDirection:SortDirection='asc',catalogRequestKey='',catalogFailedKey='';
  const qualityTab=button('MODEL KALİTESİ',()=>{active='quality';render();}),scenarioTab=button('N-1 SENARYOLARI',()=>{active='scenarios';render();}),resultTab=button('N-1 SONUÇLARI',()=>{active='results';render();});
  scopeSelect.setAttribute('aria-label','Model kalite ve N-1 analiz kapsamı');scopeSelect.innerHTML='<option value="base">Baz Model</option><option value="scenario">Aktif Senaryo</option>';scopeSelect.onchange=()=>{scope=scopeSelect.value as Scope;catalogRequestKey='';render();};
  scopeLabel.append(scopeSelect);scopeRow.append(scopeLabel,scenarioCount);tabs.append(qualityTab,scenarioTab,resultTab);

  const qualityControls=element('div','ga-analysis-controls'),runQuality=button('Kalite denetimini çalıştır',()=>void ctx.runModelQuality(scope)),qualityCsv=button('CSV indir',exportQualityCsv),qualityJson=button('JSON indir',exportQualityJson);
  const qualitySearch=element('input'),qualitySeverity=element('select'),qualityCategory=element('select'),qualityVoltageFilter=element('select'),qualityGroupFilter=element('select');
  qualitySearch.type='search';qualitySearch.placeholder='Bulgu veya ekipman ara';qualitySearch.setAttribute('aria-label','Model kalitesi bulgularında ara');qualitySearch.oninput=()=>{qualityPage=0;render();};
  qualitySeverity.innerHTML='<option value="">Tüm önem düzeyleri</option>'+severityOrder.map(x=>`<option value="${x}">${severityLabels[x]}</option>`).join('');qualitySeverity.setAttribute('aria-label','Bulgu önem düzeyi');qualitySeverity.onchange=()=>{qualityPage=0;render();};
  qualityCategory.innerHTML='<option value="">Tüm kategoriler</option>'+categories.map(x=>`<option value="${x}">${categoryLabels[x]}</option>`).join('');qualityCategory.setAttribute('aria-label','Bulgu kategorisi');qualityCategory.onchange=()=>{qualityPage=0;render();};
  qualityVoltageFilter.innerHTML='<option value="">Tüm gerilimler</option><option value="66">66 kV ve üstü</option><option value="154">154 kV ve üstü</option><option value="220">220 kV ve üstü</option><option value="400">400 kV ve üstü</option>';qualityVoltageFilter.setAttribute('aria-label','Bulgu gerilim filtresi');qualityVoltageFilter.onchange=()=>{qualityPage=0;render();};
  qualityGroupFilter.setAttribute('aria-label','Bulgu grubu');qualityGroupFilter.onchange=()=>{qualityGroup=qualityGroupFilter.value;qualityPage=0;render();};
  qualityControls.append(runQuality,qualityCsv,qualityJson);
  const qualityFilters=element('div','ga-toolbar');qualityFilters.append(qualitySeverity,qualityCategory,qualityVoltageFilter,qualityGroupFilter,qualitySearch);
  const qualityStatus=element('p','ga-notice');

  const candidateControls=element('div','ga-analysis-controls'),lineCheck=element('input'),trafoCheck=element('input'),season=element('select'),ytm=element('select'),tm=element('select'),candidateVoltage=element('select'),screenability=element('select'),candidateSearch=element('input');
  const lineLabel=element('label','','Hat'),trafoLabel=element('label','','Trafo');lineCheck.type='checkbox';lineCheck.checked=true;lineCheck.setAttribute('aria-label','Hat adayları');lineLabel.prepend(lineCheck);trafoCheck.type='checkbox';trafoCheck.checked=true;trafoCheck.setAttribute('aria-label','Trafo adayları');trafoLabel.prepend(trafoCheck);
  season.innerHTML='<option value="nominal">Nominal kapasite</option><option value="summer">Yaz kapasitesi</option><option value="winter">Kış kapasitesi</option><option value="operational">İşletme kapasitesi</option>';season.setAttribute('aria-label','Kapasite dönemi');
  ytm.setAttribute('aria-label','YTM filtresi');tm.setAttribute('aria-label','TM filtresi');
  candidateVoltage.innerHTML='<option value="all">Tüm gerilimler</option><option value="400">400 kV</option><option value="220">220 kV</option><option value="154">154 kV</option><option value="66">66 kV</option>';candidateVoltage.setAttribute('aria-label','Aday gerilim filtresi');
  screenability.innerHTML='<option value="SCREENABLE_ISLANDING">Taranabilir + ada ayıran</option><option value="SCREENABLE">Yalnız DC taranabilir</option><option value="ALL">Tümü</option><option value="ISLANDING">Ada ayıran</option><option value="UNSCREENABLE">Taranamayan</option>';screenability.setAttribute('aria-label','Taranabilirlik filtresi');
  candidateSearch.type='search';candidateSearch.placeholder='Aday veya FID ara';candidateSearch.setAttribute('aria-label','N-1 adaylarında ara');
  const refreshCatalog=button('Kataloğu yenile',()=>{catalogRequestKey='';catalogFailedKey='';render();}),selectAllFiltered=button('Filtredekileri seç',()=>selectFiltered()),selectAll=button('Tüm adayları seç',()=>selectCatalog()),clearSelection=button('Seçimi temizle',()=>{selectedIds.clear();render();}),runN1=button('Seçili senaryoları tara',()=>void ctx.runN1Screen(readOptions())),cancelN1=button('İptal',()=>ctx.cancel());
  candidateControls.append(lineLabel,trafoLabel,season,ytm,tm,candidateVoltage,screenability,candidateSearch,refreshCatalog,selectAllFiltered,selectAll,clearSelection,runN1,cancelN1);
  const candidateStatus=element('p','ga-notice'),progressPanel=element('div','ga-notice'),candidateContent=element('div');
  const n1Results=createN1ResultsView(ctx,()=>currentN1()),resultsControls=n1Results.controls,resultsNotice=n1Results.notice;
  const selectedIds=new Set<string>();
  for(const input of [lineCheck,trafoCheck,candidateVoltage,screenability,season,ytm,tm])input.addEventListener('change',()=>{candidatePage=0;render();});
  candidateSearch.oninput=()=>{candidatePage=0;render();};
  ytm.onchange=()=>{tm.value='';candidatePage=0;render();};
  root.append(heading,scopeRow,tabs,qualityControls,qualityFilters,qualityStatus,candidateControls,candidateStatus,progressPanel,candidateContent,resultsNotice,resultsControls,content);

  function selectedScenario():ReturnType<typeof calculationScenario>{return calculationScenario(ctx.scenario.current,scope);}
  function currentCatalogIdentity(){if(!ctx.network)return null;const s=selectedScenario();return{modelHash:ctx.network.modelHash,scenarioHash:scenarioSignature(s),analysisScope:scope,capacitySeason:season.value as CapacitySeason};}
  function sameCatalogIdentity(a:AppContext['n1CatalogIdentity'],b:ReturnType<typeof currentCatalogIdentity>){return!!a&&!!b&&a.modelHash===b.modelHash&&a.scenarioHash===b.scenarioHash&&a.analysisScope===b.analysisScope&&a.capacitySeason===b.capacitySeason;}
  function ensureCatalog(){const id=currentCatalogIdentity();if(!id||ctx.busy||sameCatalogIdentity(ctx.n1CatalogIdentity,id))return;const key=JSON.stringify(id);if(catalogRequestKey===key||catalogFailedKey===key)return;catalogRequestKey=key;void ctx.loadN1Catalog(scope,id.capacitySeason).then(()=>{if(sameCatalogIdentity(ctx.n1CatalogIdentity,id)){selectedIds.clear();for(const candidateId of defaultN1CandidateIds(ctx.n1CatalogResult?.candidates||[]))selectedIds.add(candidateId);catalogFailedKey='';}else catalogFailedKey=key;render();}).catch(()=>{catalogFailedKey=key;render();});}
  function updateYtmOptions(select:HTMLSelectElement,tmSelect:HTMLSelectElement){const sites=ctx.network?.sites||[],areas=[...new Map(sites.map(s=>[s.areaId,s.areaName||s.areaId])).entries()].sort((a,b)=>a[1].localeCompare(b[1],'tr'));const old=select.value;select.innerHTML='<option value="">Tüm YTM’ler</option>'+areas.map(([id,label])=>`<option value="${h(id)}">${h(label)}</option>`).join('');if(areas.some(([id])=>id===old))select.value=old;const oldTm=tmSelect.value,available=sites.filter(s=>!select.value||s.areaId===select.value).sort((a,b)=>a.name.localeCompare(b.name,'tr'));tmSelect.innerHTML='<option value="">Tüm TM’ler</option>'+available.map(s=>`<option value="${h(s.id)}">${h(s.name)}</option>`).join('');if(available.some(s=>s.id===oldTm))tmSelect.value=oldTm;}
  function catalogRows():N1CatalogCandidate[]{const catalog=ctx.n1CatalogResult;if(!catalog)return[];const classes:N1SourceClass[]=[...(lineCheck.checked?['ElmLne' as const]:[]),...(trafoCheck.checked?['ElmTr2' as const]:[])],range=bandRange(candidateVoltage.value as VoltageBandFilter),includeIslanding=screenability.value==='SCREENABLE_ISLANDING',filter:Parameters<typeof filterN1CatalogCandidates>[1]={sourceClasses:classes,minVoltageKv:range.minVoltageKv,maxVoltageKv:range.maxVoltageKv,screenability:includeIslanding?'ALL':screenability.value as N1CatalogScreenability,search:candidateSearch.value,ytmId:ytm.value||undefined,tmId:tm.value||undefined};const rows=filterN1CatalogCandidates(catalog.candidates,filter);return includeIslanding?rows.filter(isDefaultN1Candidate):rows;}
  function selectFiltered(){for(const c of catalogRows())selectedIds.add(c.candidateId);render();}
  function selectCatalog(){for(const c of ctx.n1CatalogResult?.candidates||[])selectedIds.add(c.candidateId);render();}
  function voltageOptions(value:HTMLSelectElement){return bandRange(value.value as VoltageBandFilter);}
  function readOptions():N1ScreenOptions{const types:N1SourceClass[]=[...(lineCheck.checked?['ElmLne' as const]:[]),...(trafoCheck.checked?['ElmTr2' as const]:[])],range=voltageOptions(candidateVoltage);return{candidateTypes:types,minVoltageKv:range.minVoltageKv??66,maxVoltageKv:range.maxVoltageKv,capacitySeason:season.value as CapacitySeason,selectedCandidateIds:[...selectedIds].sort((a,b)=>a.localeCompare(b)),analysisScope:scope};}
  function findingVoltage(finding:ModelQualityFinding):number|null{const n=ctx.network;if(!n||!finding.entityId)return null;const id=finding.entityId,b=n.buses.find(x=>x.id===id);if(b)return b.vnKv;const l=n.lines.find(x=>x.id===id);if(l)return l.fastParameters?.vnKv??l.vnKv;const t=n.transformers.find(x=>x.id===id);if(t)return Math.max(t.vnKv,t.lvKv);const g=n.generators.find(x=>x.id===id);return g?n.buses.find(x=>x.id===g.bus)?.vnKv??null:null;}
  function currentQuality(){const result=ctx.modelQualityResult,n=ctx.network,expected=selectedScenario();return!!result&&!!n&&result.modelHash===n.modelHash&&ctx.modelQualityScenarioHash===scenarioSignature(expected)&&ctx.modelQualityAnalysisScope===scope;}
  function currentN1(){const n=ctx.network,result=ctx.n1Result;if(!n||!result)return false;const scenario=selectedScenario(),current=n1OptionsIdentity(n,scenario,readOptions()),saved=result.identity;return current.modelHash===saved.modelHash&&current.scenarioHash===saved.scenarioHash&&current.optionsHash===saved.optionsHash&&current.engineVersion===saved.engineVersion;}
  function groupCounts(rows:readonly ModelQualityFinding[]){const map=new Map<string,number>();for(const item of rows)map.set(item.code,(map.get(item.code)||0)+1);return[...map].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]));}
  function renderScope(){scopeSelect.value=scope;const changes=Object.entries(ctx.scenario.current).filter(([k])=>k!=='energizations').reduce((n,[,v])=>n+(Array.isArray(v)?v.length:Object.keys(v as object).length),0);scenarioCount.textContent=scope==='base'?'Baz model verileri':`Aktif senaryo · ${changes} değişiklik`;
    if(active==='scenarios')ensureCatalog();}
  function renderQuality(){qualityControls.hidden=false;qualityFilters.hidden=false;qualityStatus.hidden=false;candidateControls.hidden=true;candidateStatus.hidden=true;progressPanel.hidden=true;candidateContent.hidden=true;resultsNotice.hidden=true;resultsControls.hidden=true;content.hidden=false;
    const result=ctx.modelQualityResult,n=ctx.network;runQuality.disabled=ctx.busy||!n;qualityCsv.disabled=qualityJson.disabled=!currentQuality();qualityStatus.textContent=!n?'Önce model yükleyin.':!result?'Modeli değiştirmeden kalite denetimini çalıştırın.':!currentQuality()?'Seçili kapsam için bulgular güncel değil.':`${result.summary.total} bulgu · ${scope==='base'?'Baz Model':'Aktif Senaryo'} · ${result.modelHash.slice(0,12)}`;content.replaceChildren(qualityStatus);
    if(!currentQuality()||!result)return;const severityCards=element('div','ga-card-grid');for(const level of severityOrder){const card=element('div','ga-card');card.innerHTML=`<small>${severityLabels[level]}</small><strong>${result.summary.counts[level]}</strong>`;severityCards.append(card);}content.append(severityCards);
    const groups=groupCounts(result.findings);qualityGroupFilter.innerHTML='<option value="">Tüm bulgu kodları</option>'+groups.map(([code,count])=>`<option value="${h(code)}">${h(code)} · ${count.toLocaleString('tr-TR')}</option>`).join('');qualityGroupFilter.value=qualityGroup;
    const summary=element('div','ga-table-wrap'),groupTable=element('table','ga-table');groupTable.innerHTML=`<thead><tr><th>Bulgu kodu</th><th>Adet</th></tr></thead><tbody>${groups.map(([code,count])=>`<tr><td>${h(code)}</td><td>${count}</td></tr>`).join('')}</tbody>`;summary.append(groupTable);content.append(element('h3','','Bulgu grupları'),summary);
    const q=qualitySearch.value.toLocaleLowerCase('tr-TR'),min=Number(qualityVoltageFilter.value)||0;let rows=[...result.findings].filter(x=>(!qualitySeverity.value||x.severity===qualitySeverity.value)&&(!qualityCategory.value||x.category===qualityCategory.value)&&(!qualityGroup||x.code===qualityGroup)&&(!min||(findingVoltage(x)??0)>=min)&&(!q||`${x.code} ${x.entityName||''} ${x.entityId||''} ${x.field||''} ${qualityPresentation(x).message} ${qualityPresentation(x).impact}`.toLocaleLowerCase('tr-TR').includes(q)));rows.sort((a,b)=>compareQuality(a,b,qualitySort)*(qualityDirection==='asc'?1:-1));qualityPage=Math.min(qualityPage,Math.max(0,Math.ceil(rows.length/20)-1));const pageRows=rows.slice(qualityPage*20,qualityPage*20+20),wrap=element('div','ga-table-wrap'),table=element('table','ga-table');
    table.innerHTML=`<thead><tr>${[['severity','Önem'],['code','Kod'],['category','Kategori'],['equipment','Ekipman'],['field','Alan'],['message','Bulgu'],['impact','Hesaplama etkisi']].map(([key,label])=>`<th><button class="ga-sort" data-sort="${key}">${label}${qualitySort===key?(qualityDirection==='asc'?' ▲':' ▼'):''}</button></th>`).join('')}</tr></thead><tbody>${pageRows.map(x=>{const p=qualityPresentation(x);return`<tr data-id="${h(x.id)}" class="${x.id===selectedFinding?'ga-selected':''}"><td>${severityLabels[x.severity]}</td><td>${h(x.code)}</td><td>${categoryLabels[x.category]}</td><td>${h(x.entityName||x.entityId||x.entityClass||'—')}<small>${h(x.entityClass||'')} ${h(x.entityId||'')}</small></td><td>${h(x.field||'—')}</td><td>${h(p.title)} · ${h(p.message)}</td><td>${h(p.impact)}</td></tr>`;}).join('')}</tbody>`;
    table.querySelectorAll<HTMLButtonElement>('th button').forEach(b=>b.onclick=()=>{if(qualitySort===b.dataset.sort)qualityDirection=qualityDirection==='asc'?'desc':'asc';else{qualitySort=b.dataset.sort||'severity';qualityDirection='asc';}render();});table.querySelectorAll<HTMLTableRowElement>('tbody tr').forEach(row=>row.onclick=()=>{selectedFinding=row.dataset.id||null;render();});wrap.append(table);content.append(wrap,pager(rows.length,qualityPage,p=>{qualityPage=p;render();}),qualityDetail(result.findings.find(x=>x.id===selectedFinding)));
  }
  function qualityDetail(finding:ModelQualityFinding|undefined):HTMLElement{if(!finding)return element('p','ga-muted','Bir bulgu seçin.');const p=qualityPresentation(finding),box=element('div','ga-panel');box.innerHTML=`<h3>${h(p.title)} · ${severityLabels[finding.severity]}</h3><p><strong>Sınıf / FID:</strong> ${h(finding.entityClass||'—')} / ${h(finding.entityId||'—')} · ${h(finding.entityName||'')}</p><p><strong>Kaynak alanı / değer / birim:</strong> ${h(finding.field||'—')} · ${h(JSON.stringify(finding.originalValue))} → ${h(JSON.stringify(finding.normalizedValue))} ${h(finding.unit||'')}</p><p><strong>Bulgu:</strong> ${h(p.message)}</p><p><strong>Hesaplama etkisi:</strong> ${h(p.impact)}</p><p><strong>Kaynak referansları:</strong> ${h(JSON.stringify(finding.sourceRefs))}</p>`;const actions=element('div','ga-row-actions');if(finding.entityId&&finding.entityClass)actions.append(button('Haritada göster',()=>ctx.select(finding.entityId!,finding.entityClass!,'map')),button('Envanter',()=>ctx.select(finding.entityId!,finding.entityClass!,'inventory')),button('Tek Hat',()=>ctx.select(finding.entityId!,finding.entityClass!,'sld')));box.append(actions);return box;}
  function renderScenarios(){qualityControls.hidden=true;qualityFilters.hidden=true;qualityStatus.hidden=true;candidateControls.hidden=false;candidateStatus.hidden=false;progressPanel.hidden=!(ctx.busy&&ctx.n1Progress);candidateContent.hidden=false;resultsNotice.hidden=true;resultsControls.hidden=true;content.hidden=true;runN1.disabled=ctx.busy||selectedIds.size===0||!sameCatalogIdentity(ctx.n1CatalogIdentity,currentCatalogIdentity());cancelN1.disabled=!ctx.busy;
    updateYtmOptions(ytm,tm);const catalog=ctx.n1CatalogResult;if(!catalog||!sameCatalogIdentity(ctx.n1CatalogIdentity,currentCatalogIdentity())){candidateStatus.textContent=ctx.busy?'N-1 aday kataloğu hazırlanıyor…':'Aday kataloğu kapsam için güncel değil.';candidateContent.replaceChildren();}else{
      const rows=catalogRows(),classFor=(c:N1CatalogCandidate)=>c.sourceClass==='ElmTr2'?'Trafo':'Hat';
      candidateStatus.innerHTML=`<div class="ga-card-grid"><div class="ga-card"><small>Toplam aday</small><strong>${catalog.counts.total}</strong></div><div class="ga-card"><small>DC taranabilir</small><strong>${catalog.counts.screenable}</strong></div><div class="ga-card"><small>Ada ayıran</small><strong>${catalog.counts.islanding}</strong></div><div class="ga-card"><small>Taranamayan</small><strong>${catalog.counts.unscreenable}</strong></div><div class="ga-card"><small>Filtre sonucu</small><strong>${rows.length}</strong></div><div class="ga-card"><small>Seçili</small><strong>${selectedIds.size}</strong></div></div><p>YTM/TM kapsamı: adayın en az bir ucu seçili TM ile ilişkili olmalıdır.</p><p>Trafo toplamı: ${catalog.candidates.filter(x=>x.sourceClass==='ElmTr2').length} · taranabilir ${catalog.candidates.filter(x=>x.sourceClass==='ElmTr2'&&x.screenable).length} · taranamayan ${catalog.candidates.filter(x=>x.sourceClass==='ElmTr2'&&!x.screenable).length}. ${scope==='base'?'Baz Model':'Aktif Senaryo'} · ${season.options[season.selectedIndex]?.text||''}</p>`;
      const sorted=sortN1(rows,candidateSort,candidateDirection);candidatePage=Math.min(candidatePage,Math.max(0,Math.ceil(sorted.length/25)-1));const page=sorted.slice(candidatePage*25,candidatePage*25+25),wrap=element('div','ga-table-wrap'),table=element('table','ga-table');table.innerHTML=`<thead><tr><th>Seç</th>${[['name','Aday'],['type','Tip'],['kv','kV'],['status','Taranabilirlik']].map(([key,label])=>`<th><button class="ga-sort" data-sort="${key}">${label}${candidateSort===key?(candidateDirection==='asc'?' ▲':' ▼'):''}</button></th>`).join('')}<th>Uçlar · TM</th></tr></thead><tbody>${page.map(c=>`<tr data-id="${h(c.candidateId)}"><td><input type="checkbox" aria-label="${h(c.name)} seç" ${selectedIds.has(c.candidateId)?'checked':''}></td><td>${h(c.name)}<small>${h(c.equipmentId)}</small></td><td>${classFor(c)}</td><td>${f(c.vnKv)}</td><td>${c.topology==='NON_ISLANDING'?'Taranabilir':c.topology==='ISLANDING'?'Ada ayıran':'Taranamıyor'}${c.ratingAvailable?'':' · Kesinti kapasitesi yok'}</td><td>${h(c.from)} → ${h(c.to)}<small>${h([...c.fromSiteIds,...c.toSiteIds].map(id=>ctx.network?.sites.find(s=>s.id===id)?.name||id).join(' · ')||'TM eşleşmesi yok')}</small></td></tr>`).join('')}</tbody>`;
      table.querySelectorAll<HTMLButtonElement>('th button').forEach(b=>b.onclick=()=>{if(candidateSort===b.dataset.sort)candidateDirection=candidateDirection==='asc'?'desc':'asc';else{candidateSort=b.dataset.sort||'name';candidateDirection='asc';}render();});table.querySelectorAll<HTMLTableRowElement>('tbody tr').forEach(row=>{const checkbox=row.querySelector<HTMLInputElement>('input[type=checkbox]')!;checkbox.onchange=()=>{const id=row.dataset.id!;if(checkbox.checked)selectedIds.add(id);else selectedIds.delete(id);render();};});wrap.append(table);candidateContent.replaceChildren(wrap,pager(sorted.length,candidatePage,p=>{candidatePage=p;render();}));
    }
    cancelN1.hidden=!(ctx.busy&&ctx.n1Progress);
  }
  function renderResults(){qualityControls.hidden=true;qualityFilters.hidden=true;qualityStatus.hidden=true;candidateControls.hidden=true;candidateStatus.hidden=true;candidateContent.hidden=true;progressPanel.hidden=!(ctx.busy&&ctx.n1Progress);resultsNotice.hidden=false;resultsControls.hidden=false;content.hidden=false;n1Results.render(content);}
  function renderProgressOutside(){
    if(ctx.busy&&ctx.n1Progress){const p=ctx.n1Progress;progressPanel.hidden=false;progressPanel.className='ga-notice ga-n1-progress';progressPanel.innerHTML=`<strong>N-1 taraması çalışıyor · ${p.percent}%</strong><progress max="100" value="${p.percent}"></progress><p>${p.completed.toLocaleString('tr-TR')} / ${p.total.toLocaleString('tr-TR')} aday · ${progressLabels[p.stage]} · ${(p.elapsedMs/1000).toFixed(1)} sn · Tarama ${p.screenedSoFar} · Tahmini ihlal ${p.violationCountSoFar} · Ada ayıran ${p.islandingCount} · Taranamayan ${p.unsupportedCount}</p><button type="button" class="ga-button" id="n1ProgressCancel">İptal</button>`;progressPanel.querySelector('#n1ProgressCancel')?.addEventListener('click',()=>ctx.cancel());return;}
    if(active==='results'&&ctx.n1Progress&&currentN1()&&ctx.n1Result){const p=ctx.n1Progress,violations=ctx.n1Result.candidates.reduce((sum,c)=>sum+c.estimatedOverloadCount,0);progressPanel.hidden=false;progressPanel.className='ga-notice ga-n1-complete';progressPanel.textContent=`✓ Tamamlandı · ${p.completed.toLocaleString('tr-TR')} aday · ${(p.elapsedMs/1000).toFixed(1)} sn · ${violations.toLocaleString('tr-TR')} tahmini ihlal`;}else progressPanel.hidden=true;
  }
  function exportQualityJson(){if(currentQuality())downloadText(JSON.stringify(ctx.modelQualityResult,null,2),'GridAnalyzer-model-quality.json','application/json;charset=utf-8');}
  function exportQualityCsv(){const result=currentQuality()?ctx.modelQualityResult:null;if(!result)return;downloadText(csvDocument([['Önem','Kod','Kategori','Ekipman','FID','Alan','Bulgu','Hesaplama etkisi','Kaynak referansları'],...result.findings.map(x=>{const p=qualityPresentation(x);return[severityLabels[x.severity],x.code,categoryLabels[x.category],x.entityName,x.entityId,x.field,p.message,p.impact,JSON.stringify(x.sourceRefs)];})]),'GridAnalyzer-model-quality.csv','text/csv;charset=utf-8');}
  function pager(total:number,page:number,setPage:(page:number)=>void):HTMLElement{const pages=Math.ceil(total/20),bar=element('div','ga-pager');bar.append(button('Önceki',()=>setPage(Math.max(0,page-1))),element('span','',`${total.toLocaleString('tr-TR')} kayıt · ${pages?page+1:0}/${pages}`),button('Sonraki',()=>setPage(Math.min(Math.max(0,pages-1),page+1))));(bar.firstElementChild as HTMLButtonElement).disabled=page<=0;(bar.lastElementChild as HTMLButtonElement).disabled=page>=pages-1;return bar;}
  function render(){qualityTab.setAttribute('aria-pressed',String(active==='quality'));scenarioTab.setAttribute('aria-pressed',String(active==='scenarios'));resultTab.setAttribute('aria-pressed',String(active==='results'));renderScope();qualityCsv.disabled=qualityJson.disabled=!currentQuality();if(active==='quality')renderQuality();else if(active==='scenarios')renderScenarios();else renderResults();renderProgressOutside();}
  return{element:root,render};
}
